### ISSUE TITLE
Wallet error after upgrade 

### ISSUE THREAD

**Issue by Vurdalacky** [neo-project/neo-cli#105]
Hello. Unfortunately our old version stopped uploading blocks:
NEO-CLI Version: 2.3.4.0
neo> open wallet wallet
password: ********************
neo> show state
Height: 1860095/1860095, Nodes: 4

I try to upgrade wallet, but I'm getting an error when I open my wallet. Downloaded a new archive and copied the wallet file from the previous directory. Tell me what I need to do for upgrade.
NEO-CLI Version: 2.7.0.0
neo> open wallet wallet
password: ********************
error

**Comment by metachris** [comment]
The wallet upgrade creates a new wallet file in JSON format, right? Have you tried opening that JSON file specifically?

**Comment by Vurdalacky** [comment]
No, I downloaded the last release neo-cli. Сopied the binary wallet from the previous directory neo-cli.

**Comment by metachris** [comment]
Can you try upgrading the binary wallet to JSON with `upgrade wallet` and then opening it?

**Comment by erikzhang** [comment]
Change the extension name of the wallet file to `.db3`.

**Comment by Vurdalacky** [comment]
Hello.

In version 2.3.4 make upgrade wallet and now i haw 2 files 'wallet' and 'wallet.old.db3'.
Try open  'wallet' in NEO-CLI Version: 2.7.0.0
neo> open wallet wallet
password: ********************
error

Both of these files are not json.

**Comment by Vurdalacky** [comment]
Thanks erikzhang. Problem solvd at new version NEO-CLI Version: 2.7.1.0

> Change the extension name of the wallet file to .db3.
