### ISSUE TITLE
Bug - Assets not showing, (both Ubuntu 16 & Win10)

### ISSUE THREAD

**Issue by usslindstrom** [neo-project/neo-cli#113]
Using this app, it is not showing any assets listed in both Ubuntu & Windows.

The software connects just fine, however, even after waiting multiple hours, and multiple "rebuild index" attempts it is unable to show what assets the wallet contains.

neo> show state
Height: 93788/94059/1816414, Nodes: 5

neo> show node
::ffff:47.94.164.49 port:10333 listen:10333 [1/5]
::ffff:101.132.67.230 port:10333 listen:10333 [2/5]
::ffff:47.88.53.224 port:10333 listen:10333 [3/5]
::ffff:47.89.178.72 port:10333 listen:10333 [4/5]
::ffff:47.91.92.192 port:10333 listen:10333 [5/5]

neo> list address
AMuiZnPhmH..........

neo> list asset
neo> show gas
unavailable: 0
  available: 0

This issue had been brought up already, but closed with no resolution.
https://github.com/neo-project/neo-cli/issues/50

**Comment by enVolt** [comment]
I'm facing the same issue. I assumed that `list asset` will show the assets except Neo and Gas, in case transacted. I'm doing the testing on CoZTestnet, and tried getting help from there. 

I've received some gas and neo from CoZ faucet. If I do get transaction for that hash, it is giving me the transaction. I'm able to verify that vout has my wallet's standard address (RPC Call). But if I'm doing getbalance for the asset, it is giving me 0. 

getaccountstate for my address returns nothing -

```json
{
    "id": "1",
    "jsonrpc": "2.0",
    "result": {
        "balances": [],
        "frozen": false,
        "script_hash": "0xf145739a3b8168ec2c1194b1623a0f56595d7b54",
        "version": 0,
        "votes": []
    }
}
```

I'm on version 2.7.1.0, if that helps. Next thing I'm gonna try is try an older version.

**Comment by enVolt** [comment]
Have tried 2.3.4, 2.7.0

Same issue. Do I need to specify something like I'll be storing x-y assets when creating a wallet?

**Comment by usslindstrom** [comment]
I used the Neon wallet, and imported the wallet created in neo-cli.  It shows everything just fine, and I can send and receive using it.

Looks to be just a bug with the cli version.

**Comment by enVolt** [comment]
Ok, I raised a false alarm. I just figured out somehow my balance is moving to a different address

https://coz.neoscan-testnet.io/address/APUaC8wxx8jynfMD3a5KBxi8ZzW94tY9Yv

As soon as I received the money, it got transferred to some other account. (Still figuring out how this happened)

**Comment by shivam2901** [comment]
I am facing same issue and even my funds are getting transferred into same address as above AGQGKFJ7MTMvePZcz1KEmd9UVWzZbRsotC
I also raised another issue https://github.com/neo-project/neo/issues/178 , but nobody understands.

It's a bug in neo-cli I think, because whenever I create wallet using NEON then my funds stay in my wallet but when I create using neo-cli it got transferred in AGQGKFJ7MTMvePZcz1KEmd9UVWzZbRsotC everytime

Please look into this, blocked from long time
