### ISSUE TITLE
rebuild wallet index error

### ISSUE THREAD

**Issue by juliavi** [neo-project/neo-cli#114]
while trying to execute `rebuild wallet index`
I get "error" which doesn't say much about the problem.
If the node isn't fully synced - will rebuild fail?
Since errors don't return a stack trace, it's hard to handle CLI errors. 
It would help if errors would be more informative.

**Comment by PeterLinX** [comment]
@juliavi The command is "rebuild index" and you should input it after you open wallet.

**Comment by juliavi** [comment]
`rebuild wallet` also return "error". 
Should I wait for a full sync? It's impossible to rebuild based on what's synced so far?

**Comment by erikzhang** [comment]
```
rebuild index
```
