### ISSUE TITLE
unhandle exception when exit

### ISSUE THREAD

**Issue by PeterLinX** [neo-project/neo-cli#115]
![neo_node - screen 0 root izbp16hzcn38ypxslp98jlzhomeneo_nodeneo-cli - xshell 5 free for homeschool](https://user-images.githubusercontent.com/18521923/36213584-0c8e6ce8-11e2-11e8-914b-078ade190282.jpg)

**Comment by panther142** [comment]
I have also seen this behaviour when exiting neo-cli using 2.7.1 in the past few days - same error message.
