### ISSUE TITLE
sendrawtransaction failure reason

### ISSUE THREAD

**Issue by enVolt** [neo-project/neo-cli#116]
I'm signing the transaction using neon-js. When I'm sending the serialized transaction via sendrawtransaction rpc call, it's giving me false result. 

Is there any way I can check why the transaction was failed?

Couldn't find anything relevant in the documentation

**Comment by enVolt** [comment]
Update - I've figured out what I was doing wrong. But still, it would be great to have this functionality in neo-cli. Maybe instead of `"result": false`, it could return some error as why it was failed.

**Comment by chrismpalmer** [comment]
I agree with this I am getting a false and have no idea it was just working..

**Comment by guotie** [comment]
agreed.

**Comment by guotie** [comment]
I have the same question, what method did you solve this problem?

**Comment by enVolt** [comment]
> I have the same question, what method did you solve this problem?

I was providing the used UTXOs
