### ISSUE TITLE
purpose of ports

### ISSUE THREAD

**Issue by enVolt** [neo-project/neo-cli#118]
neo-cli listens to following 3 ports (mainnet config) - 

* 10332 - RPC Port
* 10333 - P2P 
* 10334 - P2P Ws

If I want to secure my node, 10332 is behind firewall and accessible to me only.

Which other port I need to make publicly accessible in order to enable syncing. Do I need to open both the ports (10333, 10334), or just 10333 will suffice

**Comment by shargon** [comment]
With 10333 is enough

You can follow this useful guide
https://github.com/CityOfZion/standards/blob/master/nodes.md
