### ISSUE TITLE
application-log dir

### ISSUE THREAD

**Issue by bitcodernull** [neo-project/neo-cli#124]
how to set the application-log dir?
now the default dir is the root-path of  neo-cli

**Comment by kokahunter** [comment]
The dir is created automatically, there is no parameter in config.json anymore. See: https://github.com/neo-project/neo-cli/commit/020b3944f353e7bd524104041f9b60c10ae61d44

Note,
1 that the notification files changed from block based to transaction based
2 that you can now use the api call 'getapplicationlog' with transaction hash as input to get the notification

If you want to set the application log dir manually/in config, you could build from source with editing Settings.cs:
https://github.com/neo-project/neo-cli/commit/020b3944f353e7bd524104041f9b60c10ae61d44#diff-0327b59f4dd09986f49db7500602d9a9R38

**Comment by bitcodernull** [comment]
i see
thanks, i will build it.

if the parameter can be setted in  config.json , it will be very  convenient.
i install the neo-cli on system disk and want to place data on data disk

**Comment by erikzhang** [comment]
resolved in 14fb7b9570a5168d84dc742afe43ff21348d153b
