### ISSUE TITLE
getapplicationlog error  

### ISSUE THREAD

**Issue by 503945930** [neo-project/neo-cli#125]
```
dotnet neo-cli.dll --rpc --log
```

```
curl -X POST \
  http://114.215.30.71:10332 \
  -H 'Content-Type: application/json' \
  -d '{
  "jsonrpc": "2.0",
  "method": "getapplicationlog",
  "params": ["0xd1c7ea5f406e0f3ade3e8a9cd575a7b08a73f440ede947d16c325c09eaedb33e"],
  "id": 1
}
```

### result 
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -100,
        "message": "Unknown transaction"
    }
}
```

this is  a right  InvocationTransaction， but get a error.

### right result 
```
“contract" : "0xac116d4b8d4ca55e6b6d4ecce2192039b51cccc5"
"txid" : "0xd1c7ea5f406e0f3ade3e8a9cd575a7b08a73f440ede947d16c325c09eaedb33e"
```

and contain 3 transactions

```
cli version : 2.7.3
```

**Comment by erikzhang** [comment]
If you start NEO-CLI without the startup parameter `--log`, it will not record the logs of the `InvocationTransaction` in the new blocks.

**Comment by 503945930** [comment]
I had  add **--log**   parameter

**Comment by 503945930** [comment]
```
curl -X POST \
  http://114.215.30.71:10332 \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: b08e40e2-bd74-445b-a97b-de01b2ded044' \
  -d '{
  "jsonrpc": "2.0",
  "method": "getapplicationlog",
  "params": ["f9771aff6d011f57e245f89e6a85ed80c5fbd5036ecd3bf1ece6ccc3cadb8701"],
  "id": 1
}
'

return json
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -100,
        "message": "Unknown transaction"
    }
}
```


‘’‘
https://neotracker.io/tx/f9771aff6d011f57e245f89e6a85ed80c5fbd5036ecd3bf1ece6ccc3cadb8701


’‘’

**Comment by PeterLinX** [comment]
@503945930 this is a InvocationTransaction that transfer global asset gas. It didn't change any status in neo  blockchain storage. So it will not be recorded in application log. If this tx change nep5 asset status or any status in vm then it will be recorded in application log.

**Comment by PeterLinX** [comment]
@erikzhang my node returned "Unknown transaction" too, it's not caused by --log. I check the transaction again, I doubt about my answer a little bit.

**Comment by erikzhang** [comment]
It will record every `InvocationTransaction`, even if the contract fails.

**Comment by kokahunter** [comment]
My node saved the transaction log and rpc call working as intended. 

@503945930 I think --log has to be active at the time when the block of the given transaction (block 1870453) is beeing processed by neo-cli. You cannot get the application log of InvocationTransactions in blocks that were saved by neo-cli without having --log active.

So is there a way to get application logs for already saved blocks, except for a full resync? For example after rebuilding the database with chain.acc?

**Comment by erikzhang** [comment]
Rebuilding the database with chain.acc and full resync are equivalent.

**Comment by 503945930** [comment]
@kokahunter  you node  rpc ?

**Comment by kokahunter** [comment]
@erikzhang Yes I agree. But still the resync with chain.acc and --log active won't save any application log  since the ApplicationExecuted event is registered after ImportBlocks.
https://github.com/neo-project/neo-cli/blob/master/neo-cli/Shell/MainService.cs#L825-L851

So maybe check for --log and do event registration before looking for chain.acc file?

@503945930 No public node currently. But you may just put `LevelDBBlockchain.ApplicationExecuted += LevelDBBlockchain_ApplicationExecuted;` before this line (https://github.com/neo-project/neo-cli/blob/master/neo-cli/Shell/MainService.cs#L811) and resync with chain.acc file. Neo-Cli will then save every application log. I just did this and it worked fine.

**Comment by erikzhang** [comment]
>So maybe check for --log and do event registration before looking for chain.acc file?

Good suggestion. Have done in e3c95e2a5f42f33c5b31d8dc306f721a878cb364
