### ISSUE TITLE
What's the difference between --record-notifications and --log

### ISSUE THREAD

**Issue by khelle** [neo-project/neo-cli#126]
As the title says - what's the difference between `--record-notificiations` nad `--log flags`? I see, since release of v2.7.1, the documentation started to use `--log` in place where older suggested `--record-notifications`, but it does not explain neither why this has changed nor if it is does the same, but is called differenty. What's more, both flags are still accepted as valid CLI flags, so I am not sure if they are really the same or not. Can someone explain these two to me? Also, is the `--log` one really needed for me to properly deal with the NTP5 tokens? I mean, it seems to heavily burden the node itself, but since it was absent in older version it seems people were able to deal with NTP5 without this option - or am I wrong?

**Comment by erikzhang** [comment]
The parameter "--record-notificiations" is deprecated and is no longer available in the latest version of the clients.
The parameter "--log" is more powerful. It not only provides all notifications and virtual machine running status, but also enables developers to query these states through RPC commands.
