### ISSUE TITLE
when to support ubuntu 17

### ISSUE THREAD

**Issue by OliviaSong** [neo-project/neo-cli#127]

**Comment by erikzhang** [comment]
The latest release has supported all linux: https://github.com/neo-project/neo-cli/releases/tag/v2.7.4

**Comment by hunjixin** [comment]
@erikzhang  leveldb support?

**Comment by lock9** [comment]
Hello @OliviaSong, are you still facing problems? If this is solved, could you please close this issue?
 Thank you.
