### ISSUE TITLE
Inconsistent wallet state?

### ISSUE THREAD

**Issue by Keref** [neo-project/neo-cli#129]
Hello, I lost some tokens on the testnet while trying to interact with the RPC.

I use the windows NEO cli for development on my local machine, and use the linux version on a vps, for in situ testing.

I also have 298 unspent NEO, which appear on the test neotracker , [see here](https://imgur.com/OFZngBm). I doesn't show up in the wallet. I copied the wallet on my machine, erased the testchain and resynchronized everything, rebuilt the index a couple times, still doesn't appear.

So...

- Why can there be wallet inconsistency? My understanding is that somewhere in the wallet the block height is recorded, however rebuilding the index should correct any potential mistake, shouldn't it?
- I had my wallet opened in several locations at a time (2 instances of neo-cli), can this create inconsistencies?
- How do I get my funds back? Can I make a new clean wallet by copying a part of the JSON into a new file?
- or, can I extract the private key and manually send the funds from some kind of NEO myetherwallet? (but lately neotracker is not really working)

**Comment by shargon** [comment]
If the problem persist, please reopen the issue
