### ISSUE TITLE
Unable to load DLL 'libleveldb' on CentOS release

### ISSUE THREAD

**Issue by jonatanblockchain** [neo-project/neo-cli#13]
**Error:** 
Libleveldb.dll is missing on CentOS release, but its included on 'neo-cli-portable'. 

**How to reproduce:**
```
[root@localhost ~]# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)

sudo yum install libunwind libicu unzip wget
curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?linkid=848821
sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
sudo ln -s /opt/dotnet/dotnet /usr/local/bin

[root@localhost ~]# dotnet --version
1.0.4
[root@localhost ~]# dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /opt/dotnet/sdk/1.0.4

```
**neo-cli-centos.7-x64.zip**
```
wget https://github.com/neo-project/neo-cli/releases/download/v2.0.1/neo-cli-centos.7-x64.zip
sudo mkdir -p /opt/neo-cli && sudo unzip neo-cli-centos.7-x64.zip -d /opt/neo-cli
cd /opt/neo-cli/neo
dotnet neo-cli.dll /rpc

```

![centos](https://user-images.githubusercontent.com/29895459/29228820-a5757266-7edb-11e7-90f7-d23b42076f52.png)

**neo-cli-portable.zip**
```

wget https://github.com/neo-project/neo-cli/releases/download/v2.0.1/neo-cli-portable.zip
sudo mkdir -p /opt/neo-cli && sudo unzip neo-cli-portable.zip -d /opt/neo-cli
cd /opt/neo-cli/neo
dotnet neo-cli.dll /rpc
```
![centos-portable](https://user-images.githubusercontent.com/29895459/29228899-f94bb4fe-7edb-11e7-9a2f-7de9fbe8a84a.png)

**Comment by erikzhang** [comment]
see #6

**Comment by jonatanblockchain** [comment]
Erik,
You are right, you have to install leveldb-devel. Tested on a fresh installation and is working. I will update documentation asap. You can close the issue, and use this one as a reference from CentOS installations.

**Step-by-step CentOS Instalation.**

```
cat /etc/centos-release
sudo yum update
sudo yum install epel-release unzip wget

sudo yum install libunwind libicu 
sudo curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?linkid=848821
sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
sudo ln -s /opt/dotnet/dotnet /usr/local/bin

wget https://github.com/neo-project/neo-cli/releases/download/v2.0.1/neo-cli-centos.7-x64.zip
sudo mkdir -p /opt/neo-cli && sudo unzip neo-cli-centos.7-x64.zip -d /opt/neo-cli
cd /opt/neo-cli/neo
sudo dotnet neo-cli.dll /rpc
```

![2017-08-13_10-22-47](https://user-images.githubusercontent.com/29895459/29248160-654853ac-8011-11e7-9889-6f0d18dacf0d.png)

**Comment by erikzhang** [comment]
Thank you very much!

**Comment by i3bitcoin** [comment]
W: GPG error: https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EB3E94ADBE1229CF
W: The repository 'https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by jonatanblockchain** [comment]
Please, post the output of `sudo dotnet --info`

**Comment by i3bitcoin** [comment]
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by erikzhang** [comment]
You have installed .Net Core SDK 2.0, but we need 1.1
Don't worry, we will upgrade to 2.0 soon.

**Comment by devfive** [comment]
Hi,

I am struggling with neo-cli for some time and unfortunately didn't manage to run it as for now.

When I run `dotnet neo-cli.dll` I get `Segmentation fault` error. More info is available when I used diagnostics flag.

```
root@host:/home/neo/node# dotnet -d neo-cli.dll 
Telemetry is: Disabled
projectfactory: MSBUILD_EXE_PATH = /usr/share/dotnet/sdk/1.1.4/MSBuild.dll
projectfactory: MSBuild project path = 
projecttoolscommandresolver: ProjectFactory did not find Project.
Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-neo-cli.dll"
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

```
root@host:/home/neo/node# dotnet --info
.NET Command Line Tools (1.1.4)

Product Information:
 Version:            1.1.4
 Commit SHA-1 hash:  d2f3571419

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.1.4
```

Do you have any ideas what can be wrong?

Thanks in advance,
Regards
