### ISSUE TITLE
libleveldb.dll and sqlite3.dll cannot find

### ISSUE THREAD

**Issue by AhoGirl** [neo-project/neo-cli#134]
Can you provide libleveldb.dll and sqlite3.dll，please ？I cannot find them in any package....

**Comment by purplesoft-io** [comment]
You can copy these file from NEO-GUI (x86 or x64 folder. choose the correct arch.) and paste to bin/debug or bin/release... I've added leveldb project source code directly to visual studio and compile it in correct format .dll-x86/x64 and postbuild action copy it to target folder.
I hope can help.
