### ISSUE TITLE
stuck on block 2022689

### ISSUE THREAD

**Issue by sirnicolas21** [neo-project/neo-cli#138]
neo> version
2.7.4.0
neo> show state
Height: 0/2022689/2022689, Nodes: 9
neo> show node
::ffff:199.255.144.207 port:43466 listen:10333 height:2128213 [1/8]
::ffff:178.195.151.229 port:59739 listen:10333 height:2128506 [2/8]
::ffff:24.237.84.87 port:10333 listen:10333 height:2128944 [3/8]
::ffff:184.158.100.232 port:52356 listen:10333 height:2119126 [4/8]
::ffff:13.114.212.150 port:33755 listen:10333 height:2129071 [5/8]
::ffff:88.196.208.18 port:10333 listen:10333 height:2022689 [6/8]
::ffff:104.238.149.176 port:54012 listen:10333 height:1563489 [7/8]
::ffff:88.99.150.7 port:34512 listen:10333 height:2129153 [8/8]
neo>  show state
Height: 0/2022689/2022689, Nodes: 9

node stuck on block 2022689 for 2 days now.

**Comment by 6londe** [comment]
maybe same issue.
[https://neoexplorer.co/blocks](https://neoexplorer.co/blocks)

**Comment by sirnicolas21** [comment]
i synced whole chain 3 times and its unstuck now..... removed chain folder.... stuck.... removed stuck.... removed.... synced perfect...

im not closing issue since there is something wrong there.... not so critical but there is.
