### ISSUE TITLE
daemonizing the neo process

### ISSUE THREAD

**Issue by DaveWK** [neo-project/neo-cli#140]
I am trying to start the neo daemon with rpc and a wallet using the recommended:
` dotnet neo-cli.dll /rpc` command, but I don't see any documentation around how to get it to import a wallet by default and run in a way where it logs to files. Is there a way to import a wallet on start and have the rpc?

**Comment by purplesoft-io** [comment]
We have done it using neo and neo.vm nuget packages and start new project from scratch.
            
` 

            //function check file peers.dat
            CheckPeers();

            //init leveldb blockchain
            Blockchain = Blockchain.RegisterBlockchain(new LevelDBBlockchain($"Chain_{Message.Magic:X8}"));

            //on sync handler
            Blockchain.PersistCompleted += Blockchain_PersistCompleted;
            LocalNode = new LocalNode { UpnpEnabled = true };

            //Function load chain.acc - chain.acc.zip file
            BulkImportChainFile();

            //start node on port TCP-P2P
            LocalNode.Start(10333, 10334);

            //if .db3
            var masternodeOldWallet = UserWallet.Open("YOUR_WALLET_FULL_PATH", "W4LL3TP455W0RD");
            //GetWalletBalances(masternodeOldWallet);

            //if .json
            //var masternodeNewWallet = new NEP6Wallet("YOUR_WALLET_FULL_PATH"));
            //masternodeNewWallet.Unlock("W4LL3TP455W0RD");
            //GetWalletBalances(masternodeNewWallet);

            //if you want create new wallet
            //var newWallet = UserWallet.Create("YOUR_NEW_WALLET_FULL_PATH", "W4LL3TP455W0RD");
            //var na = newWallet.CreateAccount();
         
           .....HERE YOU CAN DO YOUR WORK.....NODE/WALLET/ACCOUNT ARE ACTIVE.....

            //save peers.dat before exit
            SavePeers();

            //dispose resources
            LocalNode.Dispose();
            Blockchain.Dispose();`

Let me know if useful. contact me at tiziano@purplesoft.io

**Comment by DaveWK** [comment]
thanks! do you think you would be able to contribute this as a pull request?

**Comment by purplesoft-io** [comment]
I'm trying to refactor some code to fit my requirements. In some days I can upload my version... but I implemented a small subset of neo-cli features.

**Comment by purplesoft-io** [comment]
Hello to all,
I've edited neo-cli command line parser to allow wallet unlock and start rpc.
this is the pull request link: https://github.com/neo-project/neo-cli/pull/151
and this is my forked branched repo: https://github.com/purplesoft-io/neo-cli/tree/neo-cli-daemon-with-wallet-unlock 

usage:
dotnet neo-cli.dll --rpcwallet "/home/user/walletpath/wallet.db3" "W4LL3tP4sSw0rD 01"
dotnet neo-cli.dll --rpcwallet "/home/user/walletpath/wallet.json" "W4LL3tP4sSw0rD 01"

tiziano@purplesoft.io

Donations are welcome XD we are developing NEO WEB PANEL MANAGER for NEO NODES (also private deploy of NEO blockchain).
NEO: AYUd4G2dNXAEyUxkZGyMdXAnJ396jJfNDz
ETC: 0x982e45402ad06d0a01f3e54732b28c76d9870422
BTC: 1HxdgF6WsvcRVNiXhz6jZgbD9eopvzAxap
ETH: 0x5cb3784e71710f681410d30d615a3b3bb3c24ff1

**Comment by purplesoft-io** [comment]
run as a daemon:
screen -dmS neod dotnet neo-cli.dll --rpcwallet "/home/user/walletpath/wallet.db3" "W4LL3tP4sSw0rD 01"
