### ISSUE TITLE
Not syncing

### ISSUE THREAD

**Issue by Pwnmanship** [neo-project/neo-cli#141]
Hi,

We've used the neo-cli for the last year with here and there some syncing problems. But since yesterday the neo-cli doesn't sync anymore. We've recompiled the lastest version and tried it on different machines on different locations but 'show state' keeps giving 0 or 1 nodes and doesn't sync. Sometimes we get like 20 blocks and then it doens't sync anymore.

**Comment by Pwnmanship** [comment]
If you look on http://monitor.cityofzion.io/ most of the neo.org seed nodes (which are in the config file) are offline. Maybe this has something to do with the problem?

**Comment by rad-p** [comment]
I got the same problem;
My nodes does not sync anymore, I have tried sync from genesis block and sync from chain.acc dump files. But it just does not work
