### ISSUE TITLE
Create get transaction list by json rpc api  with account parameter? 

### ISSUE THREAD

**Issue by kevingwang** [neo-project/neo-cli#142]
I want to get the transactions list with wallet account parameters  , but i can not find the json rpc api .
How to get transaction list by json rpc api  with account parameter?  Thanks!

**Comment by martysyuk** [comment]
Good question. Interesting to...

**Comment by skinderis** [comment]
No answer since 19th of April. @kevingwang @martysyuk  did you find an answer for that?
@erikzhang I need to get transactions by address too, is there any rpc method for that?

**Comment by kokahunter** [comment]
In neo-cli there is no rpc method to get the transactions list with wallet account parameter.

You could 
* Create a plugin. See for reference: https://github.com/neo-project/neo-plugins
* Query the neoscan api: https://neoscan.io/docs/index.html#api-v1-get-8

**Comment by skinderis** [comment]
@kokahunter thanks. Neoscan's API can get transactions by address. What do you think about getting transactions by wallet (wallet can have tons of addresses). And I know now that I need to get transactions by wallet.

**Comment by skinderis** [comment]
And I can't find documentation how to create a custom plugin.

**Comment by tulang3587** [comment]
Are there any plugins for this already? I really don't want to use outer API calls for this functionality.

**Comment by shargon** [comment]
@erikzhang what do you think that is better, a plugin, or now in neo3 store it inside an index `tx.hash > sender`

**Comment by erikzhang** [comment]
Plugin is better.

**Comment by lock9** [comment]
@erikzhang  a private plugin where he is the only person using it (close issue), or add a plugin to the official repository? (create a issue in neo plugins repository)

**Comment by erikzhang** [comment]
Add a plugin to the official repository.

**Comment by lock9** [comment]
Thanks Erik.
Guys, the issue has moved to [this](https://github.com/neo-project/neo-plugins/issues/105) repository.

**Comment by erikzhang** [comment]
![image](https://user-images.githubusercontent.com/10204923/61364766-0e123080-a8b9-11e9-9e48-77217efd18f0.png)
@lock9 You can use this button to transfer the issue, no need to close and re-create it.

**Comment by lock9** [comment]
Sorry Erik, I didn't know that. I wil use this feature next time. Thanks!
