### ISSUE TITLE
Asset distribution within addresses

### ISSUE THREAD

**Issue by shivam2901** [neo-project/neo-cli#145]
My wallet have 3 addresses with corresponding balance of NEP5 asset:
                                                                                          balance
AX2cbiDEkKnNWzYWzYejbN22wU8dDUCmgw          0.80000001
ALLNX3jfryFhVeoy44oRBzGjKYtjHKSTV3                   0.40000000
AQQGpAY7izctrMwEvV2MWSa8GcUFTA6sxP            0.40000000

When I am doing:

{
        "jsonrpc":"2.0",
        "method":"sendmany",
         "params":[[
	{"asset":"0x5bb169f915c916a5e30a3c13a5e0cd228ea26826","value":"0.4","address":"AMiPFWRFwJ1CjwmfBZfUKAqRCXpwvVmgmG"},
	{"asset":"0x5bb169f915c916a5e30a3c13a5e0cd228ea26826","value":"0.4","address":"AX2cbiDEkKnNWzYWzYejbN22wU8dDUCmgw"}
	]],
         "id":1
}

where AMiPFWRFwJ1CjwmfBZfUKAqRCXpwvVmgmG is external wallet address and AX2cbiDEkKnNWzYWzYejbN22wU8dDUCmgw is internal.

Then I am getting **Insufficient funds**
Why?

**Comment by shivam2901** [comment]
Any way get full node balance for NEP5 asset like we have in NEO and GAS.

{
  "jsonrpc": "2.0",
  "method": "getbalance",
  "params": ["025d82f7b00a9ff1cfe709abe3c4741a105d067178e645bc3ebad9bc79af47d4"],
  "id": 1
}

**Comment by vncoelho** [comment]
Nowdays we have a plugin specialized on that.
Please check the docs: https://docs.neo.org/

If you still have any question after it, fell free to reopen.
