### ISSUE TITLE
neo-cli launch fail on macOS

### ISSUE THREAD

**Issue by hello2all** [neo-project/neo-cli#147]
After successful installation of dependences, the Neo-cli returns the following error when launched:
```
src/tcmalloc.cc:332] Attempt to free invalid pointer 0x7f7feaf4ade0 
Abort trap: 6
```

Versions:
MacOS 10.13.4
.Net Core Runtime 2.1.105
LevelDB 1.20_2
SQLite 3.19.3

**Comment by melodyluoxue** [comment]
me too.

**Comment by melodyluoxue** [comment]
i run portable too, meet the same problem:

```
Attempt to free invalid pointer 0x7fef39716ee0 
Abort trap: 6
```

**Comment by lock9** [comment]
I have the same problem here. The project description mentions that it does not run on MacOS. I think this error is related to leveldb, but I'm not sure. I would be very happy with a solution 👍

**Comment by lock9** [comment]
Here is how to fix it:
http://docs.neo.org/en-us/node/cli/publish.html

It works, sometimes the console freezes, but I think it's related to the block synchronisation.

**Comment by hal0x2328** [comment]
Alternate fix without having to switch to rocksdb, just use this command line to start neo-cli: 
```
DYLD_INSERT_LIBRARIES=/usr/local/lib/libtcmalloc.dylib dotnet ./neo-cli.dll
```

**Comment by im-kulikov** [comment]
> Here is how to fix it:
> http://docs.neo.org/en-us/node/cli/publish.html#setting-up-neo-cli-on-macos
> 
> It works, sometimes the console freezes, but I think it's related to the block synchronisation.

Broken link..
