### ISSUE TITLE
Bad entry in block

### ISSUE THREAD

**Issue by kocho** [neo-project/neo-cli#149]
I've been syncing the chain for the past two days and then the client crashed with the following error:

`neo> 
Unhandled Exception: Neo.IO.Data.LevelDB.LevelDBException: Corruption: bad entry in block
   at Neo.IO.Data.LevelDB.NativeHelper.CheckError(IntPtr error)
   at Neo.IO.Data.LevelDB.DB.Write(WriteOptions options, WriteBatch write_batch)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[1]    4392 abort (core dumped)  dotnet neo-cli.dll /rpc`

If i try to restart the client it crashes immediately with:
` *** Error in `dotnet': malloc(): smallbin double linked list corrupted: 0x00007f99402d1580 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f9a311947e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x82651)[0x7f9a3119f651]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f9a311a1184]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x18)[0x7f9a31a94e78]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_mutateEmmPKcm+0x69)[0x7f9a31b26499]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_appendEPKcm+0x63)[0x7f9a31b27833]
/usr/lib/x86_64-linux-gnu/libleveldb.so(_ZNK7leveldb6Status8ToStringB5cxx11Ev+0xad)[0x7f9a1c5157ed]
/usr/lib/x86_64-linux-gnu/libleveldb.so(+0x12fef)[0x7f9a1c4defef]
/usr/lib/x86_64-linux-gnu/libleveldb.so(leveldb_write+0x39)[0x7f9a1c4df3e9]
[0x7f99b930c609]
======= Memory map: ========
00400000-00418000 r-xp 00000000 08:05 549786                             /usr/share/dotnet/dotnet
00618000-00619000 r--p 00018000 08:05 549786                             /usr/share/dotnet/dotnet
00619000-0061a000 rw-p 00019000 08:05 549786                             /usr/share/dotnet/dotnet
0255e000-025b8000 rw-p 00000000 00:00 0                                  [heap]
025b8000-025b9000 ---p 00000000 00:00 0                                  [heap]
...`
following with some memory mapping..

anything i can do or do i have to start syncing from the beginning?

**Comment by jens-j** [comment]
I ran into this issue as well. Not during syncing but during normal operation. My node has been running for over a month but now it keeps crashing with the same error as OP.

**Comment by jsolman** [comment]
What version of LevelDB are you using? What plugins do you have installed?

**Comment by shargon** [comment]
If the problem persist, please reopen the issue
