### ISSUE TITLE
Generating addresses from api

### ISSUE THREAD

**Issue by antouhou** [neo-project/neo-cli#15]
Hi guys! Is there any way to generate address from jsonrpc? Found nothing about that in documentation. I'm trying to integrate your wallet to my service, so I need to generate addresses programmatically through api

**Comment by erikzhang** [comment]
Yes, you can use the `getnewaddress` command in JSON RPC to generate new address.
https://github.com/neo-project/neo-cli/blob/master/neo-cli/Network/RPC/RpcServerWithWallet.cs#L118

**Comment by antouhou** [comment]
Thank you!
