### ISSUE TITLE
Create a multi-party signature contract using neo-cli

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-cli#150]
Hello, 
I would like to perform this step using neo-cli:
http://docs.neo.org/en-us/network/private-chain.html#5-extracting-neo-and-gas

To do that, I need to create this multi-party signature contract, and this does not seem to be implemented in neo-cli. 
Is there any way I can perform the step mentioned using a linux machine?

Thank you

**Comment by lock9** [comment]
I'm going to try to implement this feature in neo-cli, but if anybody needs it, you can use neo-python using command line. http://neo-python.readthedocs.io/en/latest/prompt.html#adding-a-multi-signature-address.

Special thanks to Hal0x2328 that gave me this answer

**Comment by purplesoft-io** [comment]
Hi @lock9 ,
check my pull: https://github.com/neo-project/neo-cli/pull/155
I use this for atomated private blockchain deployment.
I hope can help!

**Comment by lock9** [comment]
I've done the same thing, but differently. Thanks anyway!
