### ISSUE TITLE
Semantic versioning of 2.7.5 to 3.0.0.

### ISSUE THREAD

**Issue by canesin** [neo-project/neo-cli#158]
There was just the release of `2.7.5` but it doesn't seam to be just a bugfix of `2.7.4`, it changes behaviour so should be `3.0.0` if we are to follow https://semver.org/:

Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

Finally we could enforce following the semantic versioning scheme going forward, so that people know what is happening when they upgrade from previous versions.

**Comment by lllwvlvwlll** [comment]
Further, I was not aware this was going to be officially released until excessive testing was done on testnet...there are already mainnet notes popping up because of this release.

**Comment by shargon** [comment]
Should be 3.0 and pre-release

**Comment by vncoelho** [comment]
@canesin, my friend, I think that this has been solved and good standards are being followed.
However, you are a master in it, thus, fell free to keep pushing good ideas and practices. 
I will leave it closed for now.
