### ISSUE TITLE
Feature request: Ability to generate signed transactions offline

### ISSUE THREAD

**Issue by markcross** [neo-project/neo-cli#16]
Someone posted this in the GUI branch but I think it's more relevant here
https://github.com/neo-project/neo-gui/issues/4

The ability to sign a transaction so that NEON wallet team could have their wallet have off-line signing functionality.

The current system of send assets assumes the box is 100% secure.

**Comment by Christopher-Andrade** [comment]
+100!! Doesnt feel secure as MyEthWallet which can sign transactions offline

**Comment by erikzhang** [comment]
So, how do you want to sign the transactions? Through RPC?

**Comment by Christopher-Andrade** [comment]
Hey Erik.

I dont know how MyEtherWallet and BTC have the ability to sign transactions offline. But this to me makes it infinitely more secure than Neo at the moment which doesn't support this feature.

Even on a brand new untouched live bootable DVD OS, how can I be certain that the NEO wallet I have hasn't been infected or swapped. How do I have any guarantee that my private key isnt being broadcast somewhere. I have none. The only failsafe way to do this is to have offline transaction signing ability, where I can take an ecrypted transaction hash, and simply bring it to an online computer and broadcast it.

**Comment by erikzhang** [comment]
@markcross do you have any suggestion?

**Comment by arturaz** [comment]
I second this. You generate the needed info on online PC. You bring that over to airgapped PC with your private keys, sign the transaction, move the signed TX back to online PC and broadcast it.

This is needed.

**Comment by gernotpokorny** [comment]
yep please integrate offline transactions i.e. offline signing of transactions.

**Comment by erikzhang** [comment]
It's implemented in #162.

**Comment by blahd** [comment]
This has been implemented in neo-cli but is not available to the average end-user in the neo-gui as per the original feature request in [neo-project/neo-gui#4](https://github.com/neo-project/neo-gui/issues/4) as far as I'm aware. 

Or am I missing something?
