### ISSUE TITLE
按照中文版本，用 NEO 节点搭建私有链的教程，启用“共识过程”时报错（An item with the same key has alr eady been added）。

### ISSUE THREAD

**Issue by GreatToad** [neo-project/neo-cli#164]
![am 6_4sy 2 75tkjby jy](https://user-images.githubusercontent.com/8457261/40535892-0891d5e0-603d-11e8-85a2-2c232dc8e471.png)

报：Unhandled Exception: System.ArgumentException: An item with the same key has alr
eady been added. Key: System.Threading.Tasks.Task`1[System.Threading.Tasks.VoidT
askResult]错误。

服务器环境是4个虚拟机（vmware），window server 2012 r2 系统。

**Comment by erikzhang** [comment]
Duplicate of #159
