### ISSUE TITLE
关于log（notify）存储的建议

### ISSUE THREAD

**Issue by QingmingZi** [neo-project/neo-cli#165]
现在log存储机制是每个tx存储一个json文件，主网已经超过260w个，很容易造成linux inode撑爆，建议改用轻量数据库存储log（notify）

**Comment by purplesoft-io** [comment]
Now the log storage mechanism is to store a json file for each tx, the main network has exceeded 260w, it is easy to cause linux inode to burst, it is recommended to use a lightweight database to store log (notify)

(from google translate)

**Comment by erikzhang** [comment]
We are thinking of saving the log to leveldb.

**Comment by purplesoft-io** [comment]
Hi @erikzhang !
Can I suggest to look at https://realm.io ?
I use this db (community version opensource written in c) to store big amount of data in a easy way...
Can be a replacement for leveldb?
In my opinion this boost mobile and crossplatform development.
Let me know,
I'm interested to port neo-cli in Xamarin.
Thanks Tiz

**Comment by erikzhang** [comment]
Will begin to work on it after neo-project/neo#258 is merged.
