### ISSUE TITLE
NEO linux下怎么更新节点程序

### ISSUE THREAD

**Issue by zhaoweigao** [neo-project/neo-cli#166]
我在linux下装了一个节点，今天运行报错：

![1527475201 1](https://user-images.githubusercontent.com/37134069/40594737-8778aa5a-6263-11e8-970d-97dbbc3fa290.png)
我猜测可能是需要更新节点程序，但我该怎么操作呢？

**Comment by PeterLinX** [comment]
@zhaoweigao 可能是权限问题，也可能是chain文件夹被占用了

**Comment by shargon** [comment]
This happens when the node is closed unexpectedly, normally with deleting the `LOCK` file is enough

**Comment by shargon** [comment]
If the problem persist, please reopen the issue
