### ISSUE TITLE
MacOS CLI Error:Attempt to free invalid pointer 0x7fb5bce0e640

### ISSUE THREAD

**Issue by liguobao** [neo-project/neo-cli#169]
leveldb is installed.
error message:
Attempt to free invalid pointer 0x7fb5bce0e640

**Comment by erikzhang** [comment]
Duplicate of #147

**Comment by hal0x2328** [comment]
Alternate fix without having to switch to rocksdb, just use this command line to start neo-cli: 
```
DYLD_INSERT_LIBRARIES=/usr/local/lib/libtcmalloc.dylib dotnet ./neo-cli.dll
```
