### ISSUE TITLE
在没有打开钱包的情况下，怎样使用rpc接口构建一笔交易？

### ISSUE THREAD

**Issue by guotie** [neo-project/neo-cli#172]
例如，我想做一笔转账，如何构建交易？

rpc接口只有send Transcation的接口，没有类似于bitcoin的create Transcation的接口。

**Comment by achen27** [comment]
建议你利用类似 https://github.com/CityOfZion/neon-js 的library构建交易，将其序列化之后，用sendrawtransaction的接口广播

**Comment by shargon** [comment]
As @mralbertchen said, you could use neon-js for create the transaction
