### ISSUE TITLE
Nodes was stoped synchronize for a block height after running a while

### ISSUE THREAD

**Issue by gem-travala** [neo-project/neo-cli#173]
Hi,

I'm having trouble with the RPC nodes, it already listed as seed1,2,3,4 travala.com in monitor.cityofzion.io.

It is an Amazon c5.xlarge instance with 4 Core and 8 Gb Ram

After start and running, it sometime stopped synchronize and stuck at a block for a while (may be an hours or several minutes) then continue to sync. 

Did anyone have the same issues? Is that the instance configuration issues (network, CPU, Ram,...) or another reason? 

Thanks and best regards!

**Comment by gem-travala** [comment]
If you take a look on http://seed4.travala.com:10332 right now, it very frequently having the issue.

I just setup by using .Net 2.0 framework for Linux at https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-2.1.101 and clone NEO-CLI repository at Master branch and build then start it up by screen (screen -S neo-cli -dm .....)

Please let me know if anyone have the answer

**Comment by jsolman** [comment]
What version are you running?

**Comment by gem-travala** [comment]
Thank you for looking on

I tried with 2.7.4 version. after on and off a while, it works fine now.

I think there might be a problem while syncing a large amount of blocks at first time. After synced fully, It works normal now

**Comment by shargon** [comment]
If the problem persist, please reopen the issue
