### ISSUE TITLE
Error code MainService.cs:1000 v2.7.5

### ISSUE THREAD

**Issue by djaramillo021** [neo-project/neo-cli#176]
Someone has tried to compile neo and use it in neo-cli because the version is the tag 2.7.5 (neo-cli) refers to e.VMState.

  https://github.com/neo-project/neo-cli/blob/v2.7.5/neo-cli/Shell/MainService.cs (1000 line)

and

ApplicationExecutedEventArgs.cs does not have VMState

https://github.com/neo-project/neo/blob/master/neo/Implementations/Blockchains/LevelDB/ApplicationExecutedEventArgs.cs

**Comment by erikzhang** [comment]
Yes, they are not sync. You need to get the release of neo.dll from nuget.
https://www.nuget.org/packages/Neo/
