### ISSUE TITLE
#BugInTheBlockchain: Incorrect Argument Count in Tx Script Code

### ISSUE THREAD

**Issue by mwherman2000** [neo-project/neo-cli#178]
In block 1,989,466 tx [c0f86a083f1a3962ea375a5264768bbf13dca8a136df4cb71fb98586804fbbd7] (https://neoscan.io/transaction/c0f86a083f1a3962ea375a5264768bbf13dca8a136df4cb71fb98586804fbbd7), there's a bug in either the arg count (`push3`) or in the number of opcodes that precede the arg count.  They don't match up: 3 vs. 2, respectively.

![image](https://user-images.githubusercontent.com/6101736/41508206-ec6aa2dc-720e-11e8-9a93-fa9f9c250db8.png)

**Comment by erikzhang** [comment]
![image](https://user-images.githubusercontent.com/10204923/41510811-8033bf6a-729d-11e8-9898-7307bc26c4d6.png)

This is the way `CHECKMULTISIG` works.

https://github.com/neo-project/neo-vm/blob/e2f3b1aa42073ce27343c9a95bf076ce7d19d787/src/neo-vm/ExecutionEngine.cs#L609-L680

**Comment by mwherman2000** [comment]
@erikzhang I'll take your word for it and close this.  

However, I'm writing a Block/Transaction scanner for NEO-LUX and this is the only transaction in the entire MainNet that has this "problem/configuration".

Issue closed: https://github.com/neo-project/neo-cli/issues/178#issuecomment-397896626

**Comment by mwherman2000** [comment]
@erikzhang I'll take your word for it and close this.  

However, I'm writing a Block/Transaction scanner for NEO-LUX and this is the only transaction in the entire MainNet that has this "problem/configuration".

Issue closed: https://github.com/neo-project/neo-cli/issues/178#issuecomment-397896626
