### ISSUE TITLE
How open wallet on start neo-cli

### ISSUE THREAD

**Issue by atomlab** [neo-project/neo-cli#18]
Hi. How can I auto open wallet in start neo-cli? In [documentation](http://docs.neo.org/en-us/node/api/getbalance.html) written that  `You will need to open the wallet in the Neo-CLI node before executing this command.`  That means that a should start neo-cli and manually open the wallet.
I want start neo-cli via sysetmd or upstart on Linux and open wallet automatically. How can I do that?

I use neo-cli on Ubuntu 14.04/16.04

**Comment by erikzhang** [comment]
There is no way to open wallet automatically. Because wallet is protected by password, and you need to enter it to unlock the wallet.

**Comment by danielfm123** [comment]
you can easy use that NEO & GAS web wallet https://www.myneowallet.io
