### ISSUE TITLE
neo-cli version 2.7.6  appcarsh in win7

### ISSUE THREAD

**Issue by pemila** [neo-project/neo-cli#181]
Everything works fine when I run version 2.7.5(em,if forget [#159](https://github.com/neo-project/neo-cli/issues/159)), this happens when running version 2.7.6  
![](https://i.imgur.com/DglZtmZ.png)
I think this may be a configuration problem, so reconfigure the virtual machine, increase the memory to 8G, but still not resolved. Can someone help me to point out the problem?
↓↓↓this is windows Report↓↓↓
>Version=1
EventType=APPCRASH
EventTime=131739600914119849
ReportType=2
Consent=1
ReportIdentifier=50eb39c8-746b-11e8-91e8-000c29163168
IntegratorReportIdentifier=50eb39c7-746b-11e8-91e8-000c29163168
Response.type=4
Sig[0].Name=应用程序名
Sig[0].Value=neo-cli.exe
Sig[1].Name=应用程序版本
Sig[1].Value=0.0.0.0
Sig[2].Name=应用程序时间戳
Sig[2].Value=597139df
Sig[3].Name=故障模块名称
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=故障模块版本
Sig[4].Value=6.1.7601.17617
Sig[5].Name=故障模块时间戳
Sig[5].Value=4dce2b0e
Sig[6].Name=异常代码
Sig[6].Value=e0434352
Sig[7].Name=异常偏移
Sig[7].Value=000000000000cacd
DynamicSig[1].Name=OS 版本
DynamicSig[1].Value=6.1.7601.2.1.0.256.48
DynamicSig[2].Name=区域设置 ID
DynamicSig[2].Value=2052
DynamicSig[22].Name=其他信息 1
DynamicSig[22].Value=8920
DynamicSig[23].Name=其他信息 2
DynamicSig[23].Value=89201e55df705147dabca6609a8ad0dc
DynamicSig[24].Name=其他信息 3
DynamicSig[24].Value=1964
DynamicSig[25].Name=其他信息 4
DynamicSig[25].Value=1964f580aee00b547551547016031fe1
UI[2]=C:\Users\neo-1\Desktop\NEO\neo-cli\neo-cli.exe
UI[3]=neo-cli.exe 已停止工作
UI[4]=Windows 可以联机检查该问题的解决方案。
UI[5]=联机检查解决方案并关闭该程序
UI[6]=以后联机检查解决方案并关闭程序
UI[7]=关闭程序
LoadedModule[0]=C:\Users\neo-1\Desktop\NEO\neo-cli\neo-cli.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\kernel32.dll
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-runtime-l1-1-0.dll
LoadedModule[5]=C:\Users\neo-1\Desktop\NEO\neo-cli\ucrtbase.DLL
LoadedModule[6]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-core-timezone-l1-1-0.dll
LoadedModule[7]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-core-file-l2-1-0.dll
LoadedModule[8]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-core-localization-l1-2-0.dll
LoadedModule[9]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-core-synch-l1-2-0.dll
LoadedModule[10]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-core-processthreads-l1-1-1.dll
LoadedModule[11]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-core-file-l1-2-0.dll
LoadedModule[12]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-string-l1-1-0.dll
LoadedModule[13]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-stdio-l1-1-0.dll
LoadedModule[14]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-heap-l1-1-0.dll
LoadedModule[15]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-convert-l1-1-0.dll
LoadedModule[16]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-locale-l1-1-0.dll
LoadedModule[17]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-math-l1-1-0.dll
LoadedModule[18]=C:\Users\neo-1\Desktop\NEO\neo-cli\hostfxr.dll
LoadedModule[19]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-filesystem-l1-1-0.dll
LoadedModule[20]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-multibyte-l1-1-0.dll
LoadedModule[21]=C:\Users\neo-1\Desktop\NEO\neo-cli\hostpolicy.dll
LoadedModule[22]=C:\Users\neo-1\Desktop\NEO\neo-cli\coreclr.dll
LoadedModule[23]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[24]=C:\Windows\system32\msvcrt.dll
LoadedModule[25]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[26]=C:\Windows\system32\RPCRT4.dll
LoadedModule[27]=C:\Windows\system32\ole32.dll
LoadedModule[28]=C:\Windows\system32\GDI32.dll
LoadedModule[29]=C:\Windows\system32\USER32.dll
LoadedModule[30]=C:\Windows\system32\LPK.dll
LoadedModule[31]=C:\Windows\system32\USP10.dll
LoadedModule[32]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[33]=C:\Windows\system32\VERSION.dll
LoadedModule[34]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[35]=C:\Windows\system32\bcrypt.dll
LoadedModule[36]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-utility-l1-1-0.dll
LoadedModule[37]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-time-l1-1-0.dll
LoadedModule[38]=C:\Windows\system32\IMM32.DLL
LoadedModule[39]=C:\Windows\system32\MSCTF.dll
LoadedModule[40]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Private.CoreLib.dll
LoadedModule[41]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[42]=C:\Users\neo-1\Desktop\NEO\neo-cli\neo-cli.dll
LoadedModule[43]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Runtime.dll
LoadedModule[44]=C:\Users\neo-1\Desktop\NEO\neo-cli\clrjit.dll
LoadedModule[45]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Runtime.Extensions.dll
LoadedModule[46]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Console.dll
LoadedModule[47]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Threading.dll
LoadedModule[48]=C:\Users\neo-1\Desktop\NEO\neo-cli\Neo.dll
LoadedModule[49]=C:\Users\neo-1\Desktop\NEO\neo-cli\netstandard.dll
LoadedModule[50]=C:\Users\neo-1\Desktop\NEO\neo-cli\Neo.VM.dll
LoadedModule[51]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Collections.dll
LoadedModule[52]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.IO.FileSystem.dll
LoadedModule[53]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.Extensions.Configuration.dll
LoadedModule[54]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.Extensions.Configuration.Abstractions.dll
LoadedModule[55]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.Extensions.Configuration.Json.dll
LoadedModule[56]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.Extensions.FileProviders.Abstractions.dll
LoadedModule[57]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.Extensions.Configuration.FileExtensions.dll
LoadedModule[58]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.Extensions.FileProviders.Physical.dll
LoadedModule[59]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.Extensions.Primitives.dll
LoadedModule[60]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.IO.FileSystem.Watcher.dll
LoadedModule[61]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.ComponentModel.Primitives.dll
LoadedModule[62]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Collections.Concurrent.dll
LoadedModule[63]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Threading.Tasks.dll
LoadedModule[64]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.Extensions.FileSystemGlobbing.dll
LoadedModule[65]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Linq.dll
LoadedModule[66]=C:\Users\neo-1\Desktop\NEO\neo-cli\Newtonsoft.Json.dll
LoadedModule[67]=C:\Windows\system32\CRYPTBASE.dll
LoadedModule[68]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Dynamic.Runtime.dll
LoadedModule[69]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Linq.Expressions.dll
LoadedModule[70]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.ObjectModel.dll
LoadedModule[71]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.IO.dll
LoadedModule[72]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Globalization.dll
LoadedModule[73]=C:\Windows\system32\CRYPTSP.dll
LoadedModule[74]=C:\Windows\system32\rsaenh.dll
LoadedModule[75]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Runtime.Numerics.dll
LoadedModule[76]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Private.Uri.dll
LoadedModule[77]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Threading.Thread.dll
LoadedModule[78]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Security.Cryptography.Algorithms.dll
LoadedModule[79]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Security.Cryptography.Primitives.dll
LoadedModule[80]=C:\Windows\system32\bcryptprimitives.dll
LoadedModule[81]=C:\Users\neo-1\Desktop\NEO\neo-cli\libleveldb.DLL
LoadedModule[82]=C:\Windows\system32\MSVCP140.dll
LoadedModule[83]=C:\Windows\system32\VCRUNTIME140.dll
LoadedModule[84]=C:\Users\neo-1\Desktop\NEO\neo-cli\api-ms-win-crt-environment-l1-1-0.dll
LoadedModule[85]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Runtime.InteropServices.dll
LoadedModule[86]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Data.Common.dll
LoadedModule[87]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Net.Primitives.dll
LoadedModule[88]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Net.NetworkInformation.dll
LoadedModule[89]=C:\Windows\system32\iphlpapi.dll
LoadedModule[90]=C:\Windows\system32\NSI.dll
LoadedModule[91]=C:\Windows\system32\WINNSI.DLL
LoadedModule[92]=C:\Windows\system32\DNSAPI.dll
LoadedModule[93]=C:\Windows\system32\WS2_32.dll
LoadedModule[94]=C:\Windows\system32\dhcpcsvc6.DLL
LoadedModule[95]=C:\Windows\system32\dhcpcsvc.DLL
LoadedModule[96]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.IO.Compression.dll
LoadedModule[97]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.DiaSymReader.Native.amd64.dll
LoadedModule[98]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.AspNetCore.Http.Abstractions.dll
LoadedModule[99]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.AspNetCore.Hosting.dll
LoadedModule[100]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.AspNetCore.Hosting.Abstractions.dll
LoadedModule[101]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Diagnostics.StackTrace.dll
LoadedModule[102]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.Extensions.DependencyInjection.Abstractions.dll
LoadedModule[103]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Reflection.Metadata.dll
LoadedModule[104]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.AspNetCore.Server.Kestrel.dll
LoadedModule[105]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Net.Sockets.dll
LoadedModule[106]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.Win32.Primitives.dll
LoadedModule[107]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Xml.ReaderWriter.dll
LoadedModule[108]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Private.Xml.dll
LoadedModule[109]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Collections.Immutable.dll
LoadedModule[110]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Diagnostics.Tracing.dll
LoadedModule[111]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Threading.Tasks.Parallel.dll
LoadedModule[112]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Threading.Overlapped.dll
LoadedModule[113]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Linq.Parallel.dll
LoadedModule[114]=C:\Users\neo-1\Desktop\NEO\neo-cli\System.Net.NameResolution.dll
LoadedModule[115]=C:\Windows\system32\NLAapi.dll
LoadedModule[116]=C:\Windows\system32\napinsp.dll
LoadedModule[117]=C:\Windows\system32\pnrpnsp.dll
LoadedModule[118]=C:\Windows\System32\mswsock.dll
LoadedModule[119]=C:\Windows\System32\winrnr.dll
LoadedModule[120]=C:\Windows\System32\wshtcpip.dll
LoadedModule[121]=C:\Windows\System32\wship6.dll
LoadedModule[122]=C:\Users\neo-1\Desktop\NEO\neo-cli\Microsoft.Extensions.Configuration.EnvironmentVariables.dll
FriendlyEventName=已停止工作
ConsentKey=APPCRASH
AppName=neo-cli.exe
AppPath=C:\Users\neo-1\Desktop\NEO\neo-cli\neo-cli.exe

**Comment by erikzhang** [comment]
This seems to be due to insufficient disk space.

**Comment by pemila** [comment]
I adjusted the virtual machine's memory and virtual memory, but it was useless. I have decided not to build on win7.
