### ISSUE TITLE
why does my node can not synchronize blocks

### ISSUE THREAD

**Issue by yousq** [neo-project/neo-cli#183]
Hi, we are a cryptocurrency exchange, and we are going to support NEO.
But I get a deadly problem: my node can not synchronize blocks

This question had been raised many times,  till now, 
I still can not find an effective way to solve this problem.

Here is my situation:
my node can only connect to one peer, which is the "seed2.neo.org:10333" in China.
neo> show node
::ffff:101.132.67.230 port:10333 listen:10333 height:2439126 [1/1]

Note that the height of this peer is the highest, 
But my node can not synchronize blocks from it.
neo> show state
Height: 2430484/2430484/2430484, Nodes: 1

question 1.  why my node can not connect to more nodes, and whitout any errors?(the network bandwidth of my server is big enough, and my server is on AWS) ?

question 2. although my node can noly connect to one peer, but that peer has the highest block height, why dose my node can not synchronize blocks from it ?

**Comment by PeterLinX** [comment]
@yousq 
1. Please check these docs below first:
http://docs.neo.org/en-us/node/cli/seedlist.html
http://docs.neo.org/en-us/network/syncblocks.html
These two docs may solve your problems.
2. It'll be great if you can join discord. My team can help you on this.
https://discord.gg/svmvgCu
My id: @PeterLinX#5293

**Comment by yousq** [comment]
@PeterLinX 
Thank for your explanation.

I know http://monitor.cityofzion.io/ this site is keeping on collecting active nodes, now that you recommend to use these nodes as seeds, I can treat them as trusty seeds and have a try.

Secondly, I always use the offline block file(chain.acc.zip), 
but unfortunately ,  every time when it came to the end of the chain.acc.zip, it got stucked, 
and could not go on to get newer blocks from the mainnet.

Miracle happend today, my node  connected to 10 peers, and was synchronized with the mainnet.
Maybe it was deeply moved by my hardwork.

And I'll try to use discord and do more test & research later.

Thanks!
