### ISSUE TITLE
Is there a breaking change?

### ISSUE THREAD

**Issue by ediopia** [neo-project/neo-cli#184]
It returns different values between 2.7.4 and 2.7.6. both results are in the same block height.
<img width="1403" alt="screen shot 2018-06-28 at 12 00 52 am" src="https://user-images.githubusercontent.com/6670368/42018413-e2a89dde-7a66-11e8-8b6f-82489569a226.png">
<img width="1404" alt="screen shot 2018-06-28 at 12 01 05 am" src="https://user-images.githubusercontent.com/6670368/42018418-e7952a88-7a66-11e8-99df-1b05d10eb30b.png">

Also invocation between 2 version acts differently.
<img width="820" alt="screen shot 2018-06-27 at 11 21 41 pm" src="https://user-images.githubusercontent.com/6670368/42018520-33857a2e-7a67-11e8-81e7-1c647036b048.png">
<img width="826" alt="screen shot 2018-06-27 at 11 22 43 pm" src="https://user-images.githubusercontent.com/6670368/42018521-339e1886-7a67-11e8-8987-be4e7aadb208.png">

**Comment by shargon** [comment]
Could you copy the request in plane text please?

**Comment by ediopia** [comment]
http://seed2.neo.org:20332?jsonrpc=2.0&method=invokefunction&params=["aaeb8d8f50a25cd608256bf4e41f72f3ecece717","balanceOf",[
      {
        "type": "Hash160",
        "value": "3f0ca8728dd6bbb1d066879a2ad21e265333c723"
      }
    ]]&id=5

http://seed4.neo.org:20332?jsonrpc=2.0&method=invokefunction&params=["aaeb8d8f50a25cd608256bf4e41f72f3ecece717","balanceOf",[
      {
        "type": "Hash160",
        "value": "3f0ca8728dd6bbb1d066879a2ad21e265333c723"
      }
    ]]&id=5

**Comment by ediopia** [comment]
Another custom call

http://seed2.neo.org:20332?jsonrpc=2.0&method=invokefunction&params=["aaeb8d8f50a25cd608256bf4e41f72f3ecece717","get_all_drawing_results",[
      {
        "type": "Hash160",
        "value": "3f0ca8728dd6bbb1d066879a2ad21e265333c723"
      }
    ]]&id=5

http://seed4.neo.org:20332?jsonrpc=2.0&method=invokefunction&params=["aaeb8d8f50a25cd608256bf4e41f72f3ecece717","get_all_drawing_results",[
      {
        "type": "Hash160",
        "value": "3f0ca8728dd6bbb1d066879a2ad21e265333c723"
      }
    ]]&id=5

**Comment by ediopia** [comment]
Any updates on this issue? I don't understand how it is possible to get different values from blockchain..

**Comment by PeterLinX** [comment]
@ediopia We'll test it and find out why.

**Comment by superboyiii** [comment]
@ediopia Could you tell me what's your return param in the invokefunction of your contact? I've tested it on seed2, seed4 and localhost. It seems that seed2's version is 2.7.4, seed4's version is 2.6.0 and my localhost's version is 2.7.6. The result is that 2.7.4 and 2.7.6 have got the same response byteArray, but seed4's response is diiferent. I think it's related to the old version's different processing mechanism.
![image](https://user-images.githubusercontent.com/38493437/42202460-1167fdb6-7ece-11e8-9806-3364ba0d13b7.png)

**Comment by ediopia** [comment]
It works as I expect in 2.7.4 which is http://seed2.neo.org:20332.
You said 2.7.6 returns as 2.7.4 but when I opened this issue, 2.7.6 returned different values as well.

Now every testnet nodes on http://monitor.cityofzion.io/ are 2.6.0 but when I opened this issue those were 2.7.6

returns on 2.7.4
<img width="1119" alt="screen shot 2018-07-03 at 12 06 35 am" src="https://user-images.githubusercontent.com/6670368/42203902-086dbe90-7e55-11e8-9d1a-506e4b964762.png">

returns on 2.6.0
<img width="1114" alt="screen shot 2018-07-03 at 12 05 40 am" src="https://user-images.githubusercontent.com/6670368/42203920-145fdf3a-7e55-11e8-8be0-ba3b03d663ef.png">

**Comment by superboyiii** [comment]
2.7.6
![image](https://user-images.githubusercontent.com/38493437/42204328-f1f57782-7ed3-11e8-9aa5-951c18e05411.png)
2.7.4
![image](https://user-images.githubusercontent.com/38493437/42204426-401bdf6e-7ed4-11e8-8337-571d9fea2af6.png)
2.6.0
![image](https://user-images.githubusercontent.com/38493437/42204456-566e17a0-7ed4-11e8-9010-2109db9b3068.png)
@ediopia

**Comment by superboyiii** [comment]
As you see, 2.7.6 and 2.7.4 are the same unless 2.7.6's new param "tx".

**Comment by superboyiii** [comment]
If necessary, you can create a privatenet with docker. 
More details here-> https://github.com/HandsomeJeff/neo-python-workshop
@ediopia

**Comment by ediopia** [comment]
I just moved my project to Testnet from Privatenet. I have an auditing event with our users before mainnet deployment.

**Comment by ediopia** [comment]
I want to know about the reason what makes different results.

I met similar issues before when I tried to store some kinds of blockchain values in SC. 

Whenever I stored transaction id and blockheight as a key or as a value, it successfully stored in storage however rpc could not find the values and broke storage like this issue.

It was on 2.7.4

So I had to use alternative ways instead of storing those data.

**Comment by superboyiii** [comment]
I think It's still related to your sync. Sometimes you just open rpc and the block hasn't been synchronized. At this time, the response state can be fault. But the response above you have listed is about the diifference between 2.7.4 and 2.6.0. I think 2.6.0's version is too old so that it can't support some api normally. But as a consensus node, it works well. So if your contract has been tested well in your private net, that's OK. Mainnet now is 2.7.4, the same with your local version. @ediopia

**Comment by ediopia** [comment]
I see no 2.6.0 versions in the mainnet list so it should be okay. I just can use seed2 for the testnet app.
I don't think it was related to sync because I tried many tests to figure it out. When you have a chance, try to store transaction id as a key or value in storage. Thanks for your help. Finally I can move on. @superboyiii
