### ISSUE TITLE
How can we store multiple values like object in Neo Blockchain, need to use Neo blockchain as a database for my project

### ISSUE THREAD

**Issue by SabarishT** [neo-project/neo-cli#190]
Unable to return object with multiple values, state shows fault break
In the below code for single key am setting multiple values. 
       

      public class TestClass extends SmartContract 
                 public static Object Main(String[] args)
                  {
		        Storage.put(Storage.currentContext(), "Greeting to the Neo BLockchain", "Employee1");
		        Storage.put(Storage.currentContext(), "Greeting to the Neo BLockchain", "Employee2");
		        Storage.put(Storage.currentContext(), "Greeting to the Neo BLockchain", "Employee3");
		        Storage.put(Storage.currentContext(), "Greeting to the Neo BLockchain", "Employee4");
		        
		        return Storage.get(Storage.currentContext(),"Greeting to the Neo BLockchain");
		  }}`

**After deploying contract invoke function occurs when trying to use INVOKE FUNCTION in RPC API**
`{
                      "jsonrpc": "2.0",
                       "method": "invokefunction",
                       "params": [
                       "0x8edb0cc044e02ead5597b8043f4ff1f4d403d11d",
                        "Main",
     [
      {
        "type": "ByteArray",
        "value": ""
      }
    ]
  ],
  "id": 1
}`
**After POST request am getting response**
`{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "script": "0051c1044d61696e671dd103d4f4f14f3f04b89755ad2ee044c00cdb8e",
        "state": "FAULT, BREAK",
        "gas_consumed": "1.018",
        "stack": [
            {
                "type": "Array",
                "value": [
                    {
                        "type": "ByteArray",
                        "value": ""
                    }
                ]
            },
            {
                "type": "ByteArray",
                "value": "456d706c6f79656531"
            },
            {
                "type": "ByteArray",
                "value": "4772656574696e6720746f20746865204e656f20424c6f636b636861696e"
            }
        ],
        "tx": "d1011d0051c1044d61696e671dd103d4f4f14f3f04b89755ad2ee044c00cdb8e000000000000000000000000"
    }
}`

**Comment by shargon** [comment]
you are using the same key, so you are replace the content of this key

**Comment by SabarishT** [comment]
Yeah Ok I am trying to replace the value I have setted But it is not replacing. Instead of that When I am trying return the same key.
I am getting first value "Employee1" with "state": "FAULT, BREAK". So it is not replacing. 
But I need to Store multiple values in Neo Blockchain.
**Can you please help in this query**

**Comment by penlite** [comment]
```
  public class TestClass extends SmartContract 
             public static Object Main(String[] args)
              {
	        Storage.put(Storage.currentContext(), "Greeting to the Neo BLockchain_1", "Employee1");
	        Storage.put(Storage.currentContext(), "Greeting to the Neo BLockchain_2", "Employee2");
	        Storage.put(Storage.currentContext(), "Greeting to the Neo BLockchain_3", "Employee3");
	        Storage.put(Storage.currentContext(), "Greeting to the Neo BLockchain_4", "Employee4");
	        
	        return Storage.get(Storage.currentContext(),"Greeting to the Neo BLockchain_1");
	  }}
```

**Comment by vncoelho** [comment]
HI @SabarishT, please check the docs: https://docs.neo.org/
They have been constantly updated since your issue was openned.

If you still have any question after it fell free to ping on Discord channel or open an issue here.
