### ISSUE TITLE
Invoke Function behaving inconsistently across nodes with same version

### ISSUE THREAD

**Issue by wy** [neo-project/neo-cli#191]
The call:
```
{
        "jsonrpc": "2.0",
        "method": "invokefunction",
        "params": [
            "fc732edee1efdf968c23c20a9628eaa5a6ccb934",
            "balanceOf",
            [
                {
                    "type":"Hash160",
                    "value":"0e52fbad9df755c73a3699b12438c0b3b8eabe84"
                }
            ]
        ],
        "id": 3
}
```

Should return:
```
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "1484beeab8b3c03824b199363ac755f79dadfb520e51c10962616c616e63654f666734b9cca6a5ea28960ac2238c96dfefe1de2e73fc",
        "state": "HALT, BREAK",
        "gas_consumed": "0.358",
        "stack": [
            {
                "type": "ByteArray",
                "value": "1027"
            }
        ]
    }
}
```

However, results as follows:
https://seed1.spotcoin.com:10332 (/NEO:2.7.6/)
```
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "1484beeab8b3c03824b199363ac755f79dadfb520e51c10962616c616e63654f666734b9cca6a5ea28960ac2238c96dfefe1de2e73fc",
        "state": "HALT, BREAK",
        "gas_consumed": "0.358",
        "stack": [
            {
                "type": "ByteArray",
                "value": ""
            }
        ]
    }
}
```
http://seed1.redpulse.com:10332 (/NEO:2.7.6/)
```
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "1484beeab8b3c03824b199363ac755f79dadfb520e51c10962616c616e63654f666734b9cca6a5ea28960ac2238c96dfefe1de2e73fc",
        "state": "HALT, BREAK",
        "gas_consumed": "0.358",
        "stack": [
            {
                "type": "ByteArray",
                "value": ""
            }
        ]
    }
}
```
http://api.otcgo.cn:10332  (/NEO:2.7.6/)
```
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "1484beeab8b3c03824b199363ac755f79dadfb520e51c10962616c616e63654f666734b9cca6a5ea28960ac2238c96dfefe1de2e73fc",
        "state": "HALT, BREAK",
        "gas_consumed": "0.358",
        "stack": [
            {
                "type": "ByteArray",
                "value": "1027"
            }
        ]
    }
}
```

**Comment by superboyiii** [comment]
It seems some of the seed nodes don't work well on 10331/10332. You can have a look at my test report here and choose the good nodes. @wy

**Comment by superboyiii** [comment]
[
[seed nodes test.xlsx](https://github.com/neo-project/neo-cli/files/2165305/seed.nodes.test.xlsx)
]

**Comment by wy** [comment]
@superboyiii  could you run the same test for this contract hash:
ecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9
```
{
        "jsonrpc": "2.0",
        "method": "invokefunction",
        "params": [
            "ecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9",
            "balanceOf",
            [
                {
                    "type":"Hash160",
                    "value":"0e52fbad9df755c73a3699b12438c0b3b8eabe84"
                }
            ]
        ],
        "id": 3
}
```

**Comment by erikzhang** [comment]
I think some nodes may need to resynchronize the blocks.

**Comment by superboyiii** [comment]
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "1484beeab8b3c03824b199363ac755f79dadfb520e51c10962616c616e63654f6667f91d6b7085db7c5aaf09f19eeec1ca3c0db2c6ec",
        "state": "HALT, BREAK",
        "gas_consumed": "0.338",
        "stack": [
            {
                "type": "ByteArray",
                "value": "00409452a303"
            }
        ]
    }
}

**Comment by superboyiii** [comment]
@wy My result is above.

**Comment by superboyiii** [comment]
This contract hash seems get the same response value from all of these nodes which I have tested before.

**Comment by erikzhang** [comment]
My result is below:
```json
{
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "script": "1484beeab8b3c03824b199363ac755f79dadfb520e51c10962616c616e63654f6667f91d6b7085db7c5aaf09f19eeec1ca3c0db2c6ec",
    "state": "HALT, BREAK",
    "gas_consumed": "0.338",
    "stack": [
      {
        "type": "ByteArray",
        "value": "00409452a303"
      }
    ]
  }
}
```
The same as @superboyiii

**Comment by superboyiii** [comment]
[seed nodes test.xlsx](https://github.com/neo-project/neo-cli/files/2165689/seed.nodes.test.xlsx)

**Comment by f27d** [comment]
So the issue was raised with the contract hash which is for NNC (deployed 28th June) and the 2nd one was for Red Pulse (8th October) so maybe it's because of block syncing (2.7.5?) around that time?

**Comment by erikzhang** [comment]
Re-sync blocks in 2.7.6 or [3.0.0-preview*](https://github.com/neo-project/neo-cli/pull/188) may solve this issue.

**Comment by RavenXce** [comment]
We found some txn executions that fault on a re-sync of 2.7.4 but not on 2.7.6. Does anyone know the root reason?

We found some example transactions, for e.g.: `cd3ded801a4cdc9067d0fe49c701618e585ff9c86c9389a0f39f6c421c66f599`:
New versions: https://neotracker.io/tx/cd3ded801a4cdc9067d0fe49c701618e585ff9c86c9389a0f39f6c421c66f599

Old versions:
<img width="730" alt="screen shot 2018-10-04 at 10 05 28 am" src="https://user-images.githubusercontent.com/1667694/46449198-424eb180-c7bd-11e8-83a7-49c7d20c2e6d.png">

**Comment by vncoelho** [comment]
I think that all inconsistencies have been hunted in the latest versions.
