### ISSUE TITLE
Unable to get response from invoke function in RPC-API's

### ISSUE THREAD

**Issue by mannekarthik1** [neo-project/neo-cli#192]
For the bleow code i am setting the value by calling setMethod using Storage.put.
Hear i am using RPC-API's testnet 
`public class Test extends SmartContract {
	
	public static Object Main(String name, Object[] args){
		if(name.equals("setMethod")) {
			 return setMethod(args[0]);
		}
		if(name.equals("getMethod")) {
			return getMethod();
		}
			return false;		
	}
	
	public static Object getMethod() {
		 return Storage.get(Storage.currentContext(), "aaa");
	}
	public static Object setMethod(Object empName) {
		byte[] b= (byte[]) empName;
		Storage.put(Storage.currentContext(), "aaa" ,b);
		return true;
			
	}

}`

> **POST Request** : 
{
  "jsonrpc": "2.0",
  "method": "invokefunction",
  "params": [
    "0x51c501c83af4ae5cf6ad28152dfd02cdd4ac1035",
    "Main",
    [
      {
        "type": "String",
        "value": "setMethod"
      },
      {
      	"type": "Array",
        "value": [{
        	"type":"String",
        	"value": "zzz"
        }]
      }
    ]
  ],
  "id": 1
}

>**Response** : 
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "script": "037a7a7a51c1097365744d6574686f6452c1044d61696e673510acd4cd02fd2d1528adf65caef43ac801c551",
        "state": "HALT, BREAK",
        "gas_consumed": "0.033",
        "stack": [
            {
                "type": "ByteArray",
                "value": ""
            }
        ]
    }
}

In response i am getting "state": "HALT, BREAK", but it is not returning the value. i mention above java code. I am getting empty response (i tested both set and get methods getting same response).

**Comment by penlite** [comment]
What parameters did you use to deploy the smart contract?

**Comment by vncoelho** [comment]
Did you find out how to manage this, @penlite.
Please fell free to ping us here or check the docs: https://docs.neo.org/

If this is already solved, please close this issue.

**Comment by shargon** [comment]
Closed because wasn't answered
