### ISSUE TITLE
我再windows下运行出现内存不足，无法处理此命令

### ISSUE THREAD

**Issue by fanchi1** [neo-project/neo-cli#194]

**Comment by Tommo-L** [comment]
亲，目前这块可能是兼容性问题， win7下按照下面方法，重新编译Neo-CLI 解决问题。

![image](https://user-images.githubusercontent.com/43396869/61346049-f96a7400-a889-11e9-9e1c-f4ed3dbdcdd2.png)

注释掉红色部分，重新编译就可以。

最后，亲，若方案能解决了本问题，麻烦可以关闭该issue了吗？

**Comment by lock9** [comment]
Hello,
Since there was no answer from @fanchi1, I'm closing this issue.
@fanchi1  if the suggestion from @Tommo-L  doesn't solve your problem, please create a new issue.
Thanks
