### ISSUE TITLE
Assets not showing in node

### ISSUE THREAD

**Issue by khelle** [neo-project/neo-cli#195]
Hi, 
I am using NEO-CLI v2.7.3 and have problems with it not detecting my assets. My node is synchronized up to date with newest blockchain height. The problem is as follows.

I have some address which posses RPX and other tokens. Neotracker explorer confirms me this showing that this address in fact, has them. If I use "list address" CLI command to ensure my neo node has this address, it is present and being returned as "standard" one. If I then try to ask my NEO via RPC for state of NEO/GAS assets in wallet by calling `getbalance` with appropriate asset ID, it returns me 0. If I use it to ask for RPX tokens (assetID=ecc6b20d3ccac1ee9ef109af5a7cdb85706b1df9) or any other tokens, it returns me `{"jsonrpc":"2.0","id":1,"error":{"code":-2146233033,"message":"One of the identified items was in an invalid format."}}`. What's more, when I log into NEO CLI console, and type `list asset` it returns me nothing. What do I do wrong? I am fully synchronized.

**Comment by erikzhang** [comment]
Did you try the latest version?

**Comment by vncoelho** [comment]
Surely no problems exist latest releases.
