### ISSUE TITLE
neo-cli is not showing any logs in v2.7.6.1

### ISSUE THREAD

**Issue by InfinitePest** [neo-project/neo-cli#197]
I am running neo-cli using the docker image: `microsoft/dotnet:2.0-sdk`
my config.json is:
```
{
  "ApplicationConfiguration": {
    "Paths": {
      "Chain": "/data/chain",
      "ApplicationLogs": "/data/logs"
    },
    "P2P": {
      "Port": 10333,
      "WsPort": 10334
    },
    "RPC": {
      "Port": 10332,
      "SslCert": "",
      "SslCertPassword": ""
    },
    "UnlockWallet": {
      "Path": "",
      "Password": "",
      "StartConsensus": false,
      "IsActive": false
    }
  }
}
```
where the dir is owned by the user. 
I am using the command:
`dotnet neo-cli.dll --rpc --log`

and there are no logs in the ApplicationLogs directory.
is there a setting for the log level, or a way to make the process log to stdout?

**Comment by superboyiii** [comment]
Are you in a private net created by docker? @InfinitePest

**Comment by shargon** [comment]
Logs was moved to a plugin
https://github.com/neo-project/neo-plugins/blob/eabfd782242bda946311b8016ce4c8979fce05e2/SimplePolicy/SimplePolicyPlugin.cs#L83
