### ISSUE TITLE
Problems occurred when using JSON RPC API's

### ISSUE THREAD

**Issue by SabarishT** [neo-project/neo-cli#199]
We have deployed a python contract in the Neo Blockchain

Contract Code in python :
`
   def Main(operation, a, b):

    if operation == 'add':
        return a + b

    elif operation == 'sub':
        return a - b

    elif operation == 'mul':
        return a * b

    elif operation == 'div':
        return a / b

    else:
        return -1`
		
Initially we have tested in the neo gui-2.6.6. We got correct output for input {add, 3, 4}

![neo capture](https://user-images.githubusercontent.com/29983995/42696902-3c62e40c-86d7-11e8-81fe-0b841d89c951.PNG)

Then we have tested in neo Python cmd in ubuntu-18.04 LTS

![sample22](https://user-images.githubusercontent.com/29983995/42697279-4b15f4e8-86d8-11e8-8b2a-f8c37520a418.PNG)

In the above two cases functionalities are working fine.

As the same way we have tested through postman, with the JSON RPC API's as given below
http://seed2.neo.org:20332, http://seed4.neo.org:20332, http://localhost:20332

**Request :**

> {
  "jsonrpc": "2.0",
  "method": "invokefunction",
  "params": [
    "0x86d58778c8d29e03182f38369f0d97782d303cc0",
    "Main",
    [
      {
        "type": "String",
        "value": "add"
      },
      {
        "type": "Integer",
        "value": 3
      },
      {
        "type": "Integer",
        "value": 4
      }
    ]
  ],
  "id": 1
}

**Response:**

> {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "script": "54530361646453c1044d61696e67c03c302d78970d9f36382f18039ed2c87887d586",
        "state": "FAULT, BREAK",
        "gas_consumed": "0.021",
        "stack": [
            {
                "type": "Array",
                "value": [
                    {
                        "type": "ByteArray",
                        "value": "4d61696e"
                    },
                    {
                        "type": "Array",
                        "value": [
                            {
                                "type": "ByteArray",
                                "value": "616464"
                            },
                            {
                                "type": "Integer",
                                "value": "3"
                            },
                            {
                                "type": "Integer",
                                "value": "4"
                            }
                        ]
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    }
                ]
            },
            {
                "type": "Integer",
                "value": "2"
            }
        ]
    }
}

Here we got the status ==> "state": "FAULT, BREAK",

Here we are not getting exact response as per neo gui-2.6.6.

Not only for this contract i am facing same type of response and empty responses for so many contracts using **PYTHON** and **JAVA** 

Kindly help us to move further

Thanks in advance 

Environment

- OS: Ubuntu-18.04 LTS And Windows -10
- neo-python version: 3.6+
- Python version: 3.6

**Comment by penlite** [comment]
Can you send me the transaction reference for when you deployed the smart contract onto testnet please?

**Comment by shargon** [comment]
> Can you send me the transaction reference for when you deployed the smart contract onto testnet please?

Closed because wasn't provide the information in more than 6 months
