### ISSUE TITLE
Rpc API - Get the amount actually received

### ISSUE THREAD

**Issue by Pwnmanship** [neo-project/neo-cli#20]
When you have address A which has 2 NEO on it and you send 1 to address B then NEO doesn't create a different change address but just sends 1 to address B and 1 to address A.
Now when we want to know how much we have actually received on address A we can't also add up those change transactions.

So we need to be able to check the address the transaction came from.
Is there any way to do this in the rpc api?

**Comment by erikzhang** [comment]
No way, I think..
