### ISSUE TITLE
rpc Access denied

### ISSUE THREAD

**Issue by guanhui07** [neo-project/neo-cli#201]
[root@master-yzjbz2154544231-1528962361316 ~]#  curl 127.0.0.1:10332 -d '{
>   "jsonrpc": "2.0",
>   "method": "getbalance",
>   "params": ["025d82f7b00a9ff1cfe709abe3c4741a105d067178e645bc3ebad9bc79af47d4"],
>   "id": 1
> }'
{"jsonrpc":"2.0","id":1,"error":{"code":-400,"message":"Access denied."}}[root@master-yzjbz2154544231-1528962361316 ~]#   how i can access it

**Comment by edmhs** [comment]
Can you explain your setup? which service are you running?

**Comment by guanhui07** [comment]
yet  my  command for setup 
`[root@master-yzjbz2154544231-1528962361316 neo-cli]# dotnet neo-cli.dll  --rpc

NEO-CLI Version: 2.6.0.0

neo> 
neo> `


and open a new client ssh to curl  

or other way  nohup dotnet neo-cli.dll  --rpc & 

my os  is centos7

and   NEO-CLI Version: 2.6.0.0  it return Access denied  but i see it's a bug already fix 
[https://github.com/neo-project/neo-cli/issues/71](https://github.com/neo-project/neo-cli/issues/71) 
the newer neo-cli client 2.7 i try  also return Access denied

**Comment by LoranceChen** [comment]
http://docs.neo.org/zh-cn/node/cli/2.7.6/api/getbalance.html

**Comment by penlite** [comment]
@erikzhang we should close this one. Wallet needs to be opened on client to be able to use this RPC call.

**Comment by kentarohorie** [comment]
Open wallet example

[ref](http://docs.neo.org/en-us/node/cli/2.9.0/api.html)

edit neo-cli/config.json

```

"UnlockWallet": {
      "Path": "/home/user/wallets/wallet.json",
      "Password": "password",
      "StartConsensus": false,
      "IsActive": true
    }

```
