### ISSUE TITLE
dotnet neo-cli.dll --rpc --log exit because of exception: System.IO.IOException: No space left on device

### ISSUE THREAD

**Issue by LoranceChen** [neo-project/neo-cli#208]
Hi, I had running neo-cli for a long time(12 days ago). But it exit with a exception today:
```
Unhandled Exception: System.IO.IOException: No space left on device
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Neo.Shell.MainService.LevelDBBlockchain_ApplicationExecuted(Object sender, ApplicationExecutedEventArgs e)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Aborted (core dumped)
```
It occurred every times when start neo-cli by `dotnet neo-cli.dll --rpc --log` after it first throw the exception. neo-cli will crash after 5 seconds when started without any operation.  
My environment:
- Ubuntu 16.04  
- dotnet core 2.1.2
- Neo Main Net
- df -h
```
Filesystem      Size  Used Avail Use% Mounted on
udev             14G     0   14G   0% /dev
tmpfs           2.8G  8.7M  2.8G   1% /run
/dev/sda1        30G  2.0G   28G   7% /
tmpfs            14G   12K   14G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            14G     0   14G   0% /sys/fs/cgroup
/dev/sdb1        55G   52M   53G   1% /mnt
tmpfs           2.8G     0  2.8G   0% /run/user/1000
/dev/sdc       1007G   46G  911G   5% /home/az-user/apps
```
- df -i
```
Filesystem      Size  Used Avail Use% Mounted on
udev             14G     0   14G   0% /dev
tmpfs           2.8G  8.7M  2.8G   1% /run
/dev/sda1        30G  2.0G   28G   7% /
tmpfs            14G   12K   14G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            14G     0   14G   0% /sys/fs/cgroup
/dev/sdb1        55G   52M   53G   1% /mnt
tmpfs           2.8G     0  2.8G   0% /run/user/1000
/dev/sdc       1007G   46G  911G   5% /home/az-user/apps
```

How to make neo-cli works? thanks

**Comment by LoranceChen** [comment]
I finally find it's relative with `--log` parameter.   
It seems a bug in neo-cli when parse NEP5 application log in some block, such as at this block 2562249 in will always crash with the exception( the block count got by `show state` it shows `Height: 0/2562249/2570780, Nodes: 6`).   
It will works if I'm remove `--log` to skip the block application log parsing.

But because I have to skip some block, so it will lose some NEP5 transaction history.

**Comment by bitcodernull** [comment]
i have met the prob;em at 2571921~2571922

**Comment by bitcodernull** [comment]
i have moved the application-log files and restarted the neo-cli, it works

but if i want to find old tx on blockchain, i will lose NEP5 transaction history.

**Comment by PeterLinX** [comment]
@LoranceChen @bitcodernull 
Recently, NEO has 2 issues:
1. Attacked by tremendous "malicious" transactions, the solution is already explained here.(https://medium.com/@robogladiator/annocements-about-attack-transactions-in-neo-9fd7409fb3c6)
2. neo-cli breaks down. Hastened by the first issue, too many files are created in ApplicaionLogs directory. It just result in inodes full in linux server. 
I think you're affected by the second issue. If you delete files in ApplicationLogs then this problem will no longer occur. All those logs stores the events info in NEO blockchain, for example, if you delete them all, you can't query any NEP5 asset transfer info. So you need to make decisions based on what you need now.

**Comment by LoranceChen** [comment]
hi @PeterLinX, I have checked inode is not full yet. But it works if I'm remove ApplicationLogs to another place. Besides, I have check linux file descriptor should be enough by set as `ulimit -n`: 102400.

**Comment by apisit** [comment]
I have the exact same issue. 
Server still has space left and inode is not full.

My workaround was, I changed the `ApplicationLogs` in `config.json` file to be a different directory.

This solved `No space left on device` issue and I am able to run the node again. however, if you are running the rpc node that serves `getapplicationlog`, you won't be able to get the old TXs since they are in another directory.

I am still trying to figure out how to solve this properly.

**Comment by PeterLinX** [comment]
>find ./directory -type f -ctime +30 | xargs rm -rf

**Comment by apisit** [comment]
@PeterLinX but isn't that going to make old TXs inaccessible via `getapplicationlog` ?

**Comment by yousq** [comment]
I'm dealing the same problem

**Comment by hal0x2328** [comment]
The best solution is fixing the ApplicationLogs code in neo-cli to store the logs in a LevelDB database, but that's a bit of work. But I expect this may be something that NGD is looking at doing for the next release now that everyone running an RPC node on Linux is hitting this threshold. 

Alternatively you could modify the code to simply store the logs in a prefixed directory, e.g. ApplicationLogs/ff/ff37a6b9c4d3830fd6ce... etc. 

If you want a solution that doesn't require modification of the neo-cli code, you could try modifying your filesystem parameters, specifically dir_index can be turned off on ext4 to eliminate the inode hash collision causing the error. However that's going to be a performance hit on the whole system, not sure how severe.

**Comment by PeterLinX** [comment]
@apisit @hal0x2328 @yousq @bitcodernull @LoranceChen 
Problems:
Recently, NEO has 2 issues:
1. Attacked by tremendous "malicious" transactions.
2. neo-cli breaks down. Hastened by the first issue, too many files are created in ApplicaionLogs directory. It just result in inodes full in linux server. 
Solutions:
1. The solution is already explained here.(https://medium.com/@robogladiator/annocements-about-attack-transactions-in-neo-9fd7409fb3c6)
2. Temporary solution is to delete files from the beginning to 30 days ago in ApplicaionLogs directory, reboot neo-cli with --log, everything should be fine.(Something Like this: >find ./directory -type f -ctime +30 | xargs rm -rf) However, this method also deletes some transfer history of nep5 tokens. The best solution is to store logs info in leveldb, which is already implemented here(https://github.com/neo-project/neo-plugins/tree/master/ApplicationLogs). NGD has tested this solution for a week, we hope to release it ASAP.

**Comment by lock9** [comment]
Hello,
This is fixed, I'm closing it.
If you think this was a mistake, please reopen this issue. Thanks.
