### ISSUE TITLE
Can't run neo-cli in background

### ISSUE THREAD

**Issue by skinderis** [neo-project/neo-cli#209]
@erikzhang provided that it can be done by running `screen -S neo ./neo-cli --rpc,` but it is not running in background, I can't close the terminal. When I close I close it the process is terminating.

For example, I run:
`docker run --rm onitsoft/neo screen -S neo ./neo-cli --rpc`
And I get respond:
`Must be connected to a terminal.`

When I run in interactive mode with `-it` flag (`docker run -it --rm onitsoft/neo screen -S neo ./neo-cli --rpc`) it works well, but the terminal stays open and I can't close it without stopping `neo-cli`.

Any suggestions?

**Comment by NeoEscrow** [comment]
**Ctrl + A + D** to detach screen session
**screen -r neo** to resume screen session
;)

**Comment by skinderis** [comment]
@NeoEscrow Thanks! Is it possible to run it automatically when you run `docker-compose up`? I mean to add command in `docker-compose.yml`, so the container goes to `detach` mode.

**Comment by skinderis** [comment]
I just ran it by adding `stdin_open: true` and `tty: true` to my `docker-compose.yml` file and when ran it clicked **Ctrl + Z**.

**Comment by NeoEscrow** [comment]
>  Is it possible to run it automatically when you run docker-compose up? I mean to add command in docker-compose.yml, so the container goes to detach mode.

docker-compose up -d
