### ISSUE TITLE
seed4 - neo preview invocation response

### ISSUE THREAD

**Issue by birmas** [neo-project/neo-cli#210]
Response object after an invoke has changed and is inconsistent with current mainnet nodes.

result used to be a boolean, now it is an object with a boolean and a string for reason (great - reason is sorely needed)

txid is also missing from the response.

Suggest, for backward compatibility that result remain as a boolean - resultDetails contain the object and txid remain.

```
{ jsonrpc: '2.0',
  id: 1234,
  result: { succeed: true, reason: 'Succeed' } }
```

**Comment by erikzhang** [comment]
Is there txid in the original return result?

**Comment by birmas** [comment]
Yes sorry I didn't include the existing response
```
 response: 
   { jsonrpc: '2.0',
     id: 1234,
     result: true,
     txid: '..........' } }
```

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/9cf0d94f0979ea579e6b9d660359e0c49625532b/neo/Network/RPC/RpcServer.cs#L240-L244

Sorry, I didn't find the code to send txid.

**Comment by birmas** [comment]
maybe txid is being appended by neon-js and isn't applicable to this issue.

Regardless it would still be good for backward compatibility to have `result`: boolean and `resultDetails`: [object] both returned

what do you think @erikzhang ?

**Comment by erikzhang** [comment]
I think this may not follow the jsonrpc specification.
https://www.jsonrpc.org/specification

**Comment by vncoelho** [comment]
I think that the standard has been kept after release of 2.9.0+, however, fell free to reopen if anything still should be discussed.
