### ISSUE TITLE
open wallet via RPC or on neo-cli startup

### ISSUE THREAD

**Issue by skinderis** [neo-project/neo-cli#212]
I need to setup neo wallet that can be `fully controlled via RPC`. The thing is that when I need to control wallet, I have to open it locally (**but it doesn't fit my requirements**). 

Is there any way to open wallet remotely or to open it when I start docker container?

Thanks for your help!

**Comment by penlite** [comment]
You cannot currently open wallet via RPC as this would allow people to open wallets all over the place.

Not sure on whether you can progammatically run the CLI comands remotely.

**Comment by skinderis** [comment]
@penlite So that's point that I need to open wallet all over the place. The wallet is on another server and I can't connect all the time to server and open wallet locally. It needs to be done automatically and remotely. 

```
"UnlockWallet": {
      "Path": "wallet.db3",
      "Password": "wallet_password",
      "StartConsensus": false,
      "IsActive": false
    }
```


Also it can't be open all the time, if I provide `isActive: true` in **config.json**, it can be accessed all the time. 
Also also, is there any way to pass wallet password only when I need to open it, i. e. passing something like `"Password": ${WALLET_PASSWORD}`, so it won't be stored in `config.json` file and accessed any time.

@erikzhang
