### ISSUE TITLE
sendtoaddress return "One of the identified items was in an invalid format."

### ISSUE THREAD

**Issue by kennyqqr** [neo-project/neo-cli#214]
neo-cli version: 2.7.6 & 2.7.6.1

Hi, I use json rpc api to connect my neo wallet.

Here's the sendtoaddress json
{"method":"sendtoaddress","id":1,"jsonrpc":"2.0","params":["c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b","AR2Q2iWuoUsbtScP9MyGQhq9hpZQ6MxG7y",0.769]}

and it return
{"jsonrpc":"2.0","id":1,"error":{"code":-2146233033,"message":"One of the identified items was in an invalid format."}}

I use the same way to send to the same address at 2018-07-09.
Is there any change on this api?

**Comment by kennyqqr** [comment]
Has anyone suffer this problem, either?

**Comment by guotie** [comment]
same question when claim gas

**Comment by daivq** [comment]
@kennyqqr  The NEO amount must be an integer, not float

**Comment by kennyqqr** [comment]
> @kennyqqr The NEO amount must be an integer, not float

ok, thx.

**Comment by vncoelho** [comment]
If you still have any question please check the https://docs.neo.org of fell free to reopen and ping here.
