### ISSUE TITLE
How to get neo address balance?

### ISSUE THREAD

**Issue by ishwarchandratiwari** [neo-project/neo-cli#216]
How to get neo address balance using RPC connection,
Is there any free rpc endpoint available for neo testnet node

**Comment by skinderis** [comment]
You can get it using curl.
```
curl -X POST \
    http://localhost:30334 \
    -H 'Content-Type: application/json' \
    -d '{ "jsonrpc": "2.0", "id": 5, "method": "getbalance", "params": ["c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b"] }'
```

In params you should pass asset_it (`c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b` - is NEO)

**Comment by ishwarchandratiwari** [comment]
**I am getting auth error for using below code:**
curl -X POST \
    http://localhost:30334 \
    -H 'Content-Type: application/json' \
    -d '{ "jsonrpc": "2.0", "id": 5, "method": "getbalance", "params": ["c56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b"] }'

**ERROR =>**
{
    "jsonrpc": "2.0",
    "id": 5,
    "error": {
        "code": -400,
        "message": "Access denied."
    }
}
I am using Nodejs to build this api do i need to configure RPC connection?
Help how to make rpc connection for neo node in nodejs

**Comment by skinderis** [comment]
I think it's because **you didn't open your wallet**. It can be opened locally, when you run neo-cli there is a method `open wallet`.

Try to run neo-cli and type `help`, there will some methods and one of the is `open wallet`. Also, if you didn't create wallet, you have to do it by typing `create wallet`.

**Comment by kentarohorie** [comment]
@ishwarchandratiwari 

open wallet example

edit neo-cli/config.json

```

"UnlockWallet": {
      "Path": "/home/user/wallets/wallet.json",
      "Password": "password",
      "StartConsensus": false,
      "IsActive": true
    }

```
