### ISSUE TITLE
Get transactions for the wallet

### ISSUE THREAD

**Issue by skinderis** [neo-project/neo-cli#218]
Do we have RPC endpoint to get transactions that affected the NEO wallet? Something like bitcoin's [listtransactions](http://chainquery.com/bitcoin-api/listtransactions). I need an endpoint to get transactions by wallet and not by address because in my wallet I might have like 100 addresses in the future, so it will be hard to track transactions by addresses.

**Comment by erikzhang** [comment]
Duplicate of #142
