### ISSUE TITLE
[Question] Stuck at 2623809/2623809/2623809

### ISSUE THREAD

**Issue by kanliyong** [neo-project/neo-cli#219]
Hi !

my local node stuck at 2623809/2623809/2623809 two days.

-  I have restart the node ,not works.

- I have delete peers.dat then restart the node ,not works .

please help !!

**Comment by Joter85** [comment]
Same issue here. 

Height: 2623809/2623809/2623809, Nodes: 10

**Comment by skinderis** [comment]
Same problem. I see they have some download  [MainNet (CDN77 > Deadblock Fix) - 8/16/2018 (MD5: 06ea9760c317b3693c758bbc07b0ad96)](https://github.com/CityOfZion/awesome-neo#blockchain-bootstrap-files)

The name is Deadblock Fix, maybe it fixes the issue. Gotta try

**Comment by LuoRyan** [comment]
Maybe this method can help. Try it.

> NEO network working well now. If anyone has syncing problem(suck with 2623809), please delete old blockchain data and download latest offline blockchain data package(https://neo.org/client/chain.zip)(MD5 of this chain.zip is 06ea9760c317b3693c758bbc07b0ad96). Resync the blockchain will solve this problem. Also, 2 things have been done to make syncing data more easily.
> 1.NGD run 10 new seed nodes which have been synced to the latest height to help community node maintainers to connect with.
> http://seed1.ngd.nework/
> ...
> http://seed10.ngd.network/
> 
> Please check this instruction for reference.(http://docs.neo.org/zh-cn/node/clo/seedlist.html/

> 2. We add a new web page(http://sync.ndg.network/)for people to download offline packages which can be used to boost the syncing process. Later we'll change it to https and add MD5 hash.

**Comment by Joter85** [comment]
Where was this published? Might be useful for future issues...

**Comment by arrix** [comment]
I was advised to delete chain folder and peers.dat and resync with bootstrap: http://1713188625.rsc.cdn77.org/chain/chain.zip

The chain bootstrap link is published on awesome-neo too.

Hope the dev team can give more information about the issue. What's the technical cause? When will a fix arrive?

**Comment by arrix** [comment]
I delete the chain folder and peers.dat and rsynced with bootstrap from http://1713188625.rsc.cdn77.org/chain/chain.zip

Now I'm stuck at block Height: 0/2558442/2558443, Nodes: 0. show node gives nothing.
Updated peer list in protocol.json but it didn't help.

Restarting neo-cli didn't help.

Finally I made it continue by removing --log from the command line.

**Comment by Joter85** [comment]
> Hope the dev team can give more information about the issue. What's the technical cause? When will a fix arrive?

**Comment by kanliyong** [comment]
How to resync with chain.acc file ?

**Comment by metachris** [comment]
Delete the Chain folder, put `chain.acc` in the same directory as neo-cli.dll, and then start neo-cli. It will sync up from chain.acc

**Comment by skinderis** [comment]
@metachris Do you know why when I run with chain.acc the rpc connections are closed? I can't access my wallet via RPC

**Comment by metachris** [comment]
Probably because it's just using up all resources for syncing from chain.acc. I'd recommend to let it sync back up and after `show state` shows the current block height only then move on to testing RPC

**Comment by ratikesh9** [comment]
After syncing with chain.acc the node is stuck on 2629182 block number @metachris  @skinderis can you help me with this?

**Comment by skinderis** [comment]
I synced fully, but when I shut down container, it gets stuck again. Now I am at the 2,640,291 block and it is not moving. How to solve the problem, guys??

**Comment by yousq** [comment]
Me tooooooooo, there are nearly 20% issues talking about this PROBLEM, why not fix it thoroughly ?

**Comment by yousq** [comment]
I deleted the old chain data, and used the latest Full Offline Package chain.cc.zip, but things got more terrible: it was stucked at 1945082/1945082/1945082, Nodes: 0

**Comment by ratikesh9** [comment]
Any development on this?

**Comment by fabwa** [comment]
Please use https://github.com/neo-project/neo-cli/releases/tag/v2.7.6.1 for now.
Bootstrap with this for Chain: https://cozboot.s3-us-west-2.amazonaws.com/chain-2640xxx.tar.gz
and this for notifications: https://cozboot.s3-us-west-2.amazonaws.com/notif-2640xxx.tar.gz
Please update protocol.json and replace seeds with:

seed1.ngd.nework:10333
...
seed10.ngd.network:10333

That should work..

**Comment by vladicoin** [comment]
cli 2.7.6.1  works
2.7.6 is stuck 
and 2.8.0 is also stuck

**Comment by fabwa** [comment]
@vladicoin you cannot generalize like this. I have all those versions running and sync up to current block height. Please follow instruction above for 2.7.6 / 2.8.0 if you need those.

**Comment by vladicoin** [comment]
to be clear:
I ran all those versions from fresh installation and the above was the result.
@fabwa notifications are the result of "--log" ?

**Comment by fabwa** [comment]
Correct @vladicoin - did you run them with bootstrap beyond the dead block?

**Comment by vladicoin** [comment]
actually no,
ver 2.7.6.1 just worked from the getgo ( github release )

**Comment by fabwa** [comment]
Then you were lucky

**Comment by vladicoin** [comment]
@fabwa i'll take that :)

**Comment by ratikesh9** [comment]
Height: 2647389/2647389/2647389, Nodes: 6  my node is synced but every withdraw which i am pushing on chain now is not confirming and giving the [ code = -100 and error=Unkown Transaction]

**Comment by ratikesh9** [comment]
@fabwa  thanks for the help.

For the guys in this thread I would strictly recommend to upgrade the neo-cli to 2.7.6.1 or + and for doing so follow these steps:

1. Backup your wallets.db3 file.

2. Download the neo-cli from https://github.com/neo-project/neo-cli/releases/tag/v2.7.6.1 for now.

3. Download the chain folder from  https://cozboot.s3-us-west-2.amazonaws.com/chain-2640xxx.tar.gz

4. If you are using --logs while starting the neo-cli do download https://cozboot.s3-us-west-2.amazonaws.com/notif-2640xxx.tar.gz

5. After step (3) and (4) extract the compressed files and place them inside the neo-cli extracted from step (1).

6. Update the protocol.json with peers 
  "SeedList": [
      "seed1.ngd.nework:10333",
      "seed2.ngd.nework:10333",
      "seed3.ngd.nework:10333",
      "seed4.ngd.nework:10333",
      "seed5.ngd.nework:10333",
      "seed6.ngd.nework:10333",
      "seed7.ngd.nework:10333",
      "seed1.aphelion-neo.com:10333",
     "seed4.aphelion-neo.com:10333",
     "seed2.redpulse.com:10333"
    ],
    or use http://monitor.cityofzion.io/ to find the peers for the specific version of neo-cli you are using.

7. Start the neo-cli from ./neo-cli (Recommended to run using screen as deamon.

8. Unlock your wallet and check state using show state command then you will see the node is stuck on Height: 0/0/0, Nodes: 0
 
9. Kill the neo-cli process and move  the files from Chain folder to Chain_007* type of folder.

10. Restart the neo-cli using the same command and slowly your node will sync up.

**Comment by fabwa** [comment]
In step 5. rename extracted Chain folder to Chain_00746E41 - then you can skip 8 and 9.

**Comment by bboyHan** [comment]
After syncing with chain.acc the node is stuck on 2629182 block number @metachris @skinderis 
can you help me with this?

**Comment by anyouuu** [comment]
After syncing with chain.acc the node is stuck on 2560977 block number @metachris @skinderis
can you help me with this?

**Comment by penlite** [comment]
are you both still stuck @bboyHan and @anyouuu ?

**Comment by metachris** [comment]
@ratikesh9 small correction re your point 4

> If you are using --logs while starting the neo-cli do download https://cozboot.s3-us-west-2.amazonaws.com/notif-2640xxx.tar.gz

This download is not for neo-cli with `--logs` but only works with the [notification server](https://github.com/localhuman/neo-cli/blob/plugin-notification-restapi/notifications.md)

**Comment by ratikesh9** [comment]
@metachris noted

**Comment by bboyHan** [comment]
@penlite   I downloaded the client（2.7.1.0）, reinstalled, and deleted all the data before running properly.
It  is unfriendly to wastes a lot of time for me.

**Comment by Edgegasm** [comment]
Same issue, now stuck at #3,122,385.

**Comment by jsolman** [comment]
@Edgegasm
It appears the issue is due to getting a block that seems valid (at least in the case if 3122384, it contains the exact same transactions as the valid block and validates correctly) but is really an orphaned block. An example of this occurred on MainNet at height 3122384.

Neoscan actually has the wrong block hash for this height also which is quite interesting. I was able to get a node stuck syncing at this height with the wrong hash. Interestingly, the transactions in the block look identical though to the correct block.

Incorrect hash shown on neoscan for block 3122384:
`0xc01f377f76c95a165635c251fe36b346de5c32a246645c334d3325a425fc025c`
https://neoscan.io/block/C01F377F76C95A165635C251FE36B346DE5C32A246645C334D3325A425FC025C

Correct hash from another one of my nodes for block 3122384:
`0x5c445c2bf6855df7ea9b86a21db84b432611a17c48ba4466fa005e8739524e4e`

I will try to look into it more later, as I believe this is happening a lot on TestNet also and causing nodes to get stuck syncing. I restored from a saved copy of the Chain folder on the node that was stuck about 100 blocks back from the point it got stuck and it synced a second time normally without getting the bad block. (It probably goes without saying that getting the bad block is dependant on randomly having got blocks or headers from the bad node and accepted the bad hash -- such bad nodes usually stay around serving up their bad blocks for a long time since they will forever be stuck). 

I thought of a ways to avoid persisting this bad block while syncing, but the issue that allows it to create such a valid bad block with a different gas but same transactions will need to be addressed.

**Comment by Edgegasm** [comment]
Thanks for the info @jsolman. Interesting to see an orphan block with the same transactions as the correct block. Wonder how that happened.

I'm currently resyncing with the latest NGD chain zip, which is past the problem block (height 3125968). I'm guessing this won't be an issue anymore after the [#422](https://github.com/neo-project/neo/pull/422) changes are included.

**Comment by vncoelho** [comment]
Different nonce while transactions did not arrive meanwhile.

**Comment by vncoelho** [comment]
Sorry, miss click.

**Comment by jsolman** [comment]
@Edgegasm Yeah consensus improvements in progress should fix it.

**Comment by vncoelho** [comment]
This has been probably solved by avoiding the expose of CN signatures when crashing or after network delays that could cause view to change.

Commit https://github.com/neo-project/neo/commit/f88c427987791e11387ca23eadb619a5e9fdfff9 probably solved that. Fell free to open it again for further investigation or discussion.

**Comment by mm999222** [comment]
I apologize I am not knowledgeable enough to follow the above suggestions. I have the same issue: 
My NEO wallet (ver 2.6.6596.21976) won't update past block 2623809. I am wondering if I simply use the wallet "Rebuild Index" feature will that solve the problem? Any advice is greatly appreciated :)

**Comment by EdgeDLT** [comment]
@mm999222 There's no need for normal users to bother maintaining a full node anymore.

If you want to maintain a full copy of the blockchain, you'll need to delete your current chain folder then download a synchronization package to get past the dead block. Instructions for that are [here](https://docs.neo.org/en-us/network/syncblocks.html).

If you would prefer not to deal with synchronization, you can simply use a light wallet client such as [Neon wallet](https://neonwallet.com/).

**Comment by mm999222** [comment]
Thanks for replying! If I switch to NEON wallet how do I transfer my NEO, Gas and ONT to the new NEON wallet?

**Comment by EdgeDLT** [comment]
@mm999222 You don't need to transfer anything, your funds are on the blockchain and not actually "in" a wallet. You can just log into NEON with the same private key you have from neo-gui.

Also, ONT moved to its own MainNet a while ago and the swap closed quite a while ago. I recommend sending them to Binance as I have heard they are still honouring ONT token swaps. Once you have the MainNet ONT tokens, you'd need to store them in an Ontology wallet.

You can use [O3 wallet](https://o3.network/) instead of Neon, it supports both the NEO and Ontology blockchains.

**Comment by mm999222** [comment]
Tk u! Can I send my ONT from my NEO wallet to Binance even thought my NEO wallet is not currently  syncing?

**Comment by EdgeDLT** [comment]
@mm999222 An encrypted key is just your private key encrypted by the password. As long as you have the private key, you will not get locked out of anything. 

Encrypted keys are just an extra safety step. Make sure you typed the passphrase in both the 'create' step and the 'confirm' step. That should make the box light up again.

**Comment by mm999222** [comment]
Yes I did put my pass phrase in both boxes and I pasted my private key in the private key box. But the "create" button becomes inactive. I am wondering if this is happening because the private key has already been used to open the wallet? And therefore you can't encrypt it maybe? I appreciate all the help

**Comment by EdgeDLT** [comment]
That's more likely to be a bug with Neon rather than anything to do with the private key. Technically you can encrypt a key as many times as you like with as many different passwords.

Have you ensured that the private key is copied correctly with no spaces? I just tried to encrypt a key and it worked for me.

**Comment by mm999222** [comment]
Yes, I used the same key (copy/paste) that I used to log into the wallet

**Comment by mm999222** [comment]
What if I create a new private key (in my NEON wallet) and encrypt it with a pass phrase? Will I have the same access to my NEO tokens and the other tokens that show in the NEON wallet?

**Comment by EdgeDLT** [comment]
You can make a new private key, which would be paired with a new public key. So you'd need to send your funds from the current address to the new one. But yes, that should be a good workaround for you since you can encrypt the new key during creation.
