### ISSUE TITLE
transcations are not injected in block from 17:00 8.24

### ISSUE THREAD

**Issue by bitcodernull** [neo-project/neo-cli#223]

**Comment by yanchang-gyc** [comment]
the same problem

**Comment by bitcodernull** [comment]
i have added some seeds of main branch submited, it works well now
https://github.com/neo-project/neo-cli/commit/f67272706915731c20bf09276e96dfebd51b5d02

protocol.json:

 "SeedList": [
      "seed1.ngd.nework:10333",
      "seed2.ngd.nework:10333",
      "seed3.ngd.nework:10333",
      "seed4.ngd.nework:10333",
      "seed5.ngd.nework:10333",
      "seed6.ngd.nework:10333",
      "seed7.ngd.nework:10333",
      "seed8.ngd.nework:10333",
      "seed9.ngd.nework:10333",
      "seed10.ngd.nework:10333",
      "seed1.neo.org:10333",
      "seed2.neo.org:10333",
      "seed3.neo.org:10333",
      "seed4.neo.org:10333",
      "seed5.neo.org:10333"
    ],
