### ISSUE TITLE
Unable to open wallet file when compiling from source

### ISSUE THREAD

**Issue by Sjors** [neo-project/neo-cli#23]
I compiled neo-cli from source using the README instructions (see #22).  I am able to create a new wallet, but I get an error when trying to open it. I can open the wallet using the compiled binary wallet. So I think there is a bug when opening the wallet, not when saving it.

I created a new wallet:

```
../dotnet neo-cli/bin/Debug/netcoreapp1.0/neo-cli.dll
neo>create wallet wallet.db3
password:****
password:****
address: AXFeCtob7JdrN78qnV95rxKiFUw32VPja5
 pubkey: 02e0b70529c9b44084f63e7046afedad1e3fc7fa77fb4763845439fc63024e87e3
neo>exit
``` 

I then try to load the wallet:
```
neo>open wallet neo-cli/bin/Debug/netcoreapp1.0/wallet.db3
password:****
failed to open file "neo-cli/bin/Debug/netcoreapp1.0/wallet.db3"
```

When I use the compiled binary I can open the wallet and see the address. I attached the wallet as a zip file. The password is `1234`. There's no money in it.

[wallet.zip](https://github.com/neo-project/neo-cli/files/1245975/wallet.zip)

**Comment by erikzhang** [comment]
try this:
```
open wallet wallet.db3
```

**Comment by Sjors** [comment]
It just says `error` in that case; it probably can't find it without the path.

**Comment by erikzhang** [comment]
```
cd neo-cli/bin/Debug/netcoreapp1.0/
dotnet neo-cli.dll
```
```
open wallet wallet.db3
```
