### ISSUE TITLE
convert

### ISSUE THREAD

**Issue by prettyCoders** [neo-project/neo-cli#230]
How do I convert ByteArray into Address and amount use java
![temp](https://user-images.githubusercontent.com/36216120/45615560-7593ff80-ba9f-11e8-9cdb-00998f79f664.png)

**Comment by shargon** [comment]
You need to find a compatible class from `BigInteger` in java, honestly i don't know.

A quick search:

https://stackoverflow.com/questions/42027489/c-sharp-biginteger-equivalent-in-java

If you need more help, do not hesitate to reopen the issue
