### ISSUE TITLE
It returns "Access denied" with invokeScript in 2.9.0

### ISSUE THREAD

**Issue by ediopia** [neo-project/neo-cli#232]
Tested using Postman.

### Test in 2.8.0
https://test2.cityofzion.io:443?jsonrpc=2.0&method=invokescript&params=["1488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f6667187f2e3c81bbc0e36de5521aeba9a2dd6936fd221488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f666776db3192722022eb7841038246dc8fa636dcf2741488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f66673fbc607c12c28736343224a4b4d8f513a5c27ca81488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f666737e558ef781b899d61fe204c75761e699bd42ede1488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f66675ff6bfaa9b114c4f1527f34e75b292a972586c54"]&id=1234
**returns**
{
    "jsonrpc": "2.0",
    "id": 1234,
    "result": {
        "script": "1488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f6667187f2e3c81bbc0e36de5521aeba9a2dd6936fd221488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f666776db3192722022eb7841038246dc8fa636dcf2741488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f66673fbc607c12c28736343224a4b4d8f513a5c27ca81488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f666737e558ef781b899d61fe204c75761e699bd42ede1488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f66675ff6bfaa9b114c4f1527f34e75b292a972586c54",
        "state": "FAULT, BREAK",
        "gas_consumed": "0.571",
        "stack": []
    }
}

### Test in 2.9.0
http://seed4.neo.org:20332?jsonrpc=2.0&method=invokescript&params=["1488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f6667187f2e3c81bbc0e36de5521aeba9a2dd6936fd221488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f666776db3192722022eb7841038246dc8fa636dcf2741488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f66673fbc607c12c28736343224a4b4d8f513a5c27ca81488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f666737e558ef781b899d61fe204c75761e699bd42ede1488d63ab80add539af5001250a7e272f3f3509d3651c10962616c616e63654f66675ff6bfaa9b114c4f1527f34e75b292a972586c54"]&id=1234
**Returns**
{
    "jsonrpc": "2.0",
    "id": 1234,
    "error": {
        "code": -400,
        "message": "Access denied"
    }
}

**Comment by kentarohorie** [comment]
Do you open wallet?

You should edit neo-cli/config.json

for example

```

"UnlockWallet": {
      "Path": "/home/user/wallets/wallet.json",
      "Password": "password",
      "StartConsensus": false,
      "IsActive": true
    }

```

**Comment by xxedocxx** [comment]
Do I need to open wallet to use invokeScript?
I dont think it was requirement in previous versions.

**Comment by lock9** [comment]
@ediopia hello,
Please check [here](https://docs.neo.org/en-us/node/plugin.html).
You need a plugin in versions 2.9+.

Please reopen your issue if you think this was a mistake.
