### ISSUE TITLE
Getting 'Unknown Transaction' while calling getApplicationLog

### ISSUE THREAD

**Issue by ppsdang** [neo-project/neo-cli#235]
Hi,

I am getting Unknown Transaction while calling getApplicationLog

I have started server using following command:

dotnet neo-cli.dll --rpc --log

After this I am sending NEO to my wallet address.

Then I get txId : 0x14dcdf982eafafff168c95341991e5b8c05542b0f20690d84ab0867be473fed0
which is a contractTransaction

but If I check it using getApplicationLog
I am getting 'Unknown Transaction'

{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -100,
        "message": "Unknown transaction"
    }
}

**Comment by shargon** [comment]
Your node doesn't have this transaction, is not sync or is not exists on your node
