### ISSUE TITLE
How I can open wallet via RPC on remote server?

### ISSUE THREAD

**Issue by skinderis** [neo-project/neo-cli#238]
I have set up the node, created the wallet and now need to open wallet remotely. The thing is that my wallet is on remote server. Trying to automate wallet opening before getting balance or sending NEO. 

I know that it is possible to open wallet on startup by providing `wallet file`, `password` and setting `isActive: true` in `config.json` file, but it stays open all the time and anyone can access wallet if they get access to the server.

Is there any way to open wallet remotely via RPC?

Maybe you guys @erikzhang @metachris @purplesoft-io  know how could I solve this issue?

Will be thankful for any help!

**Comment by erikzhang** [comment]
There is no way to open wallet remotely via RPC. There are only two ways to open a wallet:

1. Open it in command line: `open wallet <path>`
2. Open it at startup by setting up the `config.json`.

**Comment by gairom** [comment]
Why do you need to open the wallet?
Most operations can be done be using the RPC API remotely (but require some work...). 
I have the same scenario and everything is done remotely using the api including balance, transactions etc.
If you are using JS you can use neon-js which is a great lib which provides almost any operation available and easy to use.

**Comment by skinderis** [comment]
@gairom, you can do anything remotely when wallet is open. But it can be hacked more easily then. 

Yesterday I opened the wallet to test some RPC methods, sent 1 NEO to my wallet and suddenly it was sent to some address from my wallet to address: **AGQGKFJ7MTMvePZcz1KEmd9UVWzZbRsotC**. 

You can check my address in explorer (**AcdBoqYVyJV8j9NCk4s5dry3rjdocve8LM**) and see 2 transactions (**IN** and **OUT**): . So, the thing is that someone was sending requests to my wallet and getting balance, as soon as it returned him balance >0, he sent it to his address.

I didn't set firewall yet, cause I was just testing. So I need to open and close wallet whenever I want remotely just to add some more security to it.

**Comment by erikzhang** [comment]
You can use this [Rpc Security Plugin](https://github.com/neo-project/neo-plugins/tree/master/RpcSecurity). It adds basic authentication to RPC.

**Comment by skinderis** [comment]
@erikzhang thanks, that's what I need.

**Comment by gairom** [comment]
I'm not opening the wallet at all, everything is done remotely by RPC calls...
In addition I have firewalls and authentication to control access to make RPC calls.

**Comment by skinderis** [comment]
@gairom What about **getbalance**, are you using this method? This one needs wallet to be open.
