### ISSUE TITLE
System.DllNotFoundException:“Unable to load DLL 'libleveldb': 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)”

### ISSUE THREAD

**Issue by jccgjccg** [neo-project/neo-cli#24]
目前路径 \neo-cli-master\neo-cli\bin\Debug\netcoreapp1.0\ 下面有这个dll 但还是报错
libleveldb 这个dll应该放在哪个路径下呢

**Comment by deanpress** [comment]
You need dotNET Runtime 1.12 (LTS), not 2.0.

**Comment by facadev** [comment]
Doesn't seem to work still.

```
# dotnet
Microsoft .NET Core Shared Framework Host

  Version  : 1.1.0
  Build    : 928f77c4bc3f49d892459992fb6e1d5542cb5e86
......

# dotnet neo-cli.dll
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Neo.IO.Data.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)
Aborted
```

I downloaded .NET Core from https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.2-download.md.

**Comment by metachris** [comment]
neo-cli works with dotnet 2.0. this error looks like your system is missing the libleveldb dependency. 

what OS are you using? the Readme describes installing the dependencies libleveldb-dev, sqlite3, libsqlite3-dev, libunwind8-dev, did you setup those?

**Comment by scwang90** [comment]
That worked!

I unnistall dotnet-2.0 and  install dotnet-1.1.6 
[dotnet 1.16 for Win10 x64](https://download.microsoft.com/download/A/7/E/A7EF2AFF-F77B-4F77-A21B-0F7BD09A4065/dotnet-win-x64.1.1.6.exe)

**Comment by anyouuu** [comment]
λ dotnet neo-cli.dll


#NEO-cli version 2.8

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb': 找不到指定的模块。 (Exception
from HRESULT: 0x8007007E)
   at Neo.IO.Data.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)

**Comment by wally-yu** [comment]
from ubuntu:
`sudo apt-get install libleveldb-dev sqlite3 libsqlite3-dev libunwind8-dev`
works for me
