### ISSUE TITLE
Export block command is missing on help menu of neo-cli

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-cli#241]
"export block" command isn't showed on help menu of neo-cli. I think is a little bug.
![image](https://user-images.githubusercontent.com/38493437/46940442-5044e200-d09b-11e8-8e8b-30a36efeb20c.png)

**Comment by erikzhang** [comment]
This command has moved to https://github.com/neo-project/neo-plugins/tree/master/ImportBlocks

**Comment by superboyiii** [comment]
@erikzhang I see. But it might be a bit not friendly to new users who wish learn command from help menu since this menu is mostly designed for these users. If it's not the necessary but vital function of neo-cli, could the menu be made as dynamic state which show "export block" command when the ImportBlocks plugin is installed? Just my little advice.

**Comment by lock9** [comment]
Hi, I created a new issue for this plugin thing. I'm closing this issue.
Feel free to reopen this issue if you think this was a mistake
