### ISSUE TITLE
申请测试链neo和neogas

### ISSUE THREAD

**Issue by anysoft** [neo-project/neo-cli#242]
因为项目需要对接neo主链，目前开发再测试链上需要neo和gas。
NEO地址：AYBkVwgiuZ3G88PUMenbBfc9eCM1S7Jmc7
公钥：024c185ab383d01cf066534124bb91df574f42b193627784b7e4e8878a7b48597c

**Comment by txhsl** [comment]
[测试NEO&GAS申请](https://neo.org/Testnet/Create)
