### ISSUE TITLE
rpc Invalid Request

### ISSUE THREAD

**Issue by antechdemo** [neo-project/neo-cli#243]
curl -X POST http://0.0.0.0:20332/json_rpc -d '{"jsonrpc": "2.0", "id": 5, "method": "getnewaddress"}'

Error:->
{"jsonrpc":"2.0","id":5,"error":{"code":-32600,"message":"Invalid Request"}}

**Comment by erikzhang** [comment]
```
{"jsonrpc": "2.0", "id": 5, "method": "getnewaddress", "params": []}
```
