### ISSUE TITLE
is there max number limit on command `create address [n=1]` 

### ISSUE THREAD

**Issue by a1onzo** [neo-project/neo-cli#251]
when i try to create some address, i got this error:
`neo> create address 10000`
`[171/10000]error`
`neo> create address 2000`
`[92/2000]error`
`neo> create address 2000`
`[116/2000]error`
`neo> create address 100`
`[92/100]error`

i wonder if there is max number limit on command `create address [n=1]` ?
neo-cli version : 2.8.0
os version: Ubuntu 16.04.4

**Comment by txhsl** [comment]
The related code is `OnCreateAddressCommand` in MainService.cs, I think there is no such a limit.

**Comment by shargon** [comment]
Please try with the last release, and review your rights in the folder. I will close it, if the problems reappear, feel free to create a new issue
