### ISSUE TITLE
the transactions don't been injected on blockchain

### ISSUE THREAD

**Issue by bitcodernull** [neo-project/neo-cli#254]
i found some transactions have not injected on blockchain after 2:00PM

maybe because the number of transactions is increased after 2:00 PM

I found that there are a lot of transactions after 2 o'clock, there are dozens of transactions on one block, only a few before 2 o'clock.

maybe i should wait..

**Comment by bitcodernull** [comment]
maybe i need give some gas fee?

**Comment by shargon** [comment]
There are a 20 free transaction max per block, so if the network is congested, i recommend you to add some gas, now you should not have any problems
