### ISSUE TITLE
 ApplicationLogs is disappeared when i upgrade to 2.9.1

### ISSUE THREAD

**Issue by bitcodernull** [neo-project/neo-cli#255]
is it ok?
i still can get the nep-5 token logs?

**Comment by bitcodernull** [comment]
i found getApplicationLog rpc is invalid

**Comment by bitcodernull** [comment]
i can not get nep-5 transactions from chain without the getApplicationLog interface

how to resolve it? thanks

**Comment by bitcodernull** [comment]
who can help me?

**Comment by belane** [comment]
Hi @bitcodernull I think the functionality you look for is now in the plugin system, https://github.com/neo-project/neo-plugins/tree/master/ApplicationLogs.

You can use the last release of ApplicationLogs https://github.com/neo-project/neo-plugins/releases

**Comment by bitcodernull** [comment]
thanks
