### ISSUE TITLE
Can I set the data folder different with the neo-cli.dll

### ISSUE THREAD

**Issue by lcgogo** [neo-project/neo-cli#259]
Like dotnet neo-cli.dll --rpc to set the data folder?
dotnet neo-cli.dll --data-dir=/data/neo

Now the data folder Chain_00746E41 is at the same folder of neo-cli.dll and I want to seperate them because I use docker container to run neo.

**Comment by erikzhang** [comment]
You can set the data folder at `config.json`.

**Comment by shargon** [comment]
As @erikzhang said, you can use this fail in order to config the folder
