### ISSUE TITLE
How do you properly backup wallet and addresses

### ISSUE THREAD

**Issue by vladyslavstartsev** [neo-project/neo-cli#262]
The problem that I've noticed when reading [this guide](http://docs.neo.org/en-us/exchange/v2.9.0.html#generating-deposit-addresses)

is that you warn about back ups.
I also need to notice that I use neo cli in docker container.
What is the best way to back up wallet and addresses, regularly and automatically .

Currently my idea is to backup the wallet with cron 
(I've read this https://github.com/neo-project/neo-cli/issues/59 and https://github.com/neo-project/neo-cli/issues/46 )

But the issue is that I can't automatically backup addresses - because what I do is 
- attach to neo cli daemon with `docker attach u32irgui32gfih3` where `u32irgui32gfih3` container id, 
- get  private keys with `export key`
- copy the cli output from terminal to a file

Is there a way to automatically backup private keys of all addresses?

**Comment by vladyslavstartsev** [comment]
in discordapp someone suggested to use `dumpprivkey`.
So I will get all addresses with `listaddress` and then iterate over them to get private key

It will be nice to have CLI API command to export all private keys of all addresses, something like `exportaddresskeys`

**Comment by vladyslavstartsev** [comment]
Also please make that it writes to NEP6 wallet the addresses that was imported with `import key` command

**Comment by belane** [comment]
If you are working with docker you can use `docker cp MyNeoContainer:/path/wallet.json /host_path/backup`.
Be careful exposing RPC and dumpprivkey.

**Comment by vladyslavstartsev** [comment]
> If you are working with docker you can use `docker cp MyNeoContainer:/path/wallet.json /host_path/backup`.
> Be careful exposing RPC and dumpprivkey.

I can, but according to [this](http://docs.neo.org/en-us/exchange/v2.9.0.html#generating-deposit-addresses) I can't.  Can you change those docs to be right, because you, as developer, say that I can do that, but the docs says I can't. Who is right?

**Comment by belane** [comment]
@vladyslavstartsev  I think the documentation is fine, it's a generic documentation and it is open to the implementation that each one wants.

It was just an advice to backup the wallet in a specific case of running it in a docker container.

In the case of an exchange, possibly the best option would be create a small program that generates the addresses and distributes them to the users.

**Comment by vladyslavstartsev** [comment]
> In the case of an exchange, possibly the best option would be create a small program that generates the addresses and distributes them to the users.

@belane do exactly like you said, but the main issue (as I said in title of issue) how to properly and automatically back things up. 

> It was just an advice to backup the wallet in a specific case of running it in a docker container.

there is nothing said about docker in those docs.

I mean, I need back ups of all of this, because I'm not sure that hosting provider will not loose my data/server.

If you don't want  to change the "Document for Exchange Developers" and add an article on how to properly back up wallets and/or addresses when using API.

That is the quote from docs
> while the disadvantage is you can not backup the wallet
this part of the docs is misleading (at least me).

**Comment by Celia18305** [comment]
The document is updated. See PR #672

**Comment by vladyslavstartsev** [comment]
@Celia18305 thank you!
