### ISSUE TITLE
how to set multiple ip in config.json

### ISSUE THREAD

**Issue by blatechen** [neo-project/neo-cli#265]
can anyone help me.  
I try to set "BindAddress": "*", but run neo-cli command was crashed.
"RPC": {
      "BindAddress": "127.0.0.1",
      "Port": 10332,
      "SslCert": "",
      "SslCertPassword": ""
 }
I had serveral server to call it, but I don't know how to set BindAddress property.

**Comment by erikzhang** [comment]
You can set it to `0.0.0.0` to bind to any address.

**Comment by blatechen** [comment]
> You can set it to `0.0.0.0` to bind to any address.

ok. thank you.
