### ISSUE TITLE
list asset沒有回應任何訊息

### ISSUE THREAD

**Issue by blatechen** [neo-project/neo-cli#266]
請問一下，為什麼我下了list asset指令，沒有任何反應，是因為我新建wallet的關係嗎？
還是裡面沒有資產才沒回應?
然後list asset沒反應的話我如果打幣進去會正常嗎?
我試過open wallet wallet.db3後，再打list asset 也是沒用、rebuild index後也是沒反應
我的環境是ubuntu

**Comment by txhsl** [comment]
> 請問一下，為什麼我下了list asset指令，沒有任何反應，是因為我新建wallet的關係嗎？
> 還是裡面沒有資產才沒回應?

是的，钱包内没有资产的情况下不会输出信息，另外记得同步到最新高度

**Comment by blatechen** [comment]
> > 請問一下，為什麼我下了list asset指令，沒有任何反應，是因為我新建wallet的關係嗎？
> > 還是裡面沒有資產才沒回應?
> 
> 是的，钱包内没有资产的情况下不会输出信息，另外记得同步到最新高度

好的，我打幣進去後就查的到了，非常感謝
