### ISSUE TITLE
Fails when 'UnlockWallet' section is filled in config.json

### ISSUE THREAD

**Issue by l-vitall** [neo-project/neo-cli#278]
Version 2.9.3.0 silently fails on startup (Windows 10) when I put some data to UnlockWallet. If remove this data then it starts normally again

**Comment by shargon** [comment]
What error did you receive? and please, show me a **sample** of your UnlockWallet data

**Comment by l-vitall** [comment]
I cannot reproduce it today. There was no error shown, only event was written to Windows Application Log. UnlockWallet very simple: 
_"UnlockWallet": {
      "Path": "myPrivNetWallet.json",
      "Password": "pwd",
      "StartConsensus": false,
      "IsActive": true
    }_

Also I notices that neo-cli application stopped to sync itself with private network (until I removed its databases)

**Comment by l-vitall** [comment]
Unable to start again.

Faulting application name: neo-cli.exe, version: 0.0.0.0, time stamp: 0x597139df
Faulting module name: coreclr.dll, version: 4.6.26614.1, time stamp: 0x5b22b860
Exception code: 0xc0000005
Fault offset: 0x000000000018434d
Faulting process id: 0x3d30
Faulting application start time: 0x01d4b4c54897c3eb
Faulting application path: e:\TokenAddition\NEO\testNet\neo-cli\neo-cli.exe
Faulting module path: e:\TokenAddition\NEO\testNet\neo-cli\coreclr.dll
Report Id: 285c4fd1-57cb-4764-9e60-4b44c2431371
Faulting package full name: 
Faulting package-relative application ID:

**Comment by vncoelho** [comment]
I think that this has been solved. No similar problem has been reported and this variable has been used without issues.

If you still have any problem in latest version please reopen this issue.
