### ISSUE TITLE
Add frontend interception for illegal asset value in transaction

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-cli#283]
When making illegal asset value in transactions by neo-cli, it could still get txid and be relayed. For example:
"send neo AVvTCJseyjAPABQxuWxayEjWUKpgQxxsKe -10". That is able to cause the result that the illegal transaction will stay in the mempool and it'll never be confirmed by consensus node. However, if your whole asset is a single utxo, the status should be spent and the change isn't able to be return. In this case, you could never send another transaction until you restart neo-cli to empty the mempool. My advice is that to make a judgement to return false on the frontend while in this situation to avoid illegal value.

**Comment by shargon** [comment]
I think that is solved, could someone confirm it?

**Comment by superboyiii** [comment]
Yes, it's solved.
![image](https://user-images.githubusercontent.com/38493437/61167504-b8651d80-a572-11e9-8a11-e4cae931af1e.png)
Close.
