### ISSUE TITLE
Can not create wallet on NEO 2.9.4

### ISSUE THREAD

**Issue by huyntchainos** [neo-project/neo-cli#284]
I tried to create wallet with NEO-CLI 2.9.4 on ubuntu 18.4. Following is error message.

neo> create wallet ~/neo-wallet/wallet.json                    
password: ****
password: ****
error
neo> version
2.9.4.0

**Comment by erikzhang** [comment]
I tested the `create wallet` command and no errors occurred. But during the test I found a deadlock problem and fixed it in https://github.com/neo-project/neo/pull/537.

**Comment by huyntchainos** [comment]
Which OS are you working on @erikzhang?

**Comment by huyntchainos** [comment]
It is now working. Needs to use fullpath neo> create wallet /home/user/neo-wallet/wallet.json
