### ISSUE TITLE
`show state` : height of remote node never change

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo-cli#287]
Alright, I can tell from the name of that height as it is called `StartHeight`. 
But why don't you update them? I mean, when I see those heights, I normally want to compare with my local height to check whether my local node is up to date.
![image](https://user-images.githubusercontent.com/10189511/51088865-213e1b00-1733-11e9-82b7-bccbad903bdf.png)

**Comment by jsolman** [comment]
`StartHeight` Is the height of the remote node when it established the tcp connection to the node in question. Perhaps another column of the current height of that node could be added, but the start height is still useful information.

**Comment by jsolman** [comment]
@Liaojinghui should we consider this a feature request to also show the current height of each remote node?

**Comment by Liaojinghui** [comment]
Personally, I think you can either add another column or change the name of `height` as `start height`. That is my own opinion since even though I've been using neo-cli for almost a  year, I never realized that height is actually not the real height of the remote node.

**Comment by ixje** [comment]
I'd say update to the latest known height. Start height isn't really useful once it's running. The latest height on the other hand is, so you can manually check if you're not stuck on all nodes that are behind.

**Comment by vncoelho** [comment]
I agree @ixje, we discussed this in other moments and it was kept like it is. But I think that it is an important change for us to improve the P2P communication.

**Comment by Liaojinghui** [comment]
And I also think that the node should only keep the connection with nodes who are at about the same height, just in case the user only find that they have synchronized the wrong chain after days of synchronizing. You know what I mean right? People's complaining about their node stuck at the height 3XXXX.

**Comment by vncoelho** [comment]
The node getting stuck was a problem that was probably now solved with dBFT 2.0.

The point is that we hope that people did not saved any duplicated block with a double signature. In such case that block could be used for propagating wrong blocks for those syncing direct from the network instead of bootstrapping.

**Comment by Liaojinghui** [comment]
@vncoelho Thank you for your reply,  really happy to hear that the issue was finally solved.

**Comment by vncoelho** [comment]
Hopefully, aehuaheuahuea
We still need some further design for strong Integration Tests and Consensus Automatic Analyses, this is one of the priorities of the NeoResearch directions and @igormcoelho has been highlighting and brainstorming the future directions.

**Comment by ixje** [comment]
> And I also think that the node should only keep the connection with nodes who are at about the same height

That would prevent new nodes to sync from 0 because they are too far behind. What I do in `neo-python` is monitor that the block height keeps advancing and otherwise disconnect because they are stuck (and we might become as well).

**Comment by shargon** [comment]
I think that this was fixed, isn't it?

**Comment by ixje** [comment]
@shargon yes and no. This https://github.com/neo-project/neo-cli/pull/338 updated `neo-cli` to the point where `show state` could automatically update the height. However, it is the core that does not (yet?) have a reoccurring task that sends ping/pong messages to actually get the height from its connected nodes. It will also only be able to update the height of nodes >= 2.10.1
