### ISSUE TITLE
Offline sync package for neo-cli does not work

### ISSUE THREAD

**Issue by ksemaev** [neo-project/neo-cli#289]
Followed instruction on https://docs.neo.org/en-us/network/syncblocks.html:
1) Used ubuntu16, ubuntu17 and ubuntu18
2) Used releases 2.9.2, 2.9.3, 2.9.4
3) Downloaded mainnet chain.acc.zip from http://sync.ngd.network/ (currently from https://packet.azureedge.net/neochain/mainnet/full/0-3196233/312F1CAE85529014EF279364286B6015/chain.acc.zip) and put it into unzipped release directory
4) run in the same directory where I put chain.acc.zip ` dotnet neo-cli.dll`

In all the versions of ubuntu with all specified releases I see ```block: 0/0/0  connected: 0  unconnected: 0```
And after some seconds it slowly starts to sync from zero:
```block: 0/38/38  connected: 6  unconnected: 41```

Please tell me if I miss something!

**Comment by jsolman** [comment]
You need the ImportBlocks plugin installed.

**Comment by jsolman** [comment]
Use 2.9.4 and use `install importblocks` and then restart.

**Comment by ksemaev** [comment]
@jsolman TY! Maybe you can update manual https://docs.neo.org/en-us/network/syncblocks.html with that solution ?
