### ISSUE TITLE
neo-cli import key not working (testnet)

### ISSUE THREAD

**Issue by emojamuto** [neo-project/neo-cli#29]
>export key path 

returns error no matter what i do (I do have permissions on the destination folder)
export key without path, works just fine

>import key key
>import key path

return error all the time as well

is there a way to debug the problem with the release binaries? 'error' doesn't give much help...

CLI version 2.1.0.0
Windows 10

**Comment by erikzhang** [comment]
Try this without the directory:
>export key <filename>

**Comment by emojamuto** [comment]
same result Erik
error, no more information

**Comment by erikzhang** [comment]
If you run it in debug mode, you will get more information about the error.

**Comment by emojamuto** [comment]
how do you get into the debug mode? I checked the neo-cli documentation and only managed to execute it as
>dotnet neo-cli.dll /rpc

but I don't get any more information about the error.

Thanks in advance

**Comment by erikzhang** [comment]
>dotnet publish -c Debug
Build a debug version first.

**Comment by emojamuto** [comment]
Works in v2.3.2
Thanks!
