### ISSUE TITLE
Cannot start neo-cli 2.9.4 on linux

### ISSUE THREAD

**Issue by nicolegys** [neo-project/neo-cli#291]
It seems that I failed to start neo-cli-2.9.4 in a screen?

**Comment by nicolegys** [comment]
![image](https://user-images.githubusercontent.com/43694095/51460883-a363ba80-1d97-11e9-8b87-1b92d0343943.png)

**Comment by erikzhang** [comment]
It has been solved in 3f5f08b9f99239aa1e5cc994037a1673591cb308.
