### ISSUE TITLE
block sync stopped at 3260162

### ISSUE THREAD

**Issue by zottirik** [neo-project/neo-cli#292]
![image](https://user-images.githubusercontent.com/13282950/51527301-39a1ea00-1e45-11e9-9283-6dc96b2a8b5a.png)

block: 3260162/3260162/3260162  connected: 7  unconnected: 43
Block sync stopped at 3260162. What can I do?

**Comment by atomlab** [comment]
I have same problem today. Block sync stopped at 3260162.

**Comment by bitcodernull** [comment]
i have two nodes
one node have the same problem

**Comment by Edgegasm** [comment]
Seeing a lot of nodes stuck at this block, so probably another 'spork.' This will be fixed when [#426](https://github.com/neo-project/neo/pull/426) is released, but until then you'll have to re-sync the chain to get around it. 

There's an updated bootstrap at height 3261221 available from http://sync.ngd.network/. 

Download the full offline package, and drop the chain.acc.zip in your neo-cli root folder with the ImportBlocks plugin installed.

**Comment by jsolman** [comment]
Minimally, it needs the commit phase #547

**Comment by vncoelho** [comment]
This has been probably solved by avoiding the expose of CN signatures when crashing or after network delays that could cause view to change.

Commit https://github.com/neo-project/neo/commit/f88c427987791e11387ca23eadb619a5e9fdfff9 probably solved that. Fell free to open it again for further investigation or discussion.
