### ISSUE TITLE
block sync stopped at 3293298

### ISSUE THREAD

**Issue by bitcodernull** [neo-project/neo-cli#294]
my two nodes all stopped at 3293298

**Comment by songrenkun** [comment]
me too,How to solve it？

**Comment by bitcodernull** [comment]
I have to spend a few hours re-importing data

**Comment by i3bitcoin** [comment]
The same here, stuck at 3293298, after the full sync, my node stuck at 2m blocks.
Is there any ETA when will it be fixed? It seems many nodes experiencing the issue.

**Comment by Joter85** [comment]
Same issue. Using latest offline file it is stuck again at block 3260162 

Using offline file with instructions from: https://docs.neo.org/en-us/network/syncblocks.html
don't resolve the problem.

**Comment by vncoelho** [comment]
This has been probably solved by avoiding the expose of CN signatures when crashing or after network delays that could cause view to change.

Commit https://github.com/neo-project/neo/commit/f88c427987791e11387ca23eadb619a5e9fdfff9 probably solved that. Fell free to open it again for further investigation or discussion.
