### ISSUE TITLE
New wallet address generate isssue of neo

### ISSUE THREAD

**Issue by ppsdang** [neo-project/neo-cli#296]
**What we have** 
we have set up own neo node onto our machine. our block is in sync state.
Request API
curl --data-binary '{"jsonrpc":"2.0","id":1,"method":"getnewaddress","params":[]}' -H 'content-type:text/plain;' http://xyz.com:20332 {"jsonrpc":"2.0","id":"","error":{"code":-400,"message":"Access denied"}}
Response 
{"jsonrpc":"2.0","id":"","error":{"code":-400,"message":"Access denied"}}

**Version details - We checked our neo version with following:**
Request API 
URL -- htttp://xyz.com:20332
Request body: {
  "jsonrpc": "2.0",
  "method": "getversion",
  "params": [],
  "id": 1
}
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "port": 20333,
        "nonce": 1380995307,
        "useragent": "/Neo:2.9.4/"
    }
}

How can we fix above issue ?

**Comment by belane** [comment]
Is the wallet already open in the node?

**Comment by shargon** [comment]
Due to unanswered time I close this issue
