### ISSUE TITLE
Non-specific error for JSON-RPC specification

### ISSUE THREAD

**Issue by im-kulikov** [neo-project/neo-cli#297]
This error is reproduced on versions 2.8.0-2.9.1

How to reproduce:

- just use image: cityofzion/neo-privatenet:2.9.1
- make request (for example):
```
## Submit block
curl -X "POST" "http://127.0.0.1:30333/" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -H 'Accept-Encoding: gzip, zlib, deflate, zstd, br' \
     -d $'{
  "jsonrpc": "2.0",
  "method": "sendtoaddress",
  "id": 1,
  "params": []
}'
```
- response:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -2146233086,
    "message": "Index was out of range. Must be non-negative and less than the size of the collection.\nParameter name: index"
  }
}
```

> "Index was out of range. Must be non-negative and less than the size of the collection.\nParameter name: index"

this is a specific for C# exception

The JSON-RPC (https://www.jsonrpc.org/specification#error_object) says that "error codes from and including -32768 to -32000 are reserved for pre-defined errors". In this case, the application itself is providing an specific error. I think that if no param is given, error -32602 should be raised, then.

Message must be something like "Method require params"

**Comment by im-kulikov** [comment]
UPD: The problem is reproduced with any method that requires input parameters

**Comment by im-kulikov** [comment]
I find almost same exeption...

```
## Submit block
curl -X "POST" "http://127.0.0.1:30333/" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -H 'Accept-Encoding: gzip, zlib, deflate, zstd, br' \
     -d $'{
  "jsonrpc": "2.0",
  "method": "getaccountstate",
  "id": 1,
  "params": [
    123
  ]
}'
```

Response:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -2146233033,
    "message": "One of the identified items was in an invalid format."
  }
}
```

**Comment by shargon** [comment]
The error should be more descriptive

**Comment by im-kulikov** [comment]
@shargon yep.. but not C# exception..

**Comment by im-kulikov** [comment]
> "Index was out of range. Must be non-negative and less than the size of the collection.\nParameter name: index"

and 

> "One of the identified items was in an invalid format."

is C#  System Exceptions..

I just propose to catch them and give the correct error message and code, according to the specification JSON-RPC

**Comment by im-kulikov** [comment]
@shargon or you are talking about something else?

**Comment by shargon** [comment]
I agree with you

**Comment by im-kulikov** [comment]
The first problem is that the presence of an index in the array is not checked. This generates an exception that no one else handles.

The second problem is caused by the fact that there is no conversion error handling.

**Comment by im-kulikov** [comment]
I make PR to solve that issue https://github.com/neo-project/neo/pull/587
