### ISSUE TITLE
ApplicationLog folder not syncing in neo 2.9.4

### ISSUE THREAD

**Issue by ramisra** [neo-project/neo-cli#298]
After downloading the plugin for application log which is compatible with 2.9.4 its not syncing the NEP-5 logs.

**Comment by ramisra** [comment]
@erikzhang how this can be solved ?

**Comment by vncoelho** [comment]
Hi @ramisra, please check out the most recent versions.
I believe it is working normally.

I will leave this issue closed, but fell free to reopen.
