### ISSUE TITLE
Wallet synchronization stops at v 2.9.4

### ISSUE THREAD

**Issue by okayu8** [neo-project/neo-cli#299]
I attempted to synchronize the block using neo-cli's v 2.9.4, but it stopped at around 2,100,000. (Currently 2,321,692)
So when I synchronized using the Import Block plugin and offline package, I could synchronize up to the latest block.
However, if we tried to synchronize the wallet afterwards, it stopped at around 2,100,000.

The following is the state of synchronization of the current block
2, 116, 136/2, 321, 692/2, 321, 692

Please let me know why this occurred, ascertain the cause.

**Comment by skashitam** [comment]
I am having the same problem.

I am using NeoCli 2.9.4.
I used bootstrap to synchronize with the main net.

After synchronization with the main net is completed, I opened a wallet using the "wallet open" command.
After synchronizing the opened wallet, the index of Wallet stopped at 707.
What could be the cause of Wallet sync stopped?

**Comment by vncoelho** [comment]
I think that this has been probably solved. Several distinct minor improvements happened since 2.9.4.
Fell free to reopen if you still find any similar issue.
