### ISSUE TITLE
export blocks missing from help message

### ISSUE THREAD

**Issue by coranos** [neo-project/neo-cli#3]
help lists the folowing Wallet Commands:
...
	export key [address] [path]
	import key <wif|path>

but the source includes:
	export block [path]
	import block [path]

**Comment by erikzhang** [comment]
There isn't an "import block" command in the code. I will add the help message for "export block".

**Comment by erikzhang** [comment]
Resolved in a63d82634c57fdf172ed9508d1c197e66247a92c
