### ISSUE TITLE
GetRawTransaction RPC method, second argument works wrong

### ISSUE THREAD

**Issue by im-kulikov** [neo-project/neo-cli#300]
https://github.com/neo-project/neo/blob/master/neo/Network/RPC/RpcServer.cs#L320
```csharp
bool verbose = _params.Count >= 2 && _params[1].AsBooleanOrDefault(false);
```

- 0, "0", false - converts to False
- whatever - converts to True

Is it correct?

**Comment by im-kulikov** [comment]
I think we should comply with the documentation and issue an error when passing an incorrect value.

- False - empty parameter or 0/false/“0”/“false”
- True - for 1/“1”/true/“true”

Other values should raise error

**Comment by im-kulikov** [comment]
This is can be reproduced even on the latest version

**Comment by erikzhang** [comment]
JSON (JavaScript Object Notation) is a lightweight data-interchange format. It is based on a subset of the JavaScript Programming Language.

In JavaScript, any `string` converted to a `boolean` is `true`, except for an empty `string`.

**Comment by im-kulikov** [comment]
@erikzhang yes, but in documentation we have:
- 0 or empty to disable verbose
- 1 - to enable

I see that the documentation does not show the actual code behavior

**Comment by im-kulikov** [comment]
In more strongly typed languages, we get an error, such as in Go.. this introduces some inconsistencies with the implementation on C#

**Comment by im-kulikov** [comment]
Perhaps a more correct behavior would be to follow the documentation, do you think?

**Comment by im-kulikov** [comment]
> Verbose: Optional, the default value of verbose is 0. When verbose is 0, the serialized information of the block is returned, represented by a hexadecimal string. If you need to get detailed information, you will need to use the SDK for deserialization. When verbose is 1, detailed information of the corresponding block in Json format string, is returned.


<img width="738" alt="image" src="https://user-images.githubusercontent.com/888650/52916434-7d76fa80-32f0-11e9-9d22-7ed77e16235a.png">

from documentation

**Comment by AlexVanin** [comment]
Isn’t `AsBooleanOrDefault` function parse `whatever` values as default (`False` in this case)?

**Comment by im-kulikov** [comment]
Unfortunately, the behavior in the code is defined differently.

**Comment by erikzhang** [comment]
For a valid json object, the following values will be converted to `false`: `0`, `-0`, `null`, `false`, `NaN`, `""` (empty string). All other objects will be converted to `true`.

**Comment by AlexVanin** [comment]
I think @im-kulikov wanted to stress that documentation suggest to use `int` values (`0` or `1`). So passing non-suggested types (`strings`, etc.) should lead to the error or `incorrect arguments` answer . This would be more convenient for implementations in languages with strong typing (like `go`).

**Comment by im-kulikov** [comment]
@AlexVanin yeah.. thanks

**Comment by shargon** [comment]
I think that the problem was solved
