### ISSUE TITLE
The release "neo-cli-win-x64.zip" can't run on Windows Server

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-cli#302]
![image](https://user-images.githubusercontent.com/6295602/53384938-9c901f00-39b7-11e9-953d-02d99445cf1d.png)

The release "neo-cli-win-x64.zip" can't run on Windows Server The investigation found that the same release could run on Windows 10, but it would make an error when running on Windows Server.

A temporary fix is to copy the libleveldb.dll of the neo-gui and replace it with the original libleveldb.dll.
The libleveldb.dll copied from the neo-gui can also run on Windows 10. 

So I suggest that the file "neo-cli-win-x64.zip" should contain the libleveldb.dll from the neo-gui

Similar issue links: https://github.com/neo-project/neo-cli/issues/198 https://github.com/neo-project/neo-cli/issues/276

从 GitHub release 中下载的压缩包 "neo-cli-win-x64.zip" 不能在 Windows Server 上直接运行，但是可以在 Windows 10 下运行。

有个临时的解决办法，就是把 neo-gui 的 libleveldb.dll 复制过来，替换掉原本的 libleveldb.dll 就可以正常运行了。这个版本的 libleveldb.dll 也可以在 Windows 10 上运行。

所以我建议 "neo-cli-win-x64.zip" 中应该包含 neo-gui 中的 libleveldb.dll。

**Comment by vncoelho** [comment]
Is this still a problem, @chenzhitong?
Should we replace the release, @erikzhang?
Maybe this issue can just be closed...

**Comment by shargon** [comment]
Closed because there are no response since more than a month
