### ISSUE TITLE
2.9.4 Calculation of the extra charge for transactions over 1024 bytes

### ISSUE THREAD

**Issue by QingmingZi** [neo-project/neo-cli#303]
If a transaction of more than 1024 bytes requires an additional network fee, then I (possibly) need to add additional GAS UTXO to the transaction, and adding the UTXO process increases the size of the transaction body, which seems to be an unpredictable number of rounds. Iterative function?
It may feel that the efficiency is very expensive, and it may increase a large delay (continue trials until the network fee changes do not cause the transaction length to change)

**Comment by QingmingZi** [comment]
After testing, about every additional UTXO plus 34bytes in length, we need to add another 0.0034GAS UTXO input. If the input is not enough to pay for this 0.0034GAS, it will cause a new round of trading structure. It can be imagined that if UTXO is less than 0.01 GAS, it will be difficult to construct a legal transaction body.

**Comment by lightszero** [comment]
I think we should pay for script and txouput, but except txinput

**Comment by igormcoelho** [comment]
Another solution here is to join input transactions in larger outputs... however, this assumes that the "join" transaction is below 1024 bytes. Is it the case?

**Comment by lock9** [comment]
Hello,
What is the current state of this issue?
Is it needed for neo 3?

**Comment by lock9** [comment]
I will have to close this due to inactivity 😢 
I think this won't be added to NEO 2.
@neo-project/core  I'm closing this, but if you guys think this is doable in NEO 2, please reopen this issue.
