### ISSUE TITLE
Compatability with Neo 2.9.5

### ISSUE THREAD

**Issue by AlexVanin** [neo-project/neo-cli#308]
With new upcoming Neo 2.9.5 version there is some compatibility issues with stable neo-cli repository. 2.9.5 is missing `OpenWallet` function at [neo/Network/RPC/RpcServer.cs](https://github.com/neo-project/neo/blob/master/neo/Network/RPC/RpcServer.cs) which is used in [neo-cli](https://github.com/neo-project/neo-cli/blob/master/neo-cli/Shell/MainService.cs#L498):

```c#
                case ".db3":
                    {
                        . . .
                        system.RpcServer?.OpenWallet(Program.Wallet);
                    }
                    break;
                case ".json":
                    {
                        . . .
                        system.RpcServer?.OpenWallet(Program.Wallet);
                    }
```

It also missing `GetMemoryPool` function at [neo/Ledger/Blockchain.cs](https://github.com/neo-project/neo/blob/master/neo/Ledger/Blockchain.cs) which is used in [neo-cli](https://github.com/neo-project/neo-cli/blob/master/neo-cli/Shell/MainService.cs#L1003)

```c#
        private bool OnShowPoolCommand(string[] args)
        {
            bool verbose = args.Length >= 3 && args[2] == "verbose";
            Transaction[] transactions = Blockchain.Singleton.GetMemoryPool().ToArray();
            if (verbose)
                foreach (Transaction tx in transactions)
                    Console.WriteLine($"{tx.Hash} {tx.GetType().Name}");
            Console.WriteLine($"total: {transactions.Length}");
            return true;
        }
```

I guess neo-cli should be updated with all new upcoming changes.

**Comment by im-kulikov** [comment]
@AlexVanin it was removed in this [commit](https://github.com/neo-project/neo/commit/1c29deea18f81f09a37574180a77288e5dfc9831#diff-e92f98cf1d59aa5795d2db95facf225c)

**Comment by im-kulikov** [comment]
`GetMemoryPool` was removed in this [commit](https://github.com/neo-project/neo/commit/5222283c9f718217d550ca789a32c383d17749d3#diff-b95eb330cd65618c912779c81831051eL221) 

> jsolman committed on Jan 13

**Comment by erikzhang** [comment]
You need to wait for the 2.9.5 release.

**Comment by vncoelho** [comment]
The version will probably be 2.10.0.
