### ISSUE TITLE
What about daemon launching?

### ISSUE THREAD

**Issue by dartkinselok** [neo-project/neo-cli#31]
We need to launch NEO node as daemon for accessing it using rpc at any time. How can i do this? Thanks.

**Comment by erikzhang** [comment]
screen ./neo-cli /rpc

**Comment by dartkinselok** [comment]
@erikzhang thank you! one more question. What about RPC commands like `create wallet` or get new address? Thanks in advance:)

**Comment by erikzhang** [comment]
There is no RPC command for creating wallet.
You can find all RPC commands at http://docs.neo.org/en-us/node/api.html

**Comment by rad-p** [comment]
@erikzhang 
I start neo node with 
dotnet /path/to/neo-cli.dll

but wat is that screen command?

**Comment by dartkinselok** [comment]
@rad-p you should use it like `screen dotnet /path/to/neo-cli.dll` . Then if you'll close console it will still be running.

**Comment by purplesoft-io** [comment]
Hello to all,
I've edited neo-cli command line parser to allow wallet unlock before start rpc service.
this is the pull request link: #151
and this is my forked branched repo: https://github.com/purplesoft-io/neo-cli/tree/neo-cli-daemon-with-wallet-unlock

usage:
dotnet neo-cli.dll --rpcwallet "/home/user/walletpath/wallet.db3" "W4LL3tP4sSw0rD 01"
dotnet neo-cli.dll --rpcwallet "/home/user/walletpath/wallet.json" "W4LL3tP4sSw0rD 01"

tiziano@purplesoft.io

Donations are welcome XD we are developing NEO WEB PANEL MANAGER for NEO NODES (also private deploy of NEO blockchain).
NEO: AYUd4G2dNXAEyUxkZGyMdXAnJ396jJfNDz
ETC: 0x982e45402ad06d0a01f3e54732b28c76d9870422
BTC: 1HxdgF6WsvcRVNiXhz6jZgbD9eopvzAxap
ETH: 0x5cb3784e71710f681410d30d615a3b3bb3c24ff1

**Comment by kizzx2** [comment]
Oneliner with Docker with auto-restart:

```
docker run --name neo-cli -id --restart=unless-stopped -p 10332:10332 kizzx2/neo-cli
```

**Comment by zhag** [comment]
Ohhh.. Looks like I found the way to demonize this shit...
You should use supervisord

> [program:neo]
directory=/home/neo/neo-cli
command=/usr/bin/dotnet /home/neo/neo-cli/neo-cli.dll --rpc
stdout_logfile=/var/log/neo.log
autostart=true
autorestart=true
user=neo
stopsignal=KILL
numprocs=1


Do not forget to enable supervisor on startup `systemctl enable supervisord`
