### ISSUE TITLE
How to get 'scriptHash' from 'deploy' ?

### ISSUE THREAD

**Issue by georgearchon** [neo-project/neo-cli#312]
When I deploy an *.avm to the testnet using neo-cli, the output is:
```
VM State: HALT, BREAK
Gas Consumed: 100
Evaluation Stack: [{"type":"InteropInterface"}]

Signed and relayed transaction with hash=0x<some hash value>
```
I understand that `<some hash value>` is the txid. But I need the scripthash of the contract.
How are they related?
If the txid is not the scripthash, how do I get the scripthash using neo-cli?
(I'm trying to avoid using the gui since I intend to program against the neo-cli and /rpc so please don't suggest the gui)
When I make a `getcontractstate` call using the /rpc of neo-cli with `<some hash value>` it returns an error:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-2146233033,"message":"One of the identified items was in an invalid format."}}
```
My /rpc call looks like:
```
curl -v -d '{"jsonrpc": "2.0","method": "getcontractstate","params": ["<some hash value>"],"id": 1}' http://127.0.0.1:20332
```

I tested `getcontractstate` using script hash from examples in Neo's docs and the output is valid. But when I make the above call with `<some hash value>` I am having no success. I see that the length of `<some hash value>` is different from the script hashes I see in the examples. 
Thanks in advance for your help.

**Comment by jsolman** [comment]
When you compile with it should create an `*abi.json` file that contains the contract script hash.

**Comment by georgearchon** [comment]
@jsolman that is it! Thank you! I was incorrectly using the txid where I should have been using scriptHash!!

**Comment by igormcoelho** [comment]
@georgearchon you can also import .avm file on neocompiler.io and you will automatically get its scripthash (even without deploy).

**Comment by jsolman** [comment]
Maybe I should
