### ISSUE TITLE
deploy with storage<-true but `getcontractstate` gives `"storage":false`

### ISSUE THREAD

**Issue by georgearchon** [neo-project/neo-cli#314]
As the title says, deploying using neo-cli with:
`deploy path/tofile.avm 0710 01 True True True nameOfContract 0.0.1 "Myname Smith" "myname@domain.com" "a great description" `

But when I run: 
`curl -v -d '{"jsonrpc": "2.0","method": "getcontractstate","params": ["<scripthash>",1],"id": 1}' http://127.0.0.1:20332`
it returns:
`{"jsonrpc":"2.0","id":1,"result":{"version":0,"hash":"<scripthash>","script":"<script>","parameters":["Void"],"returntype":"Boolean","name":"nameOfContract","code_version":"0.0.1","author":"Myname Smith","email":"myname@domain.com","description":"a great description","properties":{"storage":false,"dynamic_invoke":false}}}`

Will the storage boolean take on true value once Storage.Put(...) is successfully ran within the contract?

**Comment by georgearchon** [comment]
I found the problem.
I dug into the source and there is a bug on lines 160:162 of neo-cli/neo-cli/Shell/MainServices.cs
Changing the "true" to "True" in each respective line (then recompiling neo-cli) fixed the problem in that I successfully deployed my contract to testnet with storage:true.

I suspect the issue is that the parser of neo-cli was written elsewhere to expect string(s) "True" but was written on lines 160:162 of neo-cli/neo-cli/Shell/MainServices.cs to expect string(s) "true".

**Comment by jsolman** [comment]
This had already been fixed recently
https://github.com/neo-project/neo-cli/pull/307

**Comment by vncoelho** [comment]
Anyway, it was a nice catch, George, good debugging you did.

**Comment by georgearchon** [comment]
Thanks! I just did a fresh pull from neo-cli in case other things have been
improved in the last couple of days.
George
