### ISSUE TITLE
Cancel the limit of free gas when using "invoke", "invokefunction", "invokescript" rpc

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-cli#318]
When using "invokescript " rpc for big smart contract invoking, it seems because of the free gas limit, the response always returns "Fault Break". Since these kinds of rpc is just for invoking using on local, I think this limit is better to be canceled.

**Comment by vncoelho** [comment]
Hi @superboyiii, maybe it can generate RPC vulnarabilities issues, we need to design with carefull.
