### ISSUE TITLE
Neo CLI not syncing for 2 days

### ISSUE THREAD

**Issue by signalsfrombob** [neo-project/neo-cli#32]
Worked perfectly for a week, now sync is zero, height is 0/0
NEO coin balance shows zero although NEOScan shows I still have the coins
How to sync the wallet?
Thank you

**Comment by erikzhang** [comment]
Which client did you use?

**Comment by signalsfrombob** [comment]
https://neowallet.cn/
I cannot find a version number.
Now it is syncing, but still displays zero coins

**Comment by erikzhang** [comment]
So you should ask neowallet.cn for support. :)

**Comment by signalsfrombob** [comment]
Confusing. But thanks

**Comment by signalsfrombob** [comment]
I understand Peter Lin is the developer. Perhaps you can suggest how to contact? I can find no support channel.

**Comment by erikzhang** [comment]
@PeterLinX

**Comment by signalsfrombob** [comment]
Thank you
