### ISSUE TITLE
[Question/feature] Automatic settings load for neo-cli

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-cli#321]
@shargon, sometime ago I remember that you implemented an automatic load of plugin settings, right? If the parameter of the config is modified the client automatic reloads it, right?

However, testing https://github.com/neo-project/neo-cli/pull/319 I noticed that it is not valid for neo-cli config.
Do you think that it is worth to do?

**Comment by shargon** [comment]
i will take a look

**Comment by shargon** [comment]
With plugins is easier because the classes are smaller, we have this "environment" controlled in one (or few) class. The problem with the global config is that there are a lot of instances using this configuration, we can do it, but i think that is not needed, what do you think?

**Comment by vncoelho** [comment]
I think it is not as well. I will close this.
