### ISSUE TITLE
balance rpc call broke in 2.10

### ISSUE THREAD

**Issue by jens-j** [neo-project/neo-cli#325]
After upgrading to neo-cli 2.10 the "getbalance"  RPC method does not work for me anymore.
When I switch back to 2.9.4 it does work as expected.

request:
{"params": ["602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7"], "jsonrpc": "2.0", "method": "getbalance", "id": 1}

response:
{'jsonrpc': '2.0', 'error': {'message': 'Method not found', 'code': -32601}, 'id': 1}

**Comment by jsolman** [comment]
The wallet methods were moved to a plugin.

**Comment by erikzhang** [comment]
You need to install this plugin: https://github.com/neo-project/neo-plugins/tree/master/RpcWallet

**Comment by igormcoelho** [comment]
@jens-j besides the official Neo documentation, the list of available RPC commands can also be found on Network section (draft) of Community Yellow Paper: https://github.com/NeoResearch/yellowpaper/blob/master/sections/02_Network.md

**Comment by jens-j** [comment]
Thanks for the help! I have it working again.
