### ISSUE TITLE
Akka expection cause the stick while exit neo-cli-2.10.0

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-cli#328]
When exiting neo-cli-2.10.0, there's a high percent that could show Akka expection which could cause the stick for almost 20 seconds and nothing could be input.

![image](https://user-images.githubusercontent.com/38493437/54656819-1cfef700-4b02-11e9-81fa-43cb50f886b2.png)

**Comment by jsolman** [comment]
The akka exception is not the cause of the hang.

**Comment by superboyiii** [comment]
Yes, it's just a phenomenon.

**Comment by shargon** [comment]
duplicated with https://github.com/neo-project/neo-cli/issues/317
