### ISSUE TITLE
GAS unavailable in a private chain instance

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-cli#331]
Running a private chain on my local machine, running neo-cli 2.10.0.0. Successfully transferred the genesis NEO to a standard wallet via `send neo <address> all` while having one of the private chain wallets open (and signing the request with two other private chain wallets and relaying). I was able to successfully transfer the GAS that had accumulated in the multisig acount to the same standard account via `claim gas all <address>` (plus signing and relay). When I open the standard wallet and `list asset`, I see 1,000,00,000 NEO and the 58 GAS that accumulated in the multisig account before I transferred the NEO to the standard wallet. So far, so good.

However, when I run `show gas` with the standard wallet open, the new GAS this wallet is receiving is listed as unavailable. The amount of unavailable GAS goes up with every block written to the private chain, but it doesn't transfer over to be available. Running `claim gas` returns `no gas to claim`.

Is there a step that I'm missing? I don't have enough GAS to experiment with deploying contracts in my private chain and I don't understand why the GAS I'm accruing is not available.

**Comment by devhawk** [comment]
I figured out a work around. I opened the standard wallet that contained all the NEO to and resent all the NEO again to myself - that is I executed `send neo <address> all` again, with the standard wallet open and using the standard wallet's address. After that, `show gas` shows zero unavailable and available GAS until the next block is written on the blockchain. Then, all the GAS that was previously unavailable was listed as available and I could claim it. 

New GAS continues to accrue as "unavailable" in this account. I am able to repeat the workaround of transferring all my NEO to myself to make the GAS available. 

It appears the behavior of making GAS available after a transfer is by design, according to the [FAQ](https://docs.neo.org/en-us/faq.html)

> **What is GAS？How to acquire GAS？**
> GAS represents the right to use the Neo Blockchain. NEO network charges GAS for the new assets issuance as well as for smart contract running and storage. In the genesis block GAS is 0 and it is generated as new blocks generate. Once NEO is acquired, GAS is generated in the system following the algorithms. GAS has two status, available and unavailable. Once NEO is spent (i.e. transferred out) from the account, the relevant GAS turns to available. NEO holders can initiate a claim transaction at any time to claim available GAS to the NEO address.

> **Can I transfer GAS to my own account to make it claimable?**
> Yes. You can do that even if there is just one address in your wallet.

As per the FAQ, I tried `send gas <address> all` as well. However, while the send appears to succeed (neo-cli returns a TXID when I do the GAS transfer just like it did when I did the NEO transfer), `show gas` still listed my available GAS as zero.

**Comment by erikzhang** [comment]
https://docs.neo.org/en-us/network/private-chain/private-chain.html

Please check this doc.

**Comment by devhawk** [comment]
I reviewed that doc as well as the [NGD Quickstart](https://github.com/neo-ngd/NEO-Tutorial/blob/master/neo_docs_SmartContract_QuickStart/SmartContract_quickstart_en.md#setting-up-a-private-chain). Neither doc addresses how to claim unavailable GAS

**Comment by erikzhang** [comment]
NEO uses a UTXO system. Since you own neo, you will get gas. Only when a UTXO is spent, the accumulated gas will become available. So you need to send you neo to an address first.

**Comment by devhawk** [comment]
Is there a repo tracking documentation issues? This seems like something the private-chain doc specified above should include.

**Comment by erikzhang** [comment]
https://github.com/neo-project/docs

**Comment by devhawk** [comment]
thanks. I will open an issue over there

**Comment by vncoelho** [comment]
@devhawk, I will leave it closed.
If you find any problem fell free to keep in touch.
