### ISSUE TITLE
It is recommended to add the getAddressFromScriptHash method.

### ISSUE THREAD

**Issue by QingmingZi** [neo-project/neo-cli#332]
The address parameter output of the contract notify is in the form of ScriptHash, which is difficult to convert to an address. But what Dapp needs more is the address, not ScriptHash.

**Comment by erikzhang** [comment]
Why dapp needs address instead of ScriptHash?

**Comment by QingmingZi** [comment]
For example, I need to get the owner information of an NNS. The owner information returned by invokescript is Scritphash, and the user needs to look at Address. At this time, if I don't convert, I can't display the information that the user can understand.

**Comment by erikzhang** [comment]
You can convert it in wallet or client. You don't need to convert it in dapp. To convert a script hash to an address, you can use a SDK.

**Comment by QingmingZi** [comment]
ok
