### ISSUE TITLE
Neo-cli stopped updating with testnet blockchain

### ISSUE THREAD

**Issue by georgearchon** [neo-project/neo-cli#333]
I've been using neo-cli an an /rpc node for my project. Unfortunately it is no longer updating itself to the current state of the testnet blockchain.  My node is stuck at 2478758 but the testnet height is around 2480920. 
My node is not recognizing the current block height but is displaying:
```
block: 0/2478758/2478758  connected: 14  unconnected: 0                         
  ip: 47.52.159.228     port: 20333     listen: 20333   height: 2478758                                                                                         
  ip: 47.254.128.17     port: 20333     listen: 20333   height: 2478758                                                                                         
  ip: 47.254.43.764     port: 20333     listen: 20333   height: 2478758                                                                                         
  ip: 47.97.73.2017     port: 20333     listen: 20333   height: 2480906                                                                                         
  ip: 47.89.188.179	port: 20333	listen: 20333	height: 2478758                   
  ip: 47.254.44.88	port: 20333	listen: 20333	height: 2480906                    
  ip: 47.105.64.71	port: 20333	listen: 20333	height: 2480906                    
  ip: 47.254.28.42      port: 20333     listen: 20333   height: 2480906                                                                                         
  ip: 47.91.248.98      port: 20333     listen: 20333   height: 2478758                                                                                         
  ip: 101.132.33.44     port: 20333     listen: 20333   height: 2478030                                                                                         
  ip: 47.91.225.117     port: 20333     listen: 20333   height: 2478758                                                                                         
  ip: 47.254.38.194	port: 20333	listen: 20333	height: 2478758                   
  ip: 47.254.83.14	port: 20333	listen: 20333	height: 2478758                    
  ip: 47.52.168.73	port: 20333	listen: 20333	height: 2478758 
```
Thanks in advance for your help.

From the printout above, it appears other peers are stuck as well.

**Comment by georgearchon** [comment]
This appears to be a recurring issue with both the test net and the main net in that I've seen many threads on this issue. The other threads I have read suggest downloading an archive of the blockchain with height greater than the "bad" block. Unfortunately I have not been able to locate an archive of the testnet blockchain newer than 8/20/2018 https://github.com/CityOfZion/awesome-neo#blockchain-bootstrap-files
I've also done a full resynce (takes about 2 days) and still my node is stuck on this block.

Does anyone know of a source where I can download a more recent archive of the Neo testnet blockchain with height above this bad block (block 2478758)?

Thanks for your help.

**Comment by georgearchon** [comment]
Completed a full resync (took about 2 days) and got past the bad block. But now at block 2508816 and have reached another bad block.
Is there any other option aside from doing a full resync?
Here is the printout of `show state`
```
block: 2508816/2508816/2508816  connected: 13  unconnected: 0                   
  ip: 47.89.253.82	port: 20333	listen: 20333	height: 2517913                    
  ip: 47.91.248.98	port: 20333	listen: 20333	height: 2517913                    
  ip: 47.105.64.71	port: 20333	listen: 20333	height: 2517913                    
  ip: 47.91.225.117	port: 20333	listen: 20333	height: 2517913                   
  ip: 47.89.188.179	port: 20333	listen: 20333	height: 2508816                   
  ip: 47.254.44.88	port: 20333	listen: 20333	height: 2517913                    
  ip: 47.254.43.76	port: 20333	listen: 20333	height: 2517912                    
  ip: 47.254.128.17	port: 20333	listen: 20333	height: 2517912                   
  ip: 47.52.168.73	port: 20333	listen: 20333	height: 2517912                    
  ip: 47.97.73.20	port: 20333	listen: 20333	height: 2517913                     
  ip: 47.254.38.194	port: 20333	listen: 20333	height: 2508816                   
  ip: 101.132.33.44	port: 20333	listen: 20333	height: 2517913                   
  ip: 47.254.28.42	port: 20333	listen: 20333	height: 2517913           
```

**Comment by vncoelho** [comment]
Hi @georgearchon, did you use the bootstrap package available at https://sync.ngd.network/ ?

Which version did you use? There were some improvements and a minor fix on client 2.10.1. It would be nice if you could try again with the last version and last import plugin.

**Comment by georgearchon** [comment]
I have been using client v 2.10.1

I realized I missed the toggle button from mainnet/testnet on 
https://sync.ngd.network/ when I reviewed it with https://docs.neo.org/en-us/network/syncblocks.html.
So now I see a full resync is available for download. 
Downloading the above will get my client past this block. Thank you.

**Comment by georgearchon** [comment]
@vncoelho 
I've downloaded the bootstrap package `chain.acc.zip` and have `importBlocks` plugin installed on neo-cli 2.10.1.

Is there documentation on using `importBlocks` with a downloaded bootstrap package?

**Comment by vncoelho** [comment]
on importBlocks has just one additional parameter for debugging and stopping on a given height, but not so much usefull anymore.
Thus, it will be basically just move the .dll to the neocli.

**Comment by georgearchon** [comment]
I'm not following what you just wrote. Maybe my question was formed with a misunderstanding that `importBlocks` is relevant to the scenario of using `chain.acc.zip` with `neo-cli`.

I'll reform my question: Given `chain.acc.zip` and `neo-cli`, how do I run `neo-cli` using the data from `chain.acc.zip`?

The doc https://docs.neo.org/en-us/network/syncblocks.html shows importing `chain.acc.zip` using `neo-gui` but not a full explanation on doing so with `neo-cli`.

**Comment by vncoelho** [comment]
Just copy it to the same root folder and it will load on startup.

Use show state to check if it is going as expected or check the Chain folder.

**Comment by georgearchon** [comment]
I copied both `chain.acc.zip` and (for good measure) `chain.acc` into the root where I'm running the `neo-cli /rpc` process. I'm using "show state" and it appears the node is syncing from the beginning without any noticeable effect from `chain.acc*`. @vncoelho

**Comment by vncoelho** [comment]
Make sure you followed all steps of the docs, it includes neo-cli.

**Comment by georgearchon** [comment]
I resolved the issue of syncing using bootstrap package and "importBlocks" plugin.
Before I explain, I will note I'm surprised that the original issue of nodes getting stuck on bad blocks is not considered a bug. The bulk of this thread is getting through a workaround of something that seems broken.

Now how I got through the syncing issue: The reason the syncing using bootstrap package and "importBlocks" plugin was not working on my system is because the neo-cli `install <plugin>` saves the plugin to the root of where the process is called, but neo-cli includes the plugin in runtime by requiring it be in the same dir as the executable `neon-cli.dll`.

Like with most installations of applications to my (Linux) system, I exported the location of the executable by appending to my `.bashrc`

```
#-- NEO-CLI ENVIRONMENT VARIABLES START --#

export NEOCLI_HOME=/home/mylaptop/neo/neo-cli/neo-cli/bin/Release/netcoreapp2.1/linux-x64
export PATH=$PATH:$NEOCLI_HOME/

#-- NEO-CLI ENVIRONMENT VARIABLES END --#
```
and have been working with neo-cli by calling `neo-cli /rpc` from within a project folder `~/myproject`

**Comment by vncoelho** [comment]
Thanks for this report, @georgearchon. I am happy that you accomplished what you were searching for  and found this relevant insight.

@shargon, what do you think?

**Comment by georgearchon** [comment]
https://github.com/neo-project/neo-cli/issues/342

**Comment by shargon** [comment]
Maybe we can try to find the file in both folders

**Comment by shargon** [comment]
I think that is the expected behaiviour, if you call the program with other path it takes the local files from this path, however, we could try to search and install in the binary path instead of the working directory

**Comment by vncoelho** [comment]
@georgearchon, I think that this is solved if you use the offline package available at https://sync.ngd.network/

If you find any problem fell free to reopen.
