### ISSUE TITLE
block sync stopped at 3552409

### ISSUE THREAD

**Issue by zottirik** [neo-project/neo-cli#335]
block sync stopped at 3552409
what can i do?

**Comment by kokahunter** [comment]
You can download an incremental offline package and let neo-cli sync the blocks via `ImportBlocks` plugin. 

Guidance: https://docs.neo.org/en-us/network/syncblocks.html

**Comment by vncoelho** [comment]
@zottirik, if you encounter any problem fell free to re-open.
