### ISSUE TITLE
The extra fee calculation makes the multisig function couldn't show incompleted json for signature

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-cli#347]
The extra fee calculation makes the multisig function couldn't show incompleted json for signature.
There's no judgement whether signature is completed now before the calculation for the extra gas. However, even that is done, the size of witness seems difficult for calculation so that it makes the calculation of tx.szie more complex.

**Comment by superboyiii** [comment]
@jsolman @erikzhang @shargon

**Comment by superboyiii** [comment]
If witness isn't completed, it returns error straightly. But for the calculation of tx.size, Getwitness[] is necessary.
![image](https://user-images.githubusercontent.com/38493437/56481815-77211c80-64f3-11e9-8394-0811a2484ca2.png)

**Comment by shargon** [comment]
You have problems using `ToJson` ? could you show me when do you get this exception?

**Comment by superboyiii** [comment]
I've already fixed it. But not a perfect choice.
