### ISSUE TITLE
[2.10.1]invokefunction rpc execution failure

### ISSUE THREAD

**Issue by fl0wjacky** [neo-project/neo-cli#348]
POST
`{
  "jsonrpc": "2.0",
  "method": "invokefunction",
  "params": [
    "2830fc346b1c7a350914fbaea5ef7b3fbe3c994c",
    "decimals"
  ],
  "id": 3
}`

neo-cli 2.9.4 response:
`{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "00c108646563696d616c73674c993cbe3f7befa5aefb1409357a1c6b34fc3028",
        "state": "HALT, BREAK",
        "gas_consumed": "0.184",
        "stack": [
            {
                "type": "Integer",
                "value": "8"
            }
        ]
    }
}`

neo-cli 2.10.1 response:
`{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "00c108646563696d616c73674c993cbe3f7befa5aefb1409357a1c6b34fc3028",
        "state": "HALT",
        "gas_consumed": "0.15",
        "stack": [
            {
                "type": "ByteArray",
                "value": "646563696d616c73"
            }
        ],
        "tx": "d1012000c108646563696d616c73674c993cbe3f7befa5aefb1409357a1c6b34fc3028000000000000000000000000"
    }
}`

**Comment by shargon** [comment]
We are trying to find the issue

**Comment by shargon** [comment]
Fixed on https://github.com/neo-project/neo-vm/pull/126 and https://github.com/neo-project/neo-vm/pull/140

**Comment by superboyiii** [comment]
Already been solved. @fl0wjacky
