### ISSUE TITLE
linux 64 version

### ISSUE THREAD

**Issue by frb1972** [neo-project/neo-cli#36]
Seems like download is windows files. Many .dll files and reference to MS and no .deb?

**Comment by pctripsesp** [comment]
**It would be nice, but you need to use Windows .NET instead.**

**DO:**
`sudo apt-get install libleveldb-dev sqlite3 libsqlite3-dev`

Then follow https://www.microsoft.com/net/download/linux to install dotnet in Linux. For Ubuntu 16.04 is:
`curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg`

`sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg`

`sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-xenial-prod xenial main" > /etc/apt/sources.list.d/dotnetdev.list'`

`sudo apt-get update && sudo apt-get install dotnet-sdk-2.0.0`

**Now you can go to neo-cli folder and open a Terminal there and do:**
`dotnet neo-cli.dll`

![seleccion_192](https://user-images.githubusercontent.com/17095580/30926382-34c740fe-a3b5-11e7-86b1-028d6d688230.png)
