### ISSUE TITLE
After syncing up to "3773043", no more blocks are updated.

### ISSUE THREAD

**Issue by skashitam** [neo-project/neo-cli#365]
I am using neo-cli v2.10.1 with windows10.

I was syncing the mainnet.

Currently the latest block is "3775444",
After syncing up to "3773043", no more blocks are updated.

What causes the block to stop syncing?
The capacity of my PC is enough.

**Comment by erikzhang** [comment]
Because currently dBFT 2.0 is not deployed on the MainNet. There is a bug in the old dBFT implementation that leads to a forked block on the MainNet. You may need to resync the blocks this time. The dBFT 2.0 will be deployed next month, so this problem will not happen again.

**Comment by olizax** [comment]
same problem here.
Are there any better solutions than resync the whole blocks?

**Comment by skashitam** [comment]
@erikzhang 
Thank you for reply.

Does it mean that I need to delete and resynchronize my chain data?

I used the offline sync package.
https://sync.ngd.network/

"Full Offline Package" is uploaded on 5/18,
When syncing, does the same problem occur as long as this package is used?

**Comment by erikzhang** [comment]
There is currently no other way than resync.

**Comment by skashitam** [comment]
@erikzhang 
Thank you!
I will try Block Resync!

**Comment by i3bitcoin** [comment]
@erikzhang
I already tried to resync from scratch using the latest release v2.10.2, but again stuck at 3773043.
Is there another solution available?

**Comment by umeku** [comment]
@i3bitcoin 
Have you used offline package and ImportBlocks plugin to resync?

I've had success with v2.10.2 and offline package from https://sync.ngd.network/.

**Comment by i3bitcoin** [comment]
@umeku

Ah, sorry, syncing from offline package now.
Thanks for the reply.

**Comment by pdkproitf** [comment]
I got the same problem, block sync stuck at 3773043/3773043/3773043
