### ISSUE TITLE
Error when uninstalling the plugin CoreMetrics

### ISSUE THREAD

**Issue by nicolegys** [neo-project/neo-cli#366]
It will return an error when uninstalling CoreMetrics. Because CoreMetrics only has a .dll file, no folder.
<img width="239" alt="1" src="https://user-images.githubusercontent.com/43694095/58066181-d9387480-7bba-11e9-8b16-4365fad3461d.png">
<img width="252" alt="2" src="https://user-images.githubusercontent.com/43694095/58066252-1b61b600-7bbb-11e9-87ac-8cd9d6f183f0.png">
<img width="321" alt="3" src="https://user-images.githubusercontent.com/43694095/58066379-b22e7280-7bbb-11e9-9d50-d9f413425545.png">
neo-cli version: 2.10.2

**Comment by shargon** [comment]
We should release all plugins with the same structure.

**Comment by vncoelho** [comment]
Is there something to change on this plugin, @shargon?

**Comment by shargon** [comment]
I reviewed the zip, and at least the last version is like other plugins.

**Comment by shargon** [comment]
Done
