### ISSUE TITLE
Explicit message on plugin install

### ISSUE THREAD

**Issue by vladyslavstartsev** [neo-project/neo-cli#367]
Hi! I've notice that there is an error in you cli code. What was wrong is I was using old `config.json`
which was without `"PluginURL"`. So when I did `install ImportBlocks` in `neo-cli` I have have `error` 

```text
neo> plugins
Loaded plugins:
	ImportBlocks
neo> install ImportBlocks
error
neo> install ApplicationLogs
error
neo> install RpcWallet
error

```

What I think this should be is `error: no "PluginURL" found please provide one in config.json`

**Comment by shargon** [comment]
Could you try with the last one?

**Comment by vladyslavstartsev** [comment]
@shargon  I have the latest version of neo-cli

**Comment by vladyslavstartsev** [comment]
also I noticed that when I've added the `"PluginURL": "https://github.com/neo-project/neo-plugins/releases/download/v{1}/{0}.zip"` it downloaded the package, I've restarted the neo-cli, after that if didn't show the package.
I've `cd` to `Plugins` folder and it unpacked it wrong way.

What it did is downloaded the plugin (for example, `RpcWallet`) and unzipped it into the Plugins. but the path is wrong, because it looks like this
`neo-dlls-root/Plugins/RpcWallet/Plugins/` and inside of that it shows the `RpcWallet` folder and `RpcWallet.dll`

it should unpack  the right way `neo-dlls-root/Plugins/RpcWallet` folder and `neo-dlls-root/Plugins/RpcWallet.dll`

**Comment by shargon** [comment]
>What it did is downloaded the plugin (for example, RpcWallet) and unzipped it into the Plugins. but the path is wrong, because it looks like this
neo-dlls-root/Plugins/RpcWallet/Plugins/ and inside of that it shows the RpcWallet folder and RpcWallet.dll

Your second problem is fixed, but is not in the last release

**Comment by vladyslavstartsev** [comment]
@shargon can the first one be solved?

**Comment by shargon** [comment]
Fixed
