### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x8007001F

### ISSUE THREAD

**Issue by jwdongcn** [neo-project/neo-cli#38]
Permanent crash when start neo-cli
error message: Failed to initialize CoreCLR, HRESULT: 0x8007001F
version: Neo CLI v2.3.2
os: centos 7

**Comment by jwdongcn** [comment]
It can be solved by change owner of file neo-cli to root

**Comment by anlucoliv** [comment]
I changed owner of file neo-cli to root but not worked.

error: Failed to initialize CoreCLR, HRESULT: 0x80131500
release: https://github.com/neo-project/neo-cli/releases/download/v2.3.2/neo-cli-ubuntu.16.04-x64.zip
dotnet version: 2.0.0
my OS: ubuntu 17.04 x64

**Comment by erikzhang** [comment]
```chmod u+x neo-cli```
