### ISSUE TITLE
Running patch to change LevelDB wrapper on Mac fails.

### ISSUE THREAD

**Issue by okayu8** [neo-project/neo-cli#383]
I tried to run Neo-Cli on Mac according to the following URL.
https://docs.neo.org/en-us/node/cli/publish.html#setting-up-neo-cli-on-macos

However, if a patch for changing the LevelDB wrapper in the "Project code settings" item is executed using the following command, an error will occur.

`git apply 0001-convert-leveldb-to-rocksdb.patch`

```error: patch failed: neo/IO/Data/LevelDB/Native.cs:4
error: neo/IO/Data/LevelDB/Native.cs: patch does not apply
error: neo/IO/Data/LevelDB/NativeRocksDB.cs: already exists in working directory```

Why does this happen?
The Neo-Core version is v2.9.4 and Neo-Cli uses v2.9.4.

**Comment by lock9** [comment]
Hello @okayu8, maybe you already applied the patch? I used a fresh copy and followed the tutorial:
```BASH
$ git apply 0001-convert-leveldb-to-rocksdb.patch
0001-convert-leveldb-to-rocksdb.patch:590: trailing whitespace.
        #region extensions 
0001-convert-leveldb-to-rocksdb.patch:737: trailing whitespace.
        #region Cache 
warning: 2 lines add whitespace errors.```

**Comment by ixje** [comment]
As @lock9 said, it looks like you already applied it. Alternatively you can set the following environment variable and still use LevelDB
```
DYLD_INSERT_LIBRARIES=/usr/local/lib/libtcmalloc.dylib
```
You will get some warnings, but the `src/tcmalloc.cc:331] Attempt to free invalid pointer 0x7f83cb954a00` error will no longer be there and the storage will work just fine. Choose your flavour

**Comment by okayu8** [comment]
@ixje 
Thank you for the reply.
I tried this, but I got an error about 'ContainerPlaceholder' at build time.
That is a separate question.
Thank you.
