### ISSUE TITLE
Did you mean to run dotnet SDK commands? Please install dotnet SDK from?

### ISSUE THREAD

**Issue by prettyCoders** [neo-project/neo-cli#394]
![image](https://user-images.githubusercontent.com/36216120/59735750-815c5e80-9289-11e9-961e-3af16c1d1850.png)

**Comment by erikzhang** [comment]
```
./neo-cli
```

**Comment by igormcoelho** [comment]
`dotnet restore` only works on project level (where you can find a "project" .sln or .csproj).

**Comment by cloud8little** [comment]
@prettyCoders see if this could help. https://forums.asp.net/t/2138127.aspx?Ubuntu+16+04+dotnet+installed+but+not+working+
> Re: Ubuntu 16.04 dotnet installed but not working.
> Mar 26, 2018 03:13 PM|LINK
> 
> Did you install just the Runtime or whole SDK?  Sounds like you just installed the Runtime..
> 
> See the following link:
> 
>   https://www.microsoft.com/net/download/linux-package-manager/ubuntu16-04/sdk-2.1.101
