### ISSUE TITLE
neo-cli stops sync per several days and works again after restarting.

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-cli#401]
Neo-cli-2.10.2 stopped sync per several days and worked again after restarting. Seems the CPU utilization is almost 100%. After restarting, the CPU utilization went down immediately. Here's a curve diagram for this phenomenon.
![image](https://user-images.githubusercontent.com/38493437/60026607-6dbc5800-96ce-11e9-9154-be6eb45fb04e.png)

**Comment by vncoelho** [comment]
That is true, @superboyiii, sometime happen and just come back syncing after restart.

I believe it still can have relationship with `TaskManager`.

I just took a look and realized that, in fact, PR #644 modified the leak on `ProtocolHandler`.
What do you think, @shargon and @erikzhang.

Maybe we should modify https://github.com/neo-project/neo/blob/1e2c6c67795eed64c9266ec4292621f58a99e44f/neo/Network/P2P/TaskManager.cs#L27 to `FIFOSet` as well and limit its capacity.

### possible way to test
Create a command on neo-cli that cleans this vector.
After the node "stopping syncing" use this command to clean the tasks and see the result.

**Comment by lock9** [comment]
Hi guys,
I will close this issue since it is a duplicate like Vitor already mentioned. 
This is an issue with neo itself, not neo-cli.

Feel free to reopen this issue if you think this was a mistake. Thanks.
