### ISSUE TITLE
How to make neo-cli more verbose

### ISSUE THREAD

**Issue by ksemaev** [neo-project/neo-cli#402]
Hi! Please advice - is there a way to get some logs from neo-cli? Right now it just starts and there's no information on what's going on there. Maybe there's some cli option that I couldn't find?

**Comment by ksemaev** [comment]
@erikzhang it is very needed, as sometimes neo-cli just hangs, and there's no info in logs to check what happened.

**Comment by lock9** [comment]
Hi @ksemaev  did you try the ApplicationLogs plugin? It is not "the best" logging tool, but it does help.

**Comment by ksemaev** [comment]
@lock9 cam you please explain how ApplicationLogs plugin works? Should I pass `--log` or `--logs`? Where would the logs be outputed to?

**Comment by lock9** [comment]
Hello @ksemaev , I believe it is '--log'. It is output is in ApplicationLogs folder, inside neo-cli executable folder.
There is more information here:
https://github.com/neo-project/neo-plugins

@ksemaev  once you try it, can you give us some feedback to know if this solved your problem?

**Comment by ksemaev** [comment]
@lock9 when I installed logs plugin with:
```
wget -q https://github.com/neo-project/neo-plugins/releases/download/$VERSION/ApplicationLogs.zip && \
unzip -o ApplicationLogs.zip -d /home/neo
```
And tried to start neo-cli with `neo-cli  --rpc --log` I get:

> neo> [ERROR][07/18/2019 05:59:34][Thread 0010][akka://NeoSystem/system/IO-TCP/$a] Monitored actor [[akka://NeoSystem/user/$b#2050724388]] terminated
> Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#2050724388]] terminated
>    at Akka.Actor.ActorBase.Unhandled(Object message)
>    at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
>    at Akka.Actor.ActorCell.ReceiveMessage(Object message)
>    at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
>    at Akka.Actor.ActorCell.Invoke(Envelope envelope)
> 

Still there's not much help for me from logs in filesystem, I need them to be passed to stdout.
