### ISSUE TITLE
It takes long time to generate tx id when sending all assets with many utxos per address

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-cli#405]
Background:
Prepare a wallet, 1001 addresses with 1 utxo(neo) per address
Version:  2.10.2
Scenario: 
1. dotnet neo-cli.dll
2. open this wallet
3. send all 1000 neo to another address

It takes about 8 minutes until TXID generated. Not sure how the number of utxos affect the performance, but 8 minutes for 1000 utxos is a bit too long.

![3581562222450_ pic](https://user-images.githubusercontent.com/34291844/60645130-7baa6f80-9e6a-11e9-981a-e6b02806afa4.jpg)
![3591562222459_ pic](https://user-images.githubusercontent.com/34291844/60645135-7e0cc980-9e6a-11e9-91e8-97f44e8f9497.jpg)
![3601562222532_ pic](https://user-images.githubusercontent.com/34291844/60645142-806f2380-9e6a-11e9-94b3-9c48a419d74e.jpg)

**Comment by Ashuaidehao** [comment]
Hi @cloud8little , migrating your wallet from NEP6(.json) to SqlLite(.db3) could solve your problem. When open a NEP6 wallet, it loads all your private key enctyped with Scrypt algorithm. The private key will not decrypt until when you use it for signature first time. 
On this account ,your first transaction will cause 1000 decrypt operation with the time-consuming Scrypt algorithm.
The SqlLite wallet stores private key with AES algorithm, and can hardly block with the decrypt operation .

**Comment by cloud8little** [comment]
@Ashuaidehao Thanks, i will have a try.

**Comment by lock9** [comment]
Hello,
I will close this issue. If you consider this a mistake, please create a new one or reach me in discord to reopen it.
NEO 3 won't have UTXO, so no need to worry about this in the future.
