### ISSUE TITLE
为什么私链的共识钱包NEO会被自动转走

### ISSUE THREAD

**Issue by boy-good** [neo-project/neo-cli#406]
私链共识钱包里的NEO会被自动转走到地址：ASnwQJTjhjYcFS7aJstzrZ5tFqho1AQHEJ

目前不清楚什么原因，数额太大导致的？

**Comment by boy-good** [comment]
![image](https://user-images.githubusercontent.com/39320533/61125625-e435c400-a4dc-11e9-8b99-1b4d50d4faa2.png)

像这几笔都不是我发起的交易，不知道哪里发起的交易，转入了我上面说的那个地址

**Comment by boy-good** [comment]
![image](https://user-images.githubusercontent.com/39320533/61125691-15ae8f80-a4dd-11e9-84f9-bd5e9e689554.png)

**Comment by Ashuaidehao** [comment]
你的私链有对外开放Rpc端口吗？

**Comment by boy-good** [comment]
> 你的私链有对外开放Rpc端口吗？

有，我设置为0.0.0.0 具体原因还不清楚是什么导致的。

**Comment by Ashuaidehao** [comment]
你的私链是只给自己用还是公开ip的？开放rpc端口的话任何人都可以调用“send”开头的rpc方法将你钱包里的neo转走，建议把共识钱包里的neo全部转到你本地的另一个钱包里，确保节点钱包里没有neo，这样会比较安全。

**Comment by boy-good** [comment]
> 你的私链是只给自己用还是公开ip的？开放rpc端口的话任何人都可以调用“send”开头的rpc方法将你钱包里的neo转走，建议把共识钱包里的neo全部转到你本地的另一个钱包里，确保节点钱包里没有neo，这样会比较安全。

只有自己用的，用来测试钱包。但我把neo转到共识钱包的另一个地址就不会被转走，只有在共识公钥对应的地址才会出现这种情况。

**Comment by Ashuaidehao** [comment]
自己用的话最好把共识节点的rpc端口设置为只对你自己的ip开放，或者装上RpcSecurity插件强制每次rpc请求都要输入账号密码（https://github.com/neo-project/neo-plugins/releases）。
如果这样还有问题的话，建议检查下你的测试代码，看看是不是哪里不小心调用了转账接口转到了ASnwQJTjhjYcFS7aJstzrZ5tFqho1AQHEJ地址上。

**Comment by boy-good** [comment]
> 自己用的话最好把共识节点的rpc端口设置为只对你自己的ip开放，或者装上RpcSecurity插件强制每次rpc请求都要输入账号密码（[https://github.com/neo-project/neo-plugins/releases）。](https://github.com/neo-project/neo-plugins/releases%EF%BC%89%E3%80%82)
> 如果这样还有问题的话，建议检查下你的测试代码，看看是不是哪里不小心调用了转账接口转到了ASnwQJTjhjYcFS7aJstzrZ5tFqho1AQHEJ地址上。

RpcSecurity 这个插件怎么用的呀，正需要这种可以设置账户密码的，像btc那样设置rpcuser这样会安全点

**Comment by boy-good** [comment]
NEO有开发者微信群嘛？

**Comment by Tommo-L** [comment]
@boy-good  有的，加我微信，拉你入群 wx: luch_jinming

**Comment by Tommo-L** [comment]
@boy-good  亲，我们可以关闭这个issue了吗，目前看更多是安全问题。另外欢迎到 “NEO开发者群“ 来交流。

**Comment by boy-good** [comment]
> @boy-good 亲，我们可以关闭这个issue了吗，目前看更多是安全问题。另外欢迎到 “NEO开发者群“ 来交流。

好的，可以关闭。感谢感谢
