### ISSUE TITLE
After playing with Application Logs filter neo-cli stopped to work

### ISSUE THREAD

**Issue by ksemaev** [neo-project/neo-cli#409]
Was trying to make it more verbose with https://github.com/neo-project/neo-cli/issues/402

And now I'm catching this on every start with `neo-cli --rpc`:

> neo> [ERROR][07/18/2019 05:59:34][Thread 0010][akka://NeoSystem/system/IO-TCP/$a] Monitored actor [[akka://NeoSystem/user/$b#2050724388]] terminated
> Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://NeoSystem/user/$b#2050724388]] terminated
> at Akka.Actor.ActorBase.Unhandled(Object message)
> at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
> at Akka.Actor.ActorCell.ReceiveMessage(Object message)
> at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
> at Akka.Actor.ActorCell.Invoke(Envelope envelope)

Please advice - maybe something needs to be cleaned up?

**Comment by vncoelho** [comment]
Perhaps cleaned up in local folder, right? Because you are restarting the application completely, right?

Let us know the problem because it may be something worth to push.

**Comment by ksemaev** [comment]
@vncoelho Not sure what to clean. I just added the application logs, and than removed it. So not sure what to clean up. But I will try to remove everything except chain from persistent volume now.

**Comment by ksemaev** [comment]
It was TTY issue, sorry for troubles, fixed it with custom TTY options
