### ISSUE TITLE
Please fix Ubuntu 17, can't run.

### ISSUE THREAD

**Issue by sgehrman** [neo-project/neo-cli#41]
tried to run, but I have Ubuntu 17.

$ dotnet ./neo-cli.dll .
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.1' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.1.1'.

**Comment by erikzhang** [comment]
You need to install .NET Core 1.1

**Comment by sgehrman** [comment]
Could you provide instructions on installing .NET Core 1.1?
Microsoft makes things so complex I was unable to figure it out.  Thanks.  I'm on the latest Ubuntu.

**Comment by AlberTajuelo** [comment]
Hi @sgehrman 

Here it is the installation guide for .NET Core 1.1.1:
https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.1-download.md

**Comment by metachris** [comment]
Here are the docs: https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-download.md#installing-net-core-on-linux

Basically, just add the repos as described in the docs, and then run 

    sudo apt-get update
    sudo apt-get install dotnet-sdk-2.0.0


You can also take a look at how we do it in the Docker image, which is based on Ubuntu: https://github.com/CityOfZion/neo-privatenet-docker/blob/master/Dockerfile#L26

**Comment by metachris** [comment]
I think this issue can be closed, as there are several reproducible setup guides for Ubuntu.
