### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by lock9** [neo-project/neo-cli#412]
We need to fix Travis before we can continue adding PRs to this repository.

**Comment by shargon** [comment]
The problem is with the nuget

**Comment by lock9** [comment]
@shargon  who can solve it? Do you know?

**Comment by shargon** [comment]
I think that @erikzhang need to publish an updated nuget version for neo3

**Comment by erikzhang** [comment]
I have no idea. The problem is that we are unable to delete several packages that were uploaded incorrectly.

**Comment by shargon** [comment]
Maybe we can create a new one with the name Neo3 instead of Neo?

**Comment by erikzhang** [comment]
I have sent an email to the nuget administrator asking to delete those packages, but I have not received a response.

**Comment by Ashuaidehao** [comment]
It looks like when build in docker,it didn't copy the "Nuget.Config" file to build directory. So the "myget" source doesn't work at all. Add "COPY NuGet.Config /opt" after this line(https://github.com/neo-project/neo-cli/blob/master/ci/Dockerfile#L21) may resolve the problem.

**Comment by erikzhang** [comment]
Now that the nuget package can be restored normally, we only need to fix the test.

**Comment by lock9** [comment]
Guys, Travis is working fine. I'm closing this.
