### ISSUE TITLE
Switch network command

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo-cli#413]
Is that possible to add a new command to switch the CLI network between main and test? It bothers when I have to change the content of the config file manually to switch the network.

**Comment by vncoelho** [comment]
Sounds plausible and good, we would probably need to kill actors and restart the node with a pre-defined config and protocol that is already specific for each network.

**Comment by shargon** [comment]
I don't like it, is bad for human errors because you mustn't never use the same wallet for testnet and mainnet, and this make this kind of errors more easy. Is something totally different and is well to keep it totally isolated.

**Comment by Liaojinghui** [comment]
Might be other solutions way better than directly deal with the config files, right?

**Comment by vncoelho** [comment]
I was coming to remove enhancement...aheuahueaea

**Comment by shargon** [comment]
maybe we should be able to call neo-cli with `- - testnet` or ` - - mainnet` maybe this is easier and doesn't require to change the files

**Comment by Liaojinghui** [comment]
Yes!! Yes!! Please!!!

**Comment by lock9** [comment]
Hello @Liaojinghui ! I will close this since #415 was merged, ok?
Please leave a comment if you think I should reopen it.
Thanks!
