### ISSUE TITLE
'show gas' shows 0 gas, but the address should have 393 gas

### ISSUE THREAD

**Issue by itsmeknt** [neo-project/neo-cli#431]
I am having trouble with the 'show gas' command displaying proper gas. My address as stated in the neoscan shows 393 gas. When I do 'list assets' I get this output:

id:0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7
name:NeoGas
balance:393.49592856
confirmed:393.49592856

But when I do 'show gas' I get this output:

unavailable: 0
available: 0

My wallet address is:

AUJviCUutCSNvAJzhk3y93RyaXAJzaH2j9      Standard

and the neoscan shows that I have 393 gas:

https://neoscan-testnet.io/address/AUJviCUutCSNvAJzhk3y93RyaXAJzaH2j9

Is this normal behavior? This account is unable to send transactions, and I believe it is because my neo client thinks it has 0 gas.

I am using the neo testnet, and I syncronized the blockchain starting from the archived block that I got here: https://sync.ngd.network/

Let me know how I can make 'show gas' show the 393 gas that I have. Thank you.

**Comment by superboyiii** [comment]
Hi, itsmeknt. ```Show gas``` is used to show the gas amount for claim, not for showing balance. If you'd like to show balance,```list asset``` is for this usage.

**Comment by lock9** [comment]
Hello,
I`m closing this due to a lack of activity. Feel free to recreate this issue if you still have problems.
Thanks,
