### ISSUE TITLE
Update the maketransaction call to be compatible with change in neo

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-cli#435]
the change of neo(https://github.com/neo-project/neo/pull/968) is incompatible with neo-cli. (neo-project/neo-cli#414)
because the implementation of maketransaction changed:
https://github.com/neo-project/neo/pull/968/files#diff-3f891451d2176ac40781e3bde8ad50c2L272

![1101565686482_ pic_hd](https://user-images.githubusercontent.com/34291844/62934702-c8814e80-bdf7-11e9-84ca-c71b3785ca65.jpg)

**Comment by igormcoelho** [comment]
It would be strange if it didnt break neocli :joy:
I must be easy to fix.

**Comment by vncoelho** [comment]
@belane, it looks like that PR #440  did not resolve it completely, still getting this error here: 

```cs
Shell/MainService.cs(152,59): error CS1503: Argument 2: cannot convert from 'byte[]' to 'Neo.UInt160' [/opt/neoCli/neo-cli/neo-cli.csproj]
Shell/MainService.cs(208,59): error CS1503: Argument 2: cannot convert from 'byte[]' to 'Neo.UInt160' 
```
