### ISSUE TITLE
Where can I find the change log for v2.10.3?

### ISSUE THREAD

**Issue by yanpl** [neo-project/neo-cli#447]
Where can I find the change log for v2.10.3?

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-cli/blob/master-2.x/CHANGELOG.md

**Comment by yanpl** [comment]
Is v2.10.3 mandatory update?
If exchange update to v2.10.3, what should the exchange do?

**Comment by yanpl** [comment]
@erikzhang

**Comment by erikzhang** [comment]
It's not mandatory.

**Comment by lock9** [comment]
Hi guys, 
This question seems to be solved. If you need something else @yanpl, please add a commend or contact me directly on Discord. Thanks
