### ISSUE TITLE
如何加载插件

### ISSUE THREAD

**Issue by DingGeng-GitHub** [neo-project/neo-cli#457]
neo> install RpcWallet
Downloading from https://github.com/neo-project/neo-plugins/releases/download/v2.10.1/RpcWallet.zip
Install successful, please restart neo-cli.

![image](https://user-images.githubusercontent.com/39077274/64165893-87211380-ce78-11e9-9de6-67bd9ae948be.png)

neo> uninstall RpcWallet
Plugin not found

我成功安装了插件，为什么说插件没找到？

**Comment by cloud8little** [comment]
需要重启(restart)之后uninstall.

**Comment by DingGeng-GitHub** [comment]
@cloud8little 您好，退出控制台后再进去卸载也提示没找到，但实际插件是存在的

**Comment by cloud8little** [comment]
能提供一下你的操作过程么？比如在哪里下载的版本，做过哪些命令操作

**Comment by DingGeng-GitHub** [comment]
系统：Ubuntu16.04

安装：
~# apt-get update && apt-get upgrade -y
~# apt-get install libleveldb-dev sqlite3 libsqlite3-dev libunwind8-dev git -y
~# git clone https://github.com/neo-project/neo-cli.git
~# wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
~# dpkg -i packages-microsoft-prod.deb
~# apt-get install apt-transport-https
~# apt-get update
~# apt-get install aspnetcore-runtime-2.2 -y
~# apt-get install dotnet-sdk-2.2 -y
~# cd neo-cli
~# dotnet restore
~# dotnet publish -c Release


// 启动：
~# /root/neo-cli/neo-cli/bin/Release/netcoreapp2.1/linux-x64/publish/neo-cli
NEO-CLI Version: 2.10.1
neo>install ImportBlocks
Downloading from https://github.com/neo-project/neo-plugins/releases/download/v2.10.1/ImportBlocks.zip
Install successful, please restart neo-cli.
neo> exit

// 重新启动
~# /root/neo-cli/neo-cli/bin/Release/netcoreapp2.1/linux-x64/publish/neo-cli
NEO-CLI Version: 2.10.1
neo> plugins
No loaded plugins

**Comment by cloud8little** [comment]
@DingGeng-GitHub 首先现在从Git上下载的源代码属于NEO3的源代码，其默认的version2.10.1 并不是release版本中的2.10.1，如果需要对应的插件，需要下载neo-plugins仓库，进行编译。如果直接使用2.10.1 release版本的plugins可能会导致问题；另外，建议加上最新的neo进行编译。

**Comment by DingGeng-GitHub** [comment]
@cloud8little 加载插件的问题解决了，
neo> plugins
Loaded plugins:
	ApplicationLogs
	ImportBlocks


再请教个问题，为什么同步不了区块？
neo> show state
![image](https://user-images.githubusercontent.com/39077274/64237281-9f536a00-cf2e-11e9-908b-962b99f4d939.png)

**Comment by cloud8little** [comment]
请参考https://docs.neo.org/docs/zh-cn/network/private-chain/private-chain2.html 搭建私链，目前neo3的版本还没有主网版本，另外，由于这个问题已经解决了，我将关掉这个issue，谢谢

**Comment by DingGeng-GitHub** [comment]
@cloud8little 为什么下载tag为2.0.1版本报错：
![image](https://user-images.githubusercontent.com/39077274/64240075-e3953900-cf33-11e9-93b9-8cb6deb1a5c7.png)
启动时报以下错误：
![image](https://user-images.githubusercontent.com/39077274/64240106-f576dc00-cf33-11e9-8d0b-49a24e81da98.png)

**Comment by cloud8little** [comment]
![d449b840f00830b0d9424cfca26135b](https://user-images.githubusercontent.com/34291844/64259820-616d3a80-cf5c-11e9-963f-ea9a42e6b0eb.png)
