### ISSUE TITLE
neo-cli run fail

### ISSUE THREAD

**Issue by DingGeng-GitHub** [neo-project/neo-cli#458]
systemctl:Ubuntu16.04

Excuse me, why the error?
![image](https://user-images.githubusercontent.com/39077274/64313742-3aa41800-cfdf-11e9-9893-e4df8082188f.png)

**Comment by shargon** [comment]
We must release plugins too

**Comment by DingGeng-GitHub** [comment]
@shargon The plug-in problem has been resolved. Why do the following errors occur as soon as you enter neo-cli

![image](https://user-images.githubusercontent.com/39077274/64328781-aa76ca80-d000-11e9-8e6d-ad31bca2d367.png)

**Comment by superboyiii** [comment]
@DingGeng-GitHub It's because that the max connection number of some seed nodes is full at that time. It will find any free connection, but need some time. I think it'll connnect suceesfully after 1 minute.
