### ISSUE TITLE
CLI Wallet and RPC API Questions

### ISSUE THREAD

**Issue by Crypto2** [neo-project/neo-cli#46]
I have a couple of questions about the CLI wallet. I have looked at the docs but don't see the answers.

1. What is the proper way to back up a wallet? I've seen mention of importing a WIF key but don't see a way to get this key for a CLI wallet.

2. How to set a password for the RPC server?

3. How to view incoming transactions for the wallet, I don't see a listtransactions or listsinceblock API call or anything?

**Comment by erikzhang** [comment]
1. To backup a wallet, you just need to copy the .db3 file to a safe place. If you want to export the private keys, use "export key" command: `export key [address] [path]`.
1. You can't set a password for the PRC server. To protect your wallet from RPC, you need to setup the whitelist of firewall.
1. There is no such API in CLI currently. Maybe we will add them later.

**Comment by Crypto2** [comment]
1. Do I need to worry about the wallet running while copying the file, or is it fine to leave it running (since it could be mid-write and corrupt if you tried to reload it)? Since I definitely don't want to have to restart it a few times a day since you have to enter the password manually.

2. At least it is easy to parse the blockchain :)

**Comment by erikzhang** [comment]
You can copy the .db3 file while the node is running. Don't worry about it.
