### ISSUE TITLE
Add addresses to List from opened wallet when adding witnees without inputing utxo

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-cli#460]
Now in neo-cli-2.10.3 the initial fee is removed in invoking sc. This could bring an issue that for example: As we all know, if an nep-5 contract wants to invoke ```deploy``` method, it needs to add an UTXO input so that it could add witness to pass ```Checkwitness``` in sc to ensure the deploy invoking guy is the owner. Now since we removed initial fee in neo-cli, we're not able to invoke ```deploy``` method when the sc is not larger than 1024 bytes beacuse witness isn't able to be added. So maybe we should add addresses to List from opened wallet when adding witness without inputing utxo.

**Comment by shargon** [comment]
Could you provide me the steps for reproduce the issue?

**Comment by superboyiii** [comment]
@shargon Try to deploy a nep-5 contract in neo-cli-2.10.3 and then invoke ```deploy``` function. This tx will fail since witness isn't able to be added for owner.

**Comment by superboyiii** [comment]
Oops, tested, it works on deploy. Close now.
