### ISSUE TITLE
Invalid ip format on connected in neo-cli

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-cli#473]
Invalid ip format on ```connected``` in neo-cli. Sometimes there will display an additional number on the end of ip.
![image](https://user-images.githubusercontent.com/38493437/66808518-ff8df080-ef5d-11e9-9aa0-b647ffc36463.png)

**Comment by shargon** [comment]
Strange ... Any idea about how we can reproduce it? testnet, mainnet?

**Comment by superboyiii** [comment]
@shargon Run a node, mainet or testnet, ```show state``` after running for several hours.

**Comment by superboyiii** [comment]
We find the actual ip for this is 54.196.33.248, but I'm confused why it sometimes random an additional number at the end if run for some hours.

**Comment by shargon** [comment]
This is worst xD

![image](https://user-images.githubusercontent.com/3167973/66943094-c4b5b680-f04a-11e9-8f9a-68a1022ece93.png)

**Comment by shargon** [comment]
![image](https://user-images.githubusercontent.com/3167973/66943200-eadb5680-f04a-11e9-9c3c-f357a00d6c2f.png)

Is something related to print, i will check it

**Comment by shargon** [comment]
@superboyiii take a look to https://github.com/neo-project/neo-cli/pull/474

**Comment by superboyiii** [comment]
Let me test it.
