### ISSUE TITLE
Update to dotnet 3.0

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-cli#478]
I think that we should move all the projects to the last dotnet version. Here you can see a summary of the changes.

Changes:

https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0
Benchmarks

https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-core-3-0

Fix: https://github.com/neo-project/neo-cli/pull/477

**Comment by vncoelho** [comment]
Agreed, It is a good time for that.
