### ISSUE TITLE
run in background

### ISSUE THREAD

**Issue by 97zgxgw** [neo-project/neo-cli#48]
Hello.
We prepare install neo for exchange, how run in background and unlock wallet ?

**Comment by rakeshiitd** [comment]
Yes I want to know the same. Nohup is not working for neo-cli

**Comment by erikzhang** [comment]
screen -S neo ./neo-cli /rpc

**Comment by skinderis** [comment]
@erikzhang but it is not running in background, I can't close the terminal when i run `screen -S neo ./neo-cli --rpc`. When I close terminal process is terminating.
