### ISSUE TITLE
Windows adding RPC

### ISSUE THREAD

**Issue by MaffeProg** [neo-project/neo-cli#49]
I read all issues if I could find anything about this error:

`neo> dotnet neo-cli.dll /rpc`
`error`

It just give back an error in windows. Nothing else. Does anyone have a solution or is there an error log somewhere?

Added: Or is this not needed in windows to do this? And/or do I have to run a fully in sync wallet in order to use rpc or to get access to rpc? Because currently I try to reach it trough my browser and that doesn't work.

**Comment by erikzhang** [comment]
You need to add `/rpc` when you start neo-cli:
```
dotnet neo-cli.dll /rpc
```
Not in the neo-cli itself:
```
neo>
```

**Comment by MaffeProg** [comment]
I figured it out like this:
`"C:\Program Files\neo-cli\neo-cli.exe" /rpc`
