### ISSUE TITLE
Assets not listing ubuntu 16.04, neo-cli v2.3.5

### ISSUE THREAD

**Issue by crebbo** [neo-project/neo-cli#50]
Possibly i'm not understanding correctly, but I'm not seeing my NEO appear when using `list asset`

I setup my wallet before all blocks had synced, and sent some NEOs to my address. After the wallet appears to have been synced:

```
neo> show state
Height: 1526873/1526873, Nodes: 5
```
running `list asset` doesn't provide any feed back, unlike `show gas`
```
neo> list asset
neo> show gas
unavailable: 0
  available: 0
```
I would at least expect `list asset` to provide some feedback, even if it was a 0 value. I've checked neotracker.io and can see details of my transaction, have sent to the correct address but it's just not reflecting in my wallet.

I've yet to try previous versions of the cli. I can't see what I am missing from the documentation.

Running neo-cli: v2.3.5, (neo-cli-ubuntu.16.04-x64.zip) on 16.04

Thanks

**Comment by khandelwaldeval** [comment]
Same with me. Neotracker.io shows I have a balance of 1 NEO. But list asset shows blank even when all blocks are updated

**Comment by byenary** [comment]
Same here, after like a week it did show the assets
But now I tried exporting en importing key in another vm and there it is not showing the balance again...
In the original vm which has the same address there it still shows the assets, funky behaviour...

**Comment by crebbo** [comment]
I did try the graphical neon-wallet by CityOfZion and that instantly showed my balance.

Slightly concerning that this doesn't work/lack of community that this appears to go relatively unnoticed. The cli documentation is also hard to make sense of

**Comment by byenary** [comment]
![image](https://user-images.githubusercontent.com/7538477/32521603-683c350a-c414-11e7-837a-ab5540f20538.png)
Two screenshots, the avove is the original which after days suddenly started showing the asset, the other one the same address was created using export key and import key.
show state shows the second one is synced later in the chain and still not showing... the transaction which filled the address is also already there since 26 oktober.....

**Comment by erikzhang** [comment]
Rebuild index for the imported wallet:
```
rebuild index
```
And wait for 15~30 minutes. Then you can list your assets:
```
list asset
```

**Comment by byenary** [comment]
Nope tried that... and tried it again, does not change a thing

**Comment by byenary** [comment]
maybe relevant, when I do exit I get segmentation fault core dumped.

**Comment by hahahatrick** [comment]
I'm facing the same issue. I send 1 neo and its not showing up in the wallet.

show state
Height: 971938/1413523/1623605, Nodes: 4

Ran rebuild index too,  no luck.

**Comment by ailionx** [comment]
Why this is closed? Didn't see a solution and I still have this issue.

**Comment by enVolt** [comment]
This shouldn't be closed. 

Is there any extra step, that we're missing?

**Comment by enVolt** [comment]
Hey, sorry for the false alarm. So my RPC port was open to public. I was using CoZ test net (and their faucet) to test all of this. Later when I checked their testnet, as soon as I was getting the coins, it was getting transferred within 30-40 seconds.

Most probably, some bot was transferring my money to a different address via RPC (my wallet was open on cli).

**Comment by byenary** [comment]
No idea why it got closed, maybe they did not care about the cli wallet..
Well I moved to a gui client... #fail

**Comment by erikzhang** [comment]
>Hey, sorry for the false alarm. So my RPC port was open to public. I was using CoZ test net (and their faucet) to test all of this. Later when I checked their testnet, as soon as I was getting the coins, it was getting transferred within 30-40 seconds.
Most probably, some bot was transferring my money to a different address via RPC (my wallet was open on cli).

That's probably it.

**Comment by adityawritso** [comment]
@erikzhang  Can you please tell me, how you have blocked RPC ports for the public? I am also struggling with the same issue.

Thanks in advance.

**Comment by erikzhang** [comment]
firewall

**Comment by erikzhang** [comment]
No, you needn't.
