### ISSUE TITLE
 Does neo support hd wallet？

### ISSUE THREAD

**Issue by zuoshang** [neo-project/neo-cli#52]
In other words， how to sign a tx whose utxos owned by different privatekey?

The signatureData is at the end of the transaction data。Each utxo does not have its own signature data.

thanks.

**Comment by erikzhang** [comment]
https://ledger.zendesk.com/hc/en-us/articles/115005530425-How-to-install-and-use-Neo-NEO-

**Comment by zuoshang** [comment]
thanks

where i can get samples or documents about how to generate signatureData for a transaction whose utxos owned by different privatekeys?

**Comment by erikzhang** [comment]
You can follow the source code:
https://github.com/neo-project/neo-cli/blob/master/neo-cli/Shell/MainService.cs#L607
