### ISSUE TITLE
fund cease issue as punishment to validating node 

### ISSUE THREAD

**Issue by kiahmed** [neo-project/neo-cli#53]
wondering if neo implemented any fund ceasing feathers as punishment like Ethereum Casper is working on to punish the validating node in case of malfunction or abnormality detected? Then what are those conditions ?

**Comment by vncoelho** [comment]
Currently Validation Nodes operates without any of this punishments.

dBFT 2.0 is based on a descentralized multi-agent system with its roots on the pBFT.
Basically functionalities for making such Consensus have been implemented. 
However, the path is open for more sophisticated implementations, if they do not hurt any principle of decentralization.

Thanks for the question and insight. Fell free to reopen.
