### ISSUE TITLE
My neo coins are missing!

### ISSUE THREAD

**Issue by sidhmads** [neo-project/neo-cli#57]
I transferred some neos from one account to another account using the cli..however, it was showing as balance and not confirmed.once I rebuild the index, those neos are missing! On Neo to gas website, it has been transferred to another address and is in the unspent state. 

I double checked when I sent my Neo. Like it was to my another address. Is there anyway to get back my Neo?

**Comment by shargon** [comment]
You have sync your Blockchain?

In neo tracker do you see the same? 
> https://neotracker.io/
