### ISSUE TITLE
Very long time up to current height after restart neo-cli daemon

### ISSUE THREAD

**Issue by sysctl01** [neo-project/neo-cli#58]
After restart neo-cli daemon, status not changing  about 2-3 hours.
```
neo> show state
Height: 1605043/1605043, Nodes: 0
neo> 
```
Tcpdump shows that packages on port 10333 transfer realy rare.
```
tcpdump -n -i eth0 port 10333
```

And after 2-3 hours packages on port 10333 start  transfer more activetly and `show state` show current height.

Why this can happen?

**Comment by erikzhang** [comment]
You can delete the file `peers.dat` and restart it.
