### ISSUE TITLE
How correctly backup wallet with neo-cli daemon?

### ISSUE THREAD

**Issue by sysctl01** [neo-project/neo-cli#59]
I create wallet with command
```
neo> create wallet /home/neo-cli/wallet.dat
password:*****
password:*****
```
If I just copy wallet file to backup folder, that that correct way?  Or wallet file may damaged if on that time I do something operation with wallet?

**Comment by erikzhang** [comment]
Just copy the wallet file to backup folder.

**Comment by sysctl01** [comment]
> Just copy the wallet file to backup folder.
What happen  with wallet backup If at that moment(copy wallet file) creating new address via RPC protocol?

**Comment by metachris** [comment]
If you copy the wallet file, all blocks that have been synced (flushed) to disk will be copied. Theoretically it's possible that you copy the file in the middle of a write-operation, and that might result in a corrupt file. To guard against this, i think you'd have to close the wallet before copying. Perhaps another option is to more regularly backup the wallet, so the chances are even more reduced.

**Comment by erikzhang** [comment]
Now that we recommend using the JSON based NEP-6 wallet files, these files can be easily detected as if the backup was successful.
