### ISSUE TITLE
neo-cli fails to run

### ISSUE THREAD

**Issue by avastmick** [neo-project/neo-cli#64]
System: Windows 10 1709
neo-cli version: 2.4.1

```
dotnet neo-cli.dll --rpc

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libleveldb': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Neo.Implementations.Blockchains.LevelDB.Native.leveldb_options_create()
   at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain..ctor(String path)
   at Neo.Shell.MainService.OnStart(String[] args)
   at Neo.Services.ConsoleServiceBase.Run(String[] args)
   at Neo.Program.Main(String[] args)
```
Is the LevelDB not included, or is missing from this build..?

**Comment by erikzhang** [comment]
The latest version has included it.

**Comment by avastmick** [comment]
Thanks @erikzhang ! But...

```
dotnet neo-cli.dll
Error:
  An assembly specified in the application dependencies manifest (neo-cli.deps.json) was not found:
    package: 'Newtonsoft.Json', version: '10.0.1'
    path: 'lib/netstandard1.3/Newtonsoft.Json.dll'
```

Using the new release (v.2.5.0). I'd love to help here, but `.Net`, not so much for me.

**Comment by erikzhang** [comment]
Try this:
```
neo-cli.exe
```

**Comment by metachris** [comment]
It is very important that `dotnet neo-cli.dll` works.

This allows for all kinds of cross platform integrations on *nix systems, for instance the private network Docker image: https://github.com/CityOfZion/neo-privatenet-docker

**Comment by erikzhang** [comment]
If you need to use `dotnet neo-cli.dll`, you have to install .NET Core Runtime 2.0 first.

**Comment by metachris** [comment]
Oh alright, sorry I think I've mixed things up ^^ I just noticed that the Docker image doesn't work when upgrading to neo-cli 2.5.0, but haven't had the time to look into the cause and assumed this may be related. I'll check later today! Thank you ;)
