### ISSUE TITLE
Send command crashes NEO on Linux

### ISSUE THREAD

**Issue by titanomachy** [neo-project/neo-cli#65]
The send command crashes NEO-cli. The command is being used as it should:
`send <asset id> <address> <amount>`

The invalid operation exception is being returned:
InvalidOperationException: Failed to compare two elements in the array. At least one object must implement IComparable at System.Collections.Comparer.Compare(Object a, Object b)

This is on Debian 8.9, other commands work, NEO-CLI version  is 2.4.1.0

**Comment by i3bitcoin** [comment]
The same here. Rpc calls "sendtoaddress" and "sendmany" also lead to his error
Unhandled Exception: System.InvalidOperationException: Failed to compare two elements in the array. ---> System.ArgumentException: At least one object must implement IComparable.
