### ISSUE TITLE
Changelog for releases

### ISSUE THREAD

**Issue by metachris** [neo-project/neo-cli#68]
Hi @erikzhang 

Could you please add a short Changelog for releases of neo-cli? This could be done either in a `Changelog.md` file, or in the release description directly. This would be very helpful to understand more easily what has changed. 

I'm trying to keep up with the releases with [neo-privatenet-docker](https://github.com/CityOfZion/neo-privatenet-docker) ^^

❤️

**Comment by erikzhang** [comment]
I will do it from next release.
