### ISSUE TITLE
neo-cli >= v2.5.0 doesn't create blocks in neo-privatenet-docker

### ISSUE THREAD

**Issue by metachris** [neo-project/neo-cli#69]
Since v2.5.0, neo-cli consensus nodes don't create blocks in [neo-privatenet-docker](https://github.com/CityOfZion/neo-privatenet-docker). Are there any significant changes or new commands we need to issue? 

Tracking this issue with reproducible steps and the output of neo-cli here: https://github.com/CityOfZion/neo-privatenet-docker/issues/15

Any input on this would be much appreciated.

**Comment by metachris** [comment]
@erikzhang could you perhaps give me a pointer on how I would add the consensus smart contract to the wallet?

**Comment by erikzhang** [comment]
In v2.5.0, I redesigned the wallet model for NEP-6. The new wallet model lacks an API to find account by the public key. So we must add a consensus contract to the wallet before we can start the consensus. The consensus contract is a 5-of-7 multi-signature contract for all consensus nodes.
I will improve the wallet model as soon as possible so that we can open a consensus in the future without adding a consensus contract.

**Comment by gelinger777** [comment]
I have built the source code from master and I have still the same problem in ubuntu with starting the consensus... What to do?

**Comment by metachris** [comment]
@gerlinger777 as I wrote in the other issue, take a close look at how neo-privnet-docker does it. You need to setup the seeds/peers correctly and need to add the consensus contract to the wallet JSONs. It's a bit involved, and if you are not familiar with the whole system I personally would recommend you to use the Docker image.

**Comment by gelinger777** [comment]
do I need to edit anything else than protocol.json too?

**Comment by erikzhang** [comment]
There is no need to add consensus contract any more due to https://github.com/neo-project/neo/commit/a5dab7fb3137fb1182acf4c8279014b80efe320a

**Comment by gelinger777** [comment]
protocol.mainnet.json and protocol.testnet.json files need to be edited IMHO.... those are still with  real chain data.. maybe thats the reason that the Consensus is not starting.. Also should i give command Start Consensus on 1 node or on all paralell? I am giving command on all..

**Comment by gelinger777** [comment]
@metachris  I really appreciate the docker image you did, but here in Gelinger Media we  tend to go with more involved approach to learn it more. No pain, no gain!

**Comment by gelinger777** [comment]
@erikzhang  We have cloned master repository, then we have build it from source , then we have created wallets, edit the protocol.json ( as it was told on the documentation), then we have opened  on each machine 4 wallets  then we have run the consensus command and it's still  stuck on onStart...

**Comment by gelinger777** [comment]
I have edited also protocol.mainnet.json and protocol.testnet.json  and tried , with no success yet.
