### ISSUE TITLE
Starting Consensus

### ISSUE THREAD

**Issue by gelinger777** [neo-project/neo-cli#73]
Hi! We have  a private chain setup as described in your docs. 

We have edited protocol.json added wallet public keys,
IPs with ports and on all nodes have made a command 

Start consensus

and it's stuck 

neo> Start consensus
[14:06:15] OnStart

that's it. Why?

**Comment by metachris** [comment]
Check out this project for a reference on how to do this: https://github.com/CityOfZion/neo-privatenet-docker

You need configs so your consensus nodes find each other, and you need to add the consensus contract to the wallets.

**Comment by gelinger777** [comment]
I have made the configs to the protocol.json and put the ips of 4 nodes + have created manually passwords on all nodes and opened them then I have run the consensus....

**Comment by gelinger777** [comment]
here is my protocol.json 

`{
  "ProtocolConfiguration": {
    "Magic": 7630401,
    "AddressVersion": 23,
    "StandbyValidators": [
   "03e47c92359a600bbc6b90e9564806178c17a34c7ca56db5735e9f0d1f6d03d9d5",
      "024b52792ee782597a042cc4844dc058f0d54b699971bbb6a7494b812b2f176688",
      "0246dbdd4ea41f348404056a0ed2c2f01173106661de40e9da83b1939347849a18",
      "03a580fb34d2465aae4bdafe8496fb032efb32b793d599bb5e0431c98c6e1ecec9"


    ],
    "SeedList": [
      "35.196.222.38:10333",
      "104.196.201.69:10333",
      "35.227.65.217:10333",
      "35.196.15.225:10333"

    ],
    "SystemFee": {
      "EnrollmentTransaction": 1000,
      "IssueTransaction": 500,
      "PublishTransaction": 500,
      "RegisterTransaction": 10000
    }
  }
}





`

**Comment by metachris** [comment]
You could just use this docker image: https://hub.docker.com/r/metachris/neo-privnet-with-gas/

If you run it manually, check out the steps from the neo-privnet-docker repository above. You need special wallets with the consensus contract, and have your nodes in the seeds list.

**Comment by gelinger777** [comment]
yes, I want to do manually. And only on last step where the nodes should come to a consensus, it stucks. I don't like much docker...

**Comment by gelinger777** [comment]
I am using http://docs.neo.org/en-us/node/private-chain.html this tutorial. I am arriving without problems to the Start consensus...

**Comment by erikzhang** [comment]
This is a bug that has been fixed in neo-project/neo@a5dab7f

See #69

**Comment by gelinger777** [comment]
Ok we will try to build the code from the source and then run the chain... I will report back today later on...

**Comment by gelinger777** [comment]
Duplicate of #69
