### ISSUE TITLE
.DB3 on Ubuntu 

### ISSUE THREAD

**Issue by gelinger777** [neo-project/neo-cli#74]
On ubuntu machines, when you try to run command 

create wallet walletname.db3  it complains, that .db3 extension is not allowed. 

Somebody have to use uppercase extension .DB3 so that it will work.

**Comment by erikzhang** [comment]
The db3 format is deprecated and can not be created in the latest version of NEO-CLI.
It is recommended that you create the latest JSON based NEP-6 standard wallet file.

**Comment by gelinger777** [comment]
Please remove the image of commands which has db3 in ending of the command in private chain help doc. That's confusing.

**Comment by erikzhang** [comment]
@Celia18305

**Comment by gelinger777** [comment]
@Celia18305  here we speak about docs here 
http://docs.neo.org/en-us/node/private-chain.html
and image 
![Neo Docs](http://docs.neo.org/assets/privatechain_3.png)
