### ISSUE TITLE
Create bugfix release 2.5.3?

### ISSUE THREAD

**Issue by metachris** [neo-project/neo-cli#76]
Exchanges are looking to integrate nep-5 tokens and want to use the latest official release. Since [this critical bug](https://github.com/neo-project/neo-cli/issues/71) is still present in the latest release 2.5.2, it would be helpful to make a bugfix release that includes the fix that is already in GitHub.

**Comment by erikzhang** [comment]
I will make a release this week.

**Comment by valdor27** [comment]
It would be great to create bugfix release 2.5.3, you said this week @erikzhang ?

**Comment by erikzhang** [comment]
Yes, it is. I will create the release v2.5.4 "this week"...

**Comment by valdor27** [comment]
Awesome ! Great work

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-cli/releases/tag/v2.6.0-preview6
