### ISSUE TITLE
Show asset and/or gas balance per address

### ISSUE THREAD

**Issue by titanomachy** [neo-project/neo-cli#78]
This is on: 
- Debian 8.9 
- NEO-cli 2.5.2

I have one wallet with two addresses X and Y.

If I type `show gas` it only shows the gas from the first address X.

If I type `list asset` it shows me the total balance of both addresses X and Y.

To what extent would it be preferable to have the commands also per address? Something like this:

`show gas`
shows the total GAS balance for all addresses.

`show gas <address>` 
shows the amount of GAS for that specific address.

`show balance`
shows the total NEO balance for all addresses.

`show balance <address>`
shows the NEO balance for that specific address.

Maybe a more generic method would be like the following, then you need just one command:

`show balance <asset> <address>`
If `<address>` is specified it shows the asset balance for that specific address, else it shows the total balance for that asset. If `<asset>` is not specified it shows the NEO balance.

edit: formatting

**Comment by zipotm** [comment]
I have the same issue! And your advice is pretty good:
**Maybe a more generic method would be like the following, then you need just one command:**

**Comment by shargon** [comment]
Closed by inactivity
