### ISSUE TITLE
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/somepath/neo'.

### ISSUE THREAD

**Issue by Fossil01** [neo-project/neo-cli#8]
`root@server:~/neo# dotnet neo-cli.dll
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/somepath/neo'.`

How do I fix this?

Also to be honest. Writing everything in DotNet wasn't very smart IMHO.

**Comment by erikzhang** [comment]
What is your OS version?

**Comment by Fossil01** [comment]
Ubuntu 16.04

**Comment by blueplanet** [comment]
I have also encountered the same problem.

I tried the Ubuntu 14.04 and Ubuntu 16.04.

**Comment by erikzhang** [comment]
OK, neo-cli-ubuntu.16.10-x64.zip is for Ubuntu 16.10.
For other version of ubuntu, you can build it by yourself easily.
```
dotnet restore -r ubuntu.16.04-x64
dotnet publish -c Release -r ubuntu.16.04-x64
```
You can replace the identifier with your OS version.

**Comment by erikzhang** [comment]
This should has resolved the problem and I will close this issue. If not, please feel free to reopen it.
