### ISSUE TITLE
Wallet is not creating

### ISSUE THREAD

**Issue by plash29** [neo-project/neo-cli#82]
$ dotnet neo-cli.dll
NEO-CLI Version: 2.5.2.0

neo> create wallet wallet.db3
The wallet file in the db3 format is not supported.
neo>
neo> create wallet C:\neofile\wallet.db3
The wallet file in the db3 format is not supported.
neo> create wallet C:\neofile\wallet
password: error
neo>

**Comment by metachris** [comment]
The wallets are now JSON format, so just use `wallet.json` for the filename.

**Comment by plash29** [comment]
@metachris   
It create problem with  .json
$ dotnet neo-cli.dll
NEO-CLI Version: 2.5.2.0
neo> create wallet wallet.json
password: error

**Comment by metachris** [comment]
What operating system are you using, and are you running neo-cli manually? Also did you get neo-cli from the releases or from the master branch?

It usually asks for a password:

    # dotnet neo-cli.dll
    NEO-CLI Version: 2.5.2.0

    neo> create wallet wallet.json
    password: ***
    password: ***
    address: AUxJGHF9B1zMMnZ3mSxDvbLtQPpFqTCoEL
    pubkey: 036785af68b8e8cf2259a6699354d7c1bfc1a31553a8750ef0aa2c42de7fd215be

**Comment by plash29** [comment]
@metachris  Window 7 64 bit
yes i am using neo-cli manually. 
I have downloaded the neo-cli from https://github.com/neo-project/neo-cli/releases 
Neo CLI v2.5.2

**Comment by juliavi** [comment]
apparently paths are not really supported. nor is db3.
`C:\neofile\wallet.db3` won't work
but simply `wallet.json` will

**Comment by anshuman-tripathi** [comment]
I'm creating a wallet,It creates but with error message and after this wallet cannot be openned.
neo> create wallet nwallet.json
password: *******
password: *******
address: AGiQqwqKtZC1nFtdb35fziPm4dMCbhvxwx
 pubkey: 027a0ae22f25d8da12a88543307f1d2d7c328ee9a485a9239742b8aee7556b051e
error
neo> open wallet nwallet.json
password: *******
error

**Comment by juliavi** [comment]
have you tried both with ".json" and without?

**Comment by anshuman-tripathi** [comment]
Yeah I've tried with both .json and .db3

**Comment by anshuman-tripathi** [comment]
Yeah I've tried both .json and .db3 but the result is same
I'm doing this on ubuntu 16.04

**Comment by erikzhang** [comment]
Please ignore the error message on version 2.9.2.

**Comment by anshuman-tripathi** [comment]
ignoring the error is not the solution because wallets cannot be opened on opening wallets it also shows that error message and then nothing happens.

**Comment by erikzhang** [comment]
There is a bug in the 2.9.2 version, which means that when you open the wallet, it will display error, but it is already open. You can use the `list address` command to test whether the open is successful.

**Comment by anshuman-tripathi** [comment]
yeah got it. It is working fine. Can you tell me how to do a RPC Call using json for Neo?

**Comment by juliavi** [comment]
Are you doing RPC?
It looks like you've tried CLI

**Comment by juliavi** [comment]
the RPC API is available online. if you'll provide the language you're working with I can point you to the appropriate API wrapper/package

**Comment by anshuman-tripathi** [comment]
ok please tell me how to configure config.json,config.mainnet.json, config.testnet.json files for RPC ?

Like I have this config.testnet.json file so what  should be given in BindAddress , Port, SslCert and SslCertPassword?
{
  "ApplicationConfiguration": {
    "Paths": {
      "Chain": "Chain_{0}",
      "Index": "Index_{0}"
    },
    "P2P": {
      "Port": 20333,
      "WsPort": 20334
    },
    "RPC": {
      "BindAddress": "127.0.0.1",
      "Port": 20332,
      "SslCert": "",
      "SslCertPassword": ""
    },
    "UnlockWallet": {
      "Path": "",
      "Password": "",
      "StartConsensus": false,
      "IsActive": false
    }
  }
}

**Comment by anshuman-tripathi** [comment]
what is the meaning of these first 3 blocks and these ip addresses ? #
![screen shot 2018-11-23 at 6 44 02 pm](https://user-images.githubusercontent.com/44692739/48945402-332fe880-ef50-11e8-92be-ba176e8dbff0.png)

**Comment by anshuman-tripathi** [comment]
ok please tell me how to configure config.json,config.mainnet.json, config.testnet.json files for RPC ?

**Comment by fredrickabhishek** [comment]
@plash29 i got this same issue and my NEO-CLI Version is : 3.0.0-preview1. I solved this by creating the wallet directly through neo-cli.exe. Instead of opening neo-cli.dll through command line interface tools.

this link is the same issue which i raised and closed [https://github.com/neo-project/neo-node/issues/537#issue-556191675](url)
