### ISSUE TITLE
v2.6.0-preview5: chain.acc from consensus nodes does not work 

### ISSUE THREAD

**Issue by metachris** [neo-project/neo-cli#86]
Tried upgrading consensus nodes from neo-cli v2.5.2 to v2.6.0-preview5. 

neo-cli v2.6.0-preview5 errors at start when `chain.acc` from a consensus node is present. Example chain file: [chain.acc.zip](https://github.com/neo-project/neo-cli/files/1608105/chain.acc.zip) (exported from this [Docker privnet image](https://hub.docker.com/r/metachris/neo-privnet-with-gas/)). It does work with a `chain.acc` file from a normal (non-consensus) node.

Error output when starting neo-cli v2.6.0-preview5 with this file present:

    # dotnet neo-cli.dll
    NEO-CLI Version: 2.6.0.0

    neo>
    Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
    at Neo.IO.Caching.DataCache`2.GetAndChange(TKey key, Func`1 factory)
    at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.Persist(Block block)
    at Neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain.PersistBlocks()
    at System.Threading.Thread.ThreadMain_ThreadStart()
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
    Aborted

Steps to export the `chain.acc` file

* Start the [Docker container](https://hub.docker.com/r/metachris/neo-privnet-with-gas/), enter it with `docker exec -it neo-privnet-with-gas /bin/bash`
* Stopped consensus mode (`screen -d -r node1`, `exit`, `dotnet neo-cli.dll`)
* Exported blocks with `export blocks`, which generated attached `chain.acc` file
* From outside the container, get the chain.acc file `docker cp neo-privnet-with-gas:/opt/node1/neo-cli/chain.acc .`

**Comment by Ray-77** [comment]
Although it has not completed the synchronization yet, but it works fine.
![86](https://user-images.githubusercontent.com/17636881/34661078-16ec8efe-f482-11e7-9252-e5d040b252e8.png)
So maybe you should try it again.

**Comment by metachris** [comment]
You exported the chain.acc file? If you try the file I posted in the issue you'll find that neo-cli crashes on start.

**Comment by metachris** [comment]
But yes, without the `chain.acc` file, neo-cli v2.6.0-preview5 syncs just fine.

**Comment by metachris** [comment]
@erikzhang you can close this issue if you want and don't need it anymore. Just wanted to report it, manual resync without chain.acc file worked fine.

**Comment by erikzhang** [comment]
@Ray-77 Can you test the `chain.acc` from @metachris ?

**Comment by Ray-77** [comment]
Is the chain.acc file you have provided used for the main network?

**Comment by metachris** [comment]
No, this is the chain.acc file from a private consensus network node.

**Comment by erikzhang** [comment]
So you can't import it into the mainnet nodes.
