### ISSUE TITLE
Api call getnewaddress doesn't save address and priv key to the wallet file

### ISSUE THREAD

**Issue by i3bitcoin** [neo-project/neo-cli#89]
Hi,

There is a huge bug in the API, which costed a lot of money for me....
Neo-cli version 2.5.2.0

When initializing the **getnewaddress** api call, it returns new address, keeps it in memory but doesn't save to the wallet file, while the cli command **create address** does it perfectly and saves it to the wallet file.

**Comment by erikzhang** [comment]
The latest version has fixed this bug.
