### ISSUE TITLE
neo open wallet

### ISSUE THREAD

**Issue by EminBudak** [neo-project/neo-cli#91]
I want to ask somethink about open wallet function. 
If I start neo-cli and open wallet with password I can make withdraw always until neo cli stopped and started again isnt it ? or open wallet have a time ? Should I open wallet before every withdraw ?

**Comment by erikzhang** [comment]
> If I start neo-cli and open wallet with password I can make withdraw always until neo cli stopped and started again isnt it ?

Yes
