### ISSUE TITLE
invocation transactions process failed

### ISSUE THREAD

**Issue by bitcodernull** [neo-project/neo-cli#94]
I send many Invocation transations, but some of them failed,  most were successful。
I do not know why, or how can i find the reasons of the failure

the failed transactions example:
c5e6edbcf4dda16e9a8530b4130e0ed447e4bfe6e29397fd441c098364a39d31
4834092b35c188ae3b69717e70380964e94517575324bd6e57a994d60f756edb
fa87213545b1304b7e931b134b039e86b45322577c9402d3f40d124a96d6a6f1
0a0a097b49afeeead2d4bca5eb3c319449b14bd385f6f56c6ecc3decc6fab8ba
66c4a3eaf5caf30aa9bfc170ff13f1a2f33df6f604739a4c3d247df59849530b

**Comment by bitcodernull** [comment]
thanks
how to debug or get error logs for invocation tx

**Comment by erikzhang** [comment]
I will add a RPC command for this.
