### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by Fossil01** [neo-project/neo-cli#95]
My neo node running the latest neo-cli on ubuntu 16.04 always terminates itself after a while. The only thing I see is: *Killed*.

Is there any way to check a log file or enable debug mode?

**Comment by erikzhang** [comment]
There's a log file `error.log` in the folder. You can check it for detail information.

**Comment by jonatanblockchain** [comment]
Is neo-cli configured to Testnet o Mainnet?

**Comment by Fossil01** [comment]
@jonatanblockchain Mainnet.

**Comment by jonatanblockchain** [comment]
Paste the log file content and have a look to https://github.com/neo-project/neo-cli/issues/42

**Comment by metachris** [comment]
You can switch between MainNet and TestNet by replacing `protocol.json` with eg. `protocol.testnet.json`: https://github.com/neo-project/neo-cli/tree/master/neo-cli

**Comment by jonatanblockchain** [comment]
@metachris I asked about Testnet or Mainnet because on Testnet my neo-gui crashed at some block. Need to test more.

**Comment by Fossil01** [comment]
I just checked but I do not have an error.log. I do have Logs/2018-01-15.log but that just shows [11:35:43] persist block etc etc.

**Comment by jonatanblockchain** [comment]
Maybe you can get some idea from here:
https://github.com/CityOfZion/neo-privatenet-docker/blob/master/scripts/start_consensus_node.sh
https://github.com/CityOfZion/neo-privatenet-docker/blob/master/scripts/run.sh

**Comment by shivam2901** [comment]
@jonatanblockchain This is for running private net. What should I do to run node with MainNet in production. Only way I'm getting is dotnet neo-cli.dll /rpc.
But that opens cli that will shut down once I close terminal

**Comment by jonatanblockchain** [comment]
You need to launch dotnet neo.cli /rpc and open the wallet. Yes, these scripts are for privatenet but you can get an idea.
https://github.com/neo-project/neo-cli/issues/48

**Comment by shivam2901** [comment]
@jonatanblockchain Thanks, screen works
